using UnityEngine;
namespace DragonTower {
 // Presentation observes real damage cues; never changes the battle clock or hit schedule.
 public sealed class DarkSkillVfx:MonoBehaviour {
  BattleView view;DarkSkillLibrary library;DarkStylePrototype p;SkillData skill;DarkSkillKind kind;
  readonly float[] hits=new float[128];float age=100;Vector2 origin,target;
  public bool DamageFromSkill{get;set;}public int ScheduledHits{get;set;}public int HitsShown{get;private set;}public bool Configured{get;private set;}
  public int ActiveImages=>p==null?0:p.ActiveCount;public int PeakImages=>p==null?0:p.PeakQuads;public int DroppedLayers=>p==null?0:p.DroppedLayers;public Vector2 LastOrigin=>origin;
  int Count=>Mathf.Max(skill==null?1:skill.hitCount,ScheduledHits);
  float End=>skill==null?0:skill.initialHitDelay+(Count-1)*skill.hitInterval;
  public bool FinalImpact=>kind==DarkSkillKind.Apocalypse&&HitsShown>=Count;
  public bool FinalFreeze=>FinalImpact&&age-hits[HitsShown-1]<.055f;
  public bool Active=>Configured&&age<End+1.6f;
  DarkVfxStyle S=>library.style;
  public void Initialize(BattleView owner){view=owner;library=Resources.Load<DarkSkillLibrary>("DarkSkills/Library");}
  public void Configure(SkillData data){Clear();skill=data;Configured=library!=null&&library.Find(data,out kind);if(Configured&&p==null){p=gameObject.AddComponent<DarkStylePrototype>();p.style=library.style;p.Initialize(view);}}
  public void Cast(){if(!Configured)return;Clear();view.TryGetCharacterAnchor(DragonVisualAnchor.SkillOrigin,view.frame,out origin);target=view.frame.InverseTransformPoint(view.enemyArt.rectTransform.TransformPoint(Vector2.zero));age=0;p.Play(DarkSample.DarkEnergy,origin,target);Render();}
  public void Hit(bool first){if(!Configured)return;if(!Active)Cast();if(HitsShown<hits.Length)hits[HitsShown++]=age;Render();}
  public void Step(BattleModel battle,float delta){if(!Configured)return;if(battle==null||battle.Result!=BattleResult.Fighting){Clear();return;}age+=Mathf.Max(0,delta);Render();}
  public void Clear(){age=100;HitsShown=0;p?.Clear();}void OnDisable()=>Clear();
  static float F(float t,float a,float b)=>Mathf.Clamp01((b-t)/(b-a));static Color A(Color c,float a){c.a*=Mathf.Clamp01(a);return c;}static Vector2 D(float a)=>new Vector2(Mathf.Cos(a),Mathf.Sin(a));
  void Render(){if(p==null)return;p.BeginLayers(age);if(Active){switch(kind){case DarkSkillKind.Strike:Strike();break;case DarkSkillKind.Paranoia:Paranoia();break;case DarkSkillKind.Orb:Orb();break;case DarkSkillKind.Apocalypse:Apocalypse();break;}}p.EndLayers();}
  void Inward(Vector2 center,float radius,float time,float alpha){for(int i=0;i<42;i++){float u=Mathf.Repeat(time*2+i/42f,1),a=i*2.39996f+time*.8f;var pos=center+D(a)*(radius*(1-u)+12);p.Line(pos+D(a)*12,pos,2,A(i%3==0?S.bright:S.violet,alpha*Mathf.Sin(u*Mathf.PI)),i%2==0?0:2);if(i%6==0)p.Crystal(pos,5,a,alpha*Mathf.Sin(u*Mathf.PI),2);}}
  void Contact(float t,float scale){if(t<0||t>.18f)return;p.Ring(target,18+t*260,.65f,t*4,3,A(S.bright,F(t,.015f,.18f)),2,5.1f);p.Disc(target,22*scale,.8f,A(S.core,F(t,.035f,.12f)),2);}
  void Burst(Vector2 center,float t,float scale){if(t<0||t>1.5f)return;float u=1-Mathf.Exp(-t*13),f=F(t,.12f,.55f);p.DarkVolume(center,(18+u*64)*scale,t*5,f);if(t<.055f)p.Disc(center,26*scale,.85f,A(S.core,1-t/.055f),2);for(int i=0;i<3;i++)p.Ring(center,(28+u*(90+i*27))*scale,.38f+i*.22f,t+i,Mathf.Max(1,(6-i)*f),A(i==0?S.bright:S.violet,f*.85f),i==1?0:2,5.8f);p.Fragments(center,t,scale,false);for(int i=0;i<18;i++){float a=i*2.4f;var dir=D(a);float start=(25+u*54)*scale,end=(60+u*(80+i%4*20))*scale;p.Line(center+dir*start,center+dir*end,(2+i%3)*f,A(i%4==0?S.pale:S.purple,f),i%2==0?0:2);}}
  void Strike(){if(HitsShown==0)return;float t=age-hits[0];Inward(target,94,t,F(t,.015f,.09f));Burst(target,t,.72f);p.Impulse(t);}
  // A constant-width, volumetric column. Segmented surfaces and intermittent currents avoid spring silhouettes.
  void Column(Vector2 from,Vector2 to,float radius,float time,float alpha){var axis=to-from;var dir=axis.normalized;var n=new Vector2(-dir.y,dir.x);for(int band=0;band<9;band++){float x0=-1+band*2f/9,x1=-1+(band+1)*2f/9;float light=1-Mathf.Abs((x0+x1)*.5f+.2f);Color c=light>.85f?S.blackPurple:light>.55f?S.violet:light>.3f?S.blackPurple:S.navy;for(int j=0;j<22;j++){float u=j/22f,v=(j+1)/22f;float wave=Mathf.Sin(time*11+u*17)*radius*.05f;p.Quad(Vector2.Lerp(from,to,u)+n*(x0*radius+wave),Vector2.Lerp(from,to,u)+n*(x1*radius+wave),Vector2.Lerp(from,to,v)+n*(x1*radius+wave),Vector2.Lerp(from,to,v)+n*(x0*radius+wave),A(c,alpha*.9f));}}
   for(int patch=0;patch<26;patch++){float u=Mathf.Repeat(time*.9f+patch*.071f,1),a=patch*2.39996f+time*5;float side=Mathf.Cos(a)*radius*.82f;var q=Vector2.Lerp(from,to,u)+n*side;float w=radius*(.12f+.12f*Mathf.Sin(a)*Mathf.Sin(a)),len=12+patch%4*7;p.Quad(q-dir*len-n*w,q-dir*len*.7f+n*w*.8f,q+dir*len+n*w*.6f,q+dir*len*.5f-n*w,A(patch%4==0?S.purple:S.blackPurple,alpha*.7f),Mathf.Sin(a)>0?2:1);}
   for(int stream=0;stream<3;stream++)for(int j=0;j<34;j++){float u=j/34f,v=(j+1)/34f,a=time*13+u*12+stream*2.094f,b=time*13+v*12+stream*2.094f;float z=Mathf.Sin(a);if((j+stream*3)%11>4)continue;var x=Vector2.Lerp(from,to,u)+n*Mathf.Cos(a)*radius;var y=Vector2.Lerp(from,to,v)+n*Mathf.Cos(b)*radius;p.Line(x,y,z>0?6:3,A(stream%3==0?S.bright:S.purple,alpha*(z>0?.85f:.28f)),z>0?2:0);}
   for(int i=0;i<24;i++){float u=Mathf.Repeat(time*1.8f+i/24f,1);var pos=Vector2.Lerp(from,to,u)+n*((i%2==0?-1:1)*(radius+10+i%4*7));p.Crystal(pos,3+i%3,time*4+i,alpha*.8f,i%2==0?0:2);}
  }
  void Paranoia(){if(HitsShown==0)return;bool final=HitsShown>=Count;float after=final?age-hits[HitsShown-1]:-1;float duration=Mathf.Max(.1f,End),k=Mathf.Clamp01(age/duration);float fade=final?F(after,0,.12f):1;var center=Vector2.Lerp(origin,target,Mathf.SmoothStep(0,1,k));var dir=(target-origin).normalized;Column(center-dir*86,center+dir*86,58*(1-(final?Mathf.Clamp01(after/.12f)*.7f:0)),age,fade);for(int g=1;g<=3;g++)p.DarkVolume(Vector2.Lerp(origin,center,1-g*.15f),37-g*6,age-g*.04f,fade*.13f);for(int i=0;i<HitsShown;i++)Contact(age-hits[i],1);if(final){Burst(target,after,1.35f);p.Impulse(after);}}
  void Orb(){if(HitsShown==0)return;bool final=HitsShown>=Count;float after=final?age-hits[HitsShown-1]:-1;float k=Mathf.Clamp01(age/Mathf.Max(.1f,End));if(!final){float r=Mathf.Lerp(34,112,Mathf.SmoothStep(0,1,k))*(1-.35f*Mathf.Clamp01((k-.82f)/.18f));p.DarkVolume(target,r,age*3,1);Inward(target,195,age,1);for(int j=0;j<4;j++)p.Ring(target,r*(.8f+j*.08f),.45f+j*.12f,age*(j%2==0?3:-4)+j,2,A(j==0?S.bright:S.purple,.7f),j%2==0?0:2,2.1f);}for(int i=0;i<HitsShown;i++)Contact(age-hits[i],1);if(final){Burst(target,after,1.6f);p.Impulse(after);}}
  void Rift(Vector2 at,float radius,float time,float alpha){for(int layer=0;layer<4;layer++){float r=radius*(1-layer*.065f);for(int j=0;j<64;j++){float a=j*Mathf.PI/32,b=(j+1)*Mathf.PI/32;float ra=r*(1+.12f*Mathf.Sin(j*1.7f)+.04f*Mathf.Sin(time*8+j)),rb=r*(1+.12f*Mathf.Sin((j+1)*1.7f)+.04f*Mathf.Sin(time*8+j+1));var x=at+new Vector2(Mathf.Cos(a)*ra,Mathf.Sin(a)*ra*.26f);var y=at+new Vector2(Mathf.Cos(b)*rb,Mathf.Sin(b)*rb*.26f);p.Quad(at,x,y,at,A(layer==3?S.core:layer==2?S.purple:layer==1?S.bright:S.blackPurple,alpha),layer==0?0:1);}}
   for(int i=0;i<16;i++){float a=i*2.4f;var x=at+new Vector2(Mathf.Cos(a)*radius,Mathf.Sin(a)*radius*.28f);p.Line(x,x+D(a)*(14+i%4*8),2,A(S.purple,alpha),2);}}
  void Apocalypse(){if(HitsShown==0)return;bool final=HitsShown>=Count;float after=final?age-hits[HitsShown-1]:-1;float k=Mathf.Clamp01(age/Mathf.Max(.1f,End));float fade=final?F(after,.015f,.16f):1;var top=target+Vector2.up*182;var bottom=target+Vector2.down*102;float radius=125*Mathf.Min(1,.6f+k*2);Rift(top,radius,age,fade);Rift(bottom,radius*.92f,-age,fade);float reach=Mathf.Clamp01(k*2.5f+.05f);Column(top,Vector2.Lerp(top,target,reach),62+18*k,age,fade);Column(bottom,Vector2.Lerp(bottom,target,reach),65+17*k,-age,fade);Inward(target,185,age,fade);for(int i=0;i<HitsShown;i++)Contact(age-hits[i],1.5f);if(final){Burst(target,after,2.35f);p.Impulse(after,9);for(int i=0;i<12;i++){float a=i*2.4f;var pos=target+D(a)*(52+after*(180+i%4*65));p.Crystal(pos,14+i%3*8,a+after*3,F(after,.15f,.72f),i%2==0?0:2);}}}
 }
}
