using UnityEngine;
namespace DragonTower {
 // Visual-only prototype library. No damage, status application, timers or character mutations.
 public sealed class DarkStylePrototype:MonoBehaviour {
  public DarkVfxStyle style;LightningMeshLayer[] layers;BattleVfxHudVisibility materials;BattleView view;Vector2 target;float age=10;DarkSample sample;
  public int ActiveCount{get;private set;} public int PeakQuads{get;private set;} public int DroppedLayers{get;private set;} public bool Active=>style!=null&&age<style.duration;public bool Clean=>ActiveCount==0;
  static Vector2 D(float a)=>new Vector2(Mathf.Cos(a),Mathf.Sin(a));
  static float R(int n)=>Mathf.Repeat(Mathf.Sin(n*127.1f+31.7f)*43758.5453f,1);
  static Color A(Color c,float a){c.a*=Mathf.Clamp01(a);return c;}
  static float F(float t,float a,float b)=>Mathf.Clamp01((b-t)/(b-a));
  static Vector2 E(Vector2 p,float r,float a,float tilt)=>p+new Vector2(Mathf.Cos(a)*r,Mathf.Sin(a)*r*tilt);
  RectTransform arena;Vector2 home;bool shifted;
  public void Initialize(BattleView owner){if(layers!=null)return;view=owner;materials=new BattleVfxHudVisibility();layers=new LightningMeshLayer[3];for(int i=0;i<3;i++){var go=new GameObject("Dark depth "+i,typeof(RectTransform),typeof(CanvasRenderer),typeof(LightningMeshLayer));var r=go.GetComponent<RectTransform>();r.SetParent(view.frame,false);r.anchorMin=r.anchorMax=r.pivot=Vector2.one*.5f;r.sizeDelta=new Vector2(480,850);layers[i]=go.GetComponent<LightningMeshLayer>();layers[i].raycastTarget=false;layers[i].material=materials.alpha;if(i==0)r.SetSiblingIndex(view.enemyArt.transform.GetSiblingIndex());}BattleVfxHudVisibility.BringHudForward(view);}
  public void Play(DarkSample kind,Vector2 origin,Vector2 hit){Clear();sample=kind;target=hit;age=0;PeakQuads=DroppedLayers=0;}
  void Restore(){if(shifted&&arena!=null)arena.anchoredPosition=home;shifted=false;if(layers!=null)foreach(var l in layers)if(l!=null)l.rectTransform.anchoredPosition=Vector2.zero;}
  public void Clear(){Restore();age=10;ActiveCount=0;if(layers!=null)foreach(var l in layers)if(l!=null){l.Begin();l.End();}}
  void OnDisable()=>Clear();void OnDestroy(){Clear();materials?.Dispose();if(layers!=null)foreach(var l in layers)if(l!=null)Destroy(l.gameObject);}
  public void Impulse(float t,float strength=4){if(t<0||t>.14f)return;if(arena==null)arena=(RectTransform)view.frame.Find("Arena");if(arena==null)return;var q=new Vector2(Mathf.Sin(t*165)*strength,Mathf.Cos(t*130)*strength*.5f)*(1-t/.14f);home=arena.anchoredPosition;arena.anchoredPosition+=q;shifted=true;foreach(var l in layers)l.rectTransform.anchoredPosition=q;}
  public void BeginLayers(float time){Restore();age=time;materials.Update(view);foreach(var l in layers)l.Begin();}
  public void EndLayers(){ActiveCount=0;foreach(var l in layers){ActiveCount+=l.Count;DroppedLayers+=l.Overflow;l.End();}PeakQuads=Mathf.Max(PeakQuads,ActiveCount);}
  public void Quad(Vector2 a,Vector2 b,Vector2 c,Vector2 d,Color color,int depth=1)=>layers[depth].Quad(a,b,c,d,color);
  public void Line(Vector2 a,Vector2 b,float width,Color color,int depth=1)=>layers[depth].Line(a,b,width,color);
  public void Disc(Vector2 p,float radius,float tilt,Color color,int depth=1,int count=36){for(int i=0;i<count;i++)layers[depth].Quad(p,E(p,radius,i*Mathf.PI*2/count,tilt),E(p,radius,(i+1)*Mathf.PI*2/count,tilt),p,color);}
  public void Ring(Vector2 p,float r,float tilt,float rotation,float width,Color color,int depth=1,float span=6.28318f){for(int i=0;i<56;i++){float a=rotation+i*span/56,b=rotation+(i+1)*span/56;layers[depth].Quad(E(p,r-width,a,tilt),E(p,r+width,a,tilt),E(p,r+width,b,tilt),E(p,r-width,b,tilt),color);}}
  // Irregular nested volumes use different centers, not identical recolored silhouettes.
  public void DarkVolume(Vector2 p,float r,float time,float alpha){for(int k=5;k>=0;k--){float size=r*(.35f+k*.14f);var c=k==5?style.navy:k==4?style.blackPurple:k==3?style.violet:k==2?style.purple:style.core;var center=p+D(time*.7f+k)*r*.07f;for(int j=0;j<48;j++){float a=j*Mathf.PI/24,b=(j+1)*Mathf.PI/24;float ra=size*(1+.09f*Mathf.Sin(a*3+time*2+k)+.04f*Mathf.Sin(a*7-time*3)),rb=size*(1+.09f*Mathf.Sin(b*3+time*2+k)+.04f*Mathf.Sin(b*7-time*3));layers[1].Quad(center,E(center,ra,a,.86f),E(center,rb,b,.86f),center,A(c,alpha*(k==5?.4f:.92f)));}}
   for(int arm=0;arm<5;arm++)for(int j=0;j<30;j++){float u=j/30f,v=(j+1)/30f;float a=arm*1.2566f+time*(arm%2==0?1.5f:-1)+u*3.2f,b=arm*1.2566f+time*(arm%2==0?1.5f:-1)+v*3.2f;float rr=r*(.55f+.48f*u);var x=E(p,rr,a,.82f);var y=E(p,r*(.55f+.48f*v),b,.82f);layers[1].Line(x,y,3+5*Mathf.Sin(u*Mathf.PI),A(arm%2==0?style.purple:style.violet,alpha*.75f));if(j%5<2)layers[2].Line(x,y,1.7f,A(style.bright,alpha));}
  }
  public void Crystal(Vector2 p,float size,float angle,float alpha,int depth){Vector2 u=D(angle)*size,v=D(angle+1.57f)*size*.42f;layers[depth].Quad(p-u,p-v,p+u,p+v,A(style.violet,alpha));layers[depth].Quad(p-u,p,p+u,p+v,A(style.bright,alpha));layers[depth].Line(p-u,p+u,1.5f,A(style.pale,alpha*.8f));}
  public void Stars(Vector2 p,float r,float time,float alpha,float contraction){for(int i=0;i<52;i++){float a=i*2.39996f+time*(.7f+R(i)*1.8f),radius=r*(.28f+R(i+3)*.8f)*contraction;float tilt=.28f+R(i+8)*.6f;var q=E(p,radius,a,tilt);int depth=Mathf.Sin(a)>0?0:2;float s=1.4f+R(i+5)*3;layers[depth].Line(q,q-D(a+1.57f)*(5+R(i)*13),1.5f,A(i%6==0?style.gold:style.purple,alpha*.65f));layers[depth].Diamond(q,s,s*1.6f,A(i%5==0?style.gold:style.pale,alpha));if(i%9==0)Crystal(q,s*2.5f,a+time,alpha,depth);}}
  public void CosmicOrbit(Vector2 p,float radius,float time,float alpha,float collapse){float r=radius*collapse;DarkVolume(p,r*.52f,time,alpha);for(int orbit=0;orbit<3;orbit++){float tilt=.27f+orbit*.19f;float rr=r*(1+orbit*.18f);for(int j=0;j<64;j++){float a=j*Mathf.PI/32+time*(orbit%2==0?.9f:-.7f),b=a+Mathf.PI/32;int depth=Mathf.Sin(a)>0?0:2;var x=E(p,rr,a,tilt)+new Vector2(Mathf.Sin(a)*orbit*9,Mathf.Cos(a)*orbit*7);var y=E(p,rr,b,tilt)+new Vector2(Mathf.Sin(b)*orbit*9,Mathf.Cos(b)*orbit*7);layers[depth].Line(x,y,orbit==1?2.5f:5,A(orbit==1?style.gold:style.violet,alpha*.8f));if(j%7<3)layers[depth].Line(x,y,1.4f,A(style.pale,alpha*.8f));}}
   for(int arm=0;arm<4;arm++)for(int j=0;j<44;j++){float u=j/44f,v=(j+1)/44f,a=time*2.1f+arm*1.57f+u*5.8f,b=time*2.1f+arm*1.57f+v*5.8f;var x=E(p,r*(1-u*.82f),a,.53f);var y=E(p,r*(1-v*.82f),b,.53f);layers[Mathf.Sin(a)>0?0:2].Line(x,y,2+7*(1-u),A(arm==0?style.gold:arm%2==0?style.bright:style.purple,alpha*.8f));}
   Disc(p,r*.25f,.86f,A(style.core,alpha),1);Ring(p,r*.28f,.82f,time,2,A(style.bright,alpha),2,4.7f);Stars(p,r*1.5f,time,alpha,1);
  }
  public void ToxicBubble(Vector2 p,float r,float alpha,int depth){Disc(p,r,.92f,A(style.blackPurple,alpha*.9f),depth,18);Ring(p,r,.92f,0,1.8f,A(style.toxic,alpha),depth);Ring(p+Vector2.up*r*.08f,r*.79f,.85f,.6f,1.8f,A(style.lime,alpha),depth,1.5f);layers[depth].Diamond(p+new Vector2(-r*.28f,r*.33f),r*.17f,r*.12f,A(style.poisonPale,alpha));}
  public void ToxicMass(Vector2 p,float r,float time,float alpha){for(int lobe=0;lobe<11;lobe++){float a=lobe*2.4f+time*.25f;var q=p+new Vector2(Mathf.Cos(a)*r*.48f,Mathf.Sin(a*1.4f+time)*r*.45f);float size=r*(.35f+.1f*Mathf.Sin(time*2+lobe));int depth=lobe%3==0?0:1;Disc(q,size,1.1f,A(style.navy,alpha*.55f),depth,24);Disc(q+Vector2.up*4,size*.79f,1.1f,A(style.blackPurple,alpha*.9f),depth,24);Disc(q+new Vector2(-4,5),size*.56f,1.2f,A(style.violet,alpha*.7f),depth,20);if(lobe%2==0){Disc(q+new Vector2(4,-3),size*.42f,.7f,A(style.toxic,alpha*.95f),depth,18);Ring(q,size*.43f,.7f,time+lobe,3,A(style.lime,alpha),depth,2);}}
   for(int i=0;i<10;i++){float u=Mathf.Repeat(time*.4f+i*.101f,1);var q=p+new Vector2((R(i+60)-.5f)*r*1.2f,(u-.45f)*r*1.4f);ToxicBubble(q,4+R(i)*8,alpha*Mathf.Sin(u*Mathf.PI),2);}
  }
  public void Fragments(Vector2 p,float t,float scale,bool toxic){if(t<0)return;for(int i=0;i<(toxic?48:64);i++){float life=.55f+R(i+9)*.85f;if(t>life)continue;float a=i*2.39996f;Vector2 v=D(a)*(70+R(i)*155)*scale;var q=p+v*t+Vector2.down*t*t*(toxic?95:32);float alpha=F(t,life*.5f,life),size=(2+R(i+7)*6)*scale;int depth=i%4==0?0:2;if(toxic){layers[depth].Line(q-v.normalized*size*2,q,size*1.3f,A(style.toxic,alpha));layers[depth].Diamond(q,size,size*.72f,A(style.lime,alpha));layers[depth].Diamond(q+Vector2.up*size*.3f,size*.25f,size*.2f,A(style.poisonPale,alpha));}else Crystal(q,size,a+t*2,alpha,depth);}}
  public void DarkImpact(Vector2 p,float t,float scale){if(t<0||t>1.9f)return;float release=Mathf.Max(0,t-.045f),expand=1-Mathf.Pow(1-Mathf.Clamp01(release/.32f),3);float fade=F(t,.2f,.85f);Disc(p,(24+expand*77)*scale,.87f,A(style.blackPurple,fade),1);if(t<.10f)Disc(p,scale*(t<.045f?42:68),.85f,t<.045f?style.core:style.pale,2);for(int ring=0;ring<3;ring++){float radius=(30+expand*(100+ring*30))*scale;Ring(p,radius,ring==1?.35f:.82f,ring,Mathf.Max(1,(7-ring*2)*fade),A(ring==0?style.bright:style.purple,fade*.85f),ring==2?0:2);}
   for(int i=0;i<14;i++){float a=i*2.39996f;var dir=D(a);float reach=(30+expand*(80+R(i)*110))*scale;var n=D(a+1.57f)*(4+R(i+7)*8)*scale*fade;layers[2].Quad(p+dir*22-n,p+dir*22+n,p+dir*reach,p+dir*reach,A(i%4==0?style.pale:style.purple,fade));}
   Fragments(p,release,scale,false);for(int i=0;i<7;i++){float k=t-.2f-i*.04f;if(k>0)Ring(p+D(i*2.4f)*28,scale*(25+k*28),.5f,k+i,2,A(style.violet,F(k,.2f,1.5f)*.35f),0,3.8f);}
  }
  public void ToxicImpact(Vector2 p,float t){if(t<0||t>2.2f)return;float u=1-Mathf.Exp(-t*12),fade=F(t,.25f,1.1f);ToxicMass(p,35+u*74,t*2,fade);if(t<.075f)Disc(p,25+t*300,.8f,A(style.poisonPale,1-t/.075f),2);Ring(p+Vector2.down*45,40+u*122,.28f,0,4*fade,A(style.toxic,fade),0);Fragments(p,t,1.1f,true);for(int i=0;i<9;i++){float k=t-i*.055f;if(k<0)continue;ToxicBubble(p+new Vector2((R(i+55)-.5f)*160,k*65),5+R(i)*9,F(k,.35f,1.4f)*.7f,2);}ToxicMass(p+Vector2.down*40+Vector2.up*t*25,45,t,F(t,.8f,2.2f)*.28f);}
  public void PoisonStatus(Vector2 p,float time,float alpha){Ring(p+Vector2.down*48,58,.24f,time*.2f,1.5f,A(style.toxic,alpha*.38f),0,5.5f);for(int i=0;i<7;i++){float u=Mathf.Repeat(time*.48f+i*.147f,1);var q=p+new Vector2((i%2==0?-1:1)*(45+R(i)*22),-45+u*115);ToxicBubble(q,3+R(i+6)*4,alpha*Mathf.Sin(u*Mathf.PI)*.8f,i%2==0?0:2);}float pulse=Mathf.Pow(Mathf.Max(0,Mathf.Sin(time*5)),9)*alpha;Ring(p,58,.7f,time,1.6f,A(style.lime,pulse*.4f),2,4.8f);for(int i=0;i<4;i++){float u=Mathf.Repeat(time*.3f+i*.25f,1);Disc(p+new Vector2((R(i)-.5f)*90,-30+u*75),9+u*10,.8f,A(i%2==0?style.violet:style.toxic,Mathf.Sin(u*Mathf.PI)*alpha*.13f),0,16);}}
  public void Step(BattleModel model,float dt){if(layers==null)return;Restore();if(model==null||model.Result!=BattleResult.Fighting){Clear();return;}age+=Mathf.Max(0,dt);materials.Update(view);foreach(var l in layers)l.Begin();if(Active){float end=F(age,2.8f,style.duration);
   if(sample==DarkSample.DarkEnergy){float start=Mathf.SmoothStep(0,1,age/.35f);DarkVolume(target,65*start,age,end);Stars(target,110,age,end,.8f);}
   else if(sample==DarkSample.CosmicCompression){float hit=style.cosmicRelease;if(age<hit){float k=Mathf.Clamp01(age/hit);float squeeze=1-.78f*Mathf.Pow(k,3);CosmicOrbit(target,88,age*(1+k*2),1,squeeze);Stars(target,170,age*2,1,squeeze);}DarkImpact(target,age-hit,1.15f);}
   else if(sample==DarkSample.ToxicCorruption){if(age<style.toxicRelease)ToxicMass(target,Mathf.Lerp(24,78,Mathf.Clamp01(age/style.toxicRelease)),age,1);ToxicImpact(target,age-style.toxicRelease);}
   else if(sample==DarkSample.HeavyDarkImpact){float hit=style.heavyRelease;if(age<hit){float k=age/hit;DarkVolume(target,Mathf.Lerp(110,17,k*k),age*3,1);Stars(target,190,age*3,1,1-k*.8f);for(int i=0;i<3;i++)Ring(target,Mathf.Lerp(155+i*20,24,k),.75f,age+i,2,A(style.bright,k*.8f),0,4.8f);}float impact=age-hit;DarkImpact(target,impact,1.65f);Impulse(impact);}
   else if(model.EnemyPoisoned)PoisonStatus(target,age,end);
  }ActiveCount=0;foreach(var l in layers){ActiveCount+=l.Count;DroppedLayers+=l.Overflow;l.End();}PeakQuads=Mathf.Max(PeakQuads,ActiveCount);}
 }
}
