using UnityEngine;using UnityEngine.UI;
namespace DragonTower {
 // Art-only compositions. No skill data, combat event, status, HP or cooldown writes.
 public sealed class EarthStylePrototype:MonoBehaviour {
  public EarthVfxStyle style;const int PerLayer=768;Image[][] pool;RectTransform[] roots;int[] used=new int[3],last=new int[3];BattleView view;BattleVfxHudVisibility materials;RectTransform arena;Vector2 arenaHome,source,ground;float age=10;bool shifted;EarthSample sample;
  public int ActiveCount{get;private set;}public int PeakImages{get;private set;}public int DroppedLayers{get;private set;}public bool Active=>age<3.15f;public bool Clean=>ActiveCount==0&&!shifted;
  public void Initialize(BattleView owner){if(pool!=null)return;view=owner;materials=new BattleVfxHudVisibility();arena=(RectTransform)view.frame.Find("Arena");pool=new Image[3][];roots=new RectTransform[3];for(int g=0;g<3;g++){var go=new GameObject("Earth depth "+g,typeof(RectTransform),typeof(RectMask2D));var r=go.GetComponent<RectTransform>();roots[g]=r;r.SetParent(view.frame,false);r.anchorMin=r.anchorMax=r.pivot=Vector2.one*.5f;r.anchoredPosition=new Vector2(0,85);r.sizeDelta=new Vector2(480,620);if(g==0)r.SetSiblingIndex(view.enemyArt.transform.GetSiblingIndex());if(g==1)r.SetSiblingIndex(view.playerArt.transform.GetSiblingIndex());pool[g]=new Image[PerLayer];for(int i=0;i<PerLayer;i++){var child=new GameObject("Earth pooled "+g+"-"+i,typeof(RectTransform),typeof(Image));var im=child.GetComponent<Image>();im.rectTransform.SetParent(r,false);im.raycastTarget=false;im.material=materials.alpha;pool[g][i]=im;child.SetActive(false);}}BattleVfxHudVisibility.BringHudForward(view);}
  public void Play(EarthSample kind,Vector2 origin,Vector2 targetGround){Clear();sample=kind;source=origin;ground=targetGround;age=0;PeakImages=DroppedLayers=0;}
  public void Step(BattleModel model,float delta){Restore();if(pool==null)return;if(model==null||model.Result!=BattleResult.Fighting){Clear();return;}age+=Mathf.Max(0,delta);materials.Update(view);for(int g=0;g<3;g++)used[g]=0;if(Active){float impact=sample==EarthSample.SeismicWave?.60f:.18f;float h=age-impact;float hold=sample==EarthSample.HeavyFinalImpact?.055f:.033f;float local=Mathf.Max(0,h-hold);if(age<impact)Compress(ground,age/impact,sample==EarthSample.HeavyFinalImpact?1.5f:.85f);switch(sample){case EarthSample.GroundImpact:if(h>=0)Impact(ground,local,1,0);break;case EarthSample.GroundRise:Rise(ground,age,1.2f,2);break;case EarthSample.SeismicWave:for(int i=0;i<6;i++){float t=age-.10f-i*.10f;if(t>=0){var p=Vector2.Lerp(source,ground,(i+1)/6f);Impact(p,t,.43f+i*.055f,i);if(i%2==0)Rise(p,t,.35f,i+4);}}break;default:if(h>=0){Impact(ground,local,1.6f,3);for(int i=0;i<3;i++)Rise(ground+new Vector2((i-1)*81,(i%2)*22),local-.045f-i*.028f,i==1?1.05f:.73f,6+i);}break;}float duration=sample==EarthSample.HeavyFinalImpact?.20f:.12f;float amp=sample==EarthSample.HeavyFinalImpact?9:sample==EarthSample.GroundRise?4:2.5f;if(h>=0&&h<duration){float impulse=amp*(1-h/duration);var offset=new Vector2(Mathf.Sin(h*103)*impulse,Mathf.Cos(h*83)*impulse*.65f);arenaHome=arena.anchoredPosition;arena.anchoredPosition+=offset;shifted=true;foreach(var r in roots)r.anchoredPosition=new Vector2(0,85)+offset;}}ActiveCount=0;for(int g=0;g<3;g++){for(int i=used[g];i<last[g];i++)pool[g][i].gameObject.SetActive(false);last[g]=used[g];ActiveCount+=used[g];}PeakImages=Mathf.Max(PeakImages,ActiveCount);}
  void Restore(){if(shifted&&arena!=null)arena.anchoredPosition=arenaHome;shifted=false;if(roots!=null)foreach(var r in roots)if(r!=null)r.anchoredPosition=new Vector2(0,85);}
  public void Clear(){Restore();age=10;ActiveCount=0;if(pool!=null)for(int g=0;g<3;g++){for(int i=0;i<last[g];i++)if(pool[g][i]!=null)pool[g][i].gameObject.SetActive(false);last[g]=used[g]=0;}}
  void OnDisable()=>Clear();void OnDestroy(){Clear();materials?.Dispose();if(roots!=null)foreach(var r in roots)if(r!=null)Destroy(r.gameObject);}
  void Draw(EarthModule module,float frame,Vector2 p,Vector2 size,float alpha=1,int layer=1,float angle=0,float reveal=1,bool rotate=false){if(alpha<=.002f||reveal<=0)return;if(used[layer]>=PerLayer){DroppedLayers++;return;}var im=pool[layer][used[layer]++];im.sprite=rotate?style.RotatingRock(frame):style.Frame(module,frame);im.color=new Color(1,1,1,Mathf.Clamp01(alpha));im.type=reveal<1?Image.Type.Filled:Image.Type.Simple;im.fillMethod=Image.FillMethod.Vertical;im.fillOrigin=0;im.fillAmount=reveal;var r=im.rectTransform;r.anchorMin=r.anchorMax=r.pivot=Vector2.one*.5f;r.anchoredPosition=new Vector2(Mathf.Round(p.x/2)*2,Mathf.Round((p.y-85)/2)*2);r.sizeDelta=size;r.localRotation=Quaternion.Euler(0,0,angle);if(!im.gameObject.activeSelf)im.gameObject.SetActive(true);}
  // Shared art renderer: leaves the standalone prototype compositions unchanged.
  public void BeginLayers(float time,bool heavy=false){Restore();age=time;sample=heavy?EarthSample.HeavyFinalImpact:EarthSample.GroundImpact;materials.Update(view);for(int g=0;g<3;g++)used[g]=0;}
  public void EndLayers(){ActiveCount=0;for(int g=0;g<3;g++){for(int i=used[g];i<last[g];i++)if(pool[g][i]!=null)pool[g][i].gameObject.SetActive(false);last[g]=used[g];ActiveCount+=used[g];}PeakImages=Mathf.Max(PeakImages,ActiveCount);}
  public void Layer(EarthModule module,float phase,Vector2 p,Vector2 size,float alpha=1,int depth=1,float angle=0)=>Draw(module,phase,p,size,alpha,depth,angle);
  public void SpriteLayer(Sprite sprite,Vector2 p,Vector2 size,float alpha=1,int depth=1,float angle=0,float reveal=1){if(sprite==null||alpha<=.002f||reveal<=0)return;if(used[depth]>=PerLayer){DroppedLayers++;return;}var im=pool[depth][used[depth]++];im.sprite=sprite;im.color=new Color(1,1,1,Mathf.Clamp01(alpha));im.type=reveal<1?Image.Type.Filled:Image.Type.Simple;im.fillMethod=Image.FillMethod.Vertical;im.fillOrigin=0;im.fillAmount=reveal;var r=im.rectTransform;r.anchorMin=r.anchorMax=r.pivot=Vector2.one*.5f;r.anchoredPosition=new Vector2(Mathf.Round(p.x/2)*2,Mathf.Round((p.y-85)/2)*2);r.sizeDelta=size;r.localRotation=Quaternion.Euler(0,0,angle);if(!im.gameObject.activeSelf)im.gameObject.SetActive(true);}
  public void Impulse(float time,float strength,float duration){if(time<0||time>=duration||arena==null)return;float a=strength*(1-time/duration);var offset=new Vector2(Mathf.Sin(time*103)*a,Mathf.Cos(time*83)*a*.65f);arenaHome=arena.anchoredPosition;arena.anchoredPosition+=offset;shifted=true;foreach(var r in roots)if(r!=null)r.anchoredPosition=new Vector2(0,85)+offset;}
  static float Fade(float h,float start,float end)=>Mathf.Clamp01((end-h)/(end-start));
  void Compress(Vector2 p,float k,float scale){Draw(EarthModule.Shadow,0,p,new Vector2(165,42)*scale,k*.8f,0);for(int i=0;i<8;i++){float a=i*2.4f;var q=p+new Vector2(Mathf.Cos(a)*65,Mathf.Sin(a)*20)*(1-k)*scale;Draw(EarthModule.Grain,0,q,Vector2.one*7*scale,k,1,i*30);}}
  public void Crack(Vector2 p,float time,float scale,float alpha=1,int layer=0){if(time<0)return;Draw(EarthModule.Crack,Mathf.Clamp01(time/.14f),p,new Vector2(270,95)*scale,alpha*Fade(time,.75f,1.65f),layer);}
  public void Rock(Vector2 p,Vector2 size,float clock,float alpha,int depth=1,float angle=0)=>Draw(EarthModule.Rock,clock,p,size,alpha,depth,angle,1,true);
  public void Dust(Vector2 p,Vector2 size,float phase,float alpha,int depth)=>Draw(EarthModule.DustCloud,phase,p,size,alpha,depth);
  public void Shockwave(Vector2 p,float h,float scale,int seed){if(h<0||h>1.05f)return;float expansion=1-Mathf.Pow(1-Mathf.Clamp01(h/.32f),3),fade=Fade(h,.26f,1.05f);Draw(EarthModule.Pressure,h/.55f,p,new Vector2(340,112)*scale,fade*.26f,0);for(int i=0;i<18;i++){float a=i*Mathf.PI*2/18;bool back=Mathf.Sin(a)>.0f;float depth=back?.76f:1.13f;var q=p+new Vector2(Mathf.Cos(a),Mathf.Sin(a)*.30f)*(24+expansion*135)*scale;Draw(EarthModule.DustWave,Mathf.Clamp01(h/.9f),q,new Vector2(58+expansion*32,27+expansion*18)*scale*depth,fade*(back?.55f:.80f),back?0:1,i*13);if(i%2==0)Rock(q+new Vector2(0,8),Vector2.one*(12+i%3*7)*scale,h+i*.17f,fade,back?0:1,i*27);}}
  public void Debris(Vector2 p,float h,float scale,int seed,bool heavy){int count=heavy?style.heavyDebris:24;for(int i=0;i<count;i++){float delay=i%7*.011f+(i%9==0?.12f:0),t=h-delay;if(t<0)continue;float life=.62f+i%6*.105f;if(t>life)continue;float a=i*2.39996f+seed;bool near=i%13==0;int layer=i%4==0?0:near?2:1;float vx=Mathf.Cos(a)*(90+i%5*36)*scale,vy=(100+i%6*36)*scale;var q=p+new Vector2(vx*t,vy*t-330*t*t);float size=(near?42:i%5==0?27:9+i%4*4)*scale;if(near)size*=1+t*.7f;float fade=Fade(t,life-.17f,life);Draw(EarthModule.Shadow,0,new Vector2(q.x,p.y-5),new Vector2(size*1.05f,size*.23f),fade*.45f,0);if(i%3==0)Draw(EarthModule.Grain,0,q,Vector2.one*size*.35f,fade,layer,i*37);else Rock(q,Vector2.one*size,t*(i%2==0?1:-1)+i*.137f,fade,layer,i*23+t*70);}}
  public void Impact(Vector2 p,float h,float scale,int seed){if(h<0||h>2.0f)return;bool heavy=sample==EarthSample.HeavyFinalImpact;Crack(p,h,scale);Draw(EarthModule.Shadow,0,p,new Vector2(170,60)*scale,Fade(h,.6f,1.5f),0);if(h<.13f){Draw(EarthModule.Impact,h/.13f,p+new Vector2(0,14)*scale,new Vector2(180,130)*scale,1,1,seed*23);for(int i=0;i<5;i++)Draw(EarthModule.GroundSlab,i*.17f,p+new Vector2((i-2)*28,10+Mathf.Sin(i)*5)*scale,new Vector2(67,45)*scale,Fade(h,.08f,.24f),1,i*17);}
   Shockwave(p,h-.025f,scale,seed);Debris(p+new Vector2(0,20),h-.025f,scale,seed,heavy);if(h>.035f)for(int i=0;i<8;i++){float t=h-.035f,life=.68f+i%3*.14f;if(t>life)continue;float a=i*2.4f;bool back=i%3==0;var q=p+new Vector2(Mathf.Cos(a)*(45+t*70),Mathf.Sin(a)*18+12+t*30)*scale;Dust(q,new Vector2(95+t*35,58+t*30)*scale*(back?.7f:1),t/life,Fade(t,.18f,life)*(back?.5f:.75f),back?0:1);}if(h>.48f&&h<1.5f)for(int i=0;i<5;i++){float t=h-.48f-i*.033f;if(t<0)continue;var q=p+new Vector2((i-2)*43,95-t*t*235)*scale;if(q.y<p.y)continue;Rock(q,Vector2.one*(18+i%3*8)*scale,t+i,.85f,1,i*24);}}
  public void Rise(Vector2 p,float time,float scale,int seed){if(time<0||time>2.1f)return;float bulge=Mathf.Clamp01(time/.12f),grow=Mathf.Clamp01((time-.14f)/.18f),fade=Fade(time,1.1f,1.9f);Draw(EarthModule.Shadow,0,p,new Vector2(160,55)*scale,fade,0);if(time<.34f)Draw(EarthModule.GroundSlab,.22f,p+new Vector2(0,bulge*8),new Vector2(150,22+bulge*24)*scale,fade,1);Crack(p,time-.055f,scale*1.0f);float height=210*scale;Draw(EarthModule.GroundSlab,.10f+seed%3*.13f,p+new Vector2(0,height*.44f),new Vector2(170*scale,height),fade,1,-8+seed%3*7,grow);if(grow>0&&time<.95f){for(int i=0;i<4;i++)Draw(EarthModule.DustPuff,time,p+new Vector2((i-1.5f)*40,7)*scale,new Vector2(80,38)*scale,Fade(time,.30f,.95f),i%2==0?0:1);Shockwave(p,time-.16f,scale*.9f,seed);}if(time>.12f)Debris(p+new Vector2(0,15),time-.12f,scale*.65f,seed,false);}
 }
}
