using UnityEngine;using UnityEngine.UI;
namespace DragonTower {
 public sealed class EclipseVfx:MonoBehaviour {
  BattleModel bound;BattleView view;DarkStylePrototype p;EclipseSpaceLayer space;SkillData skill;float age=100,impact=-1;Vector2 target,source;bool cast;
  public bool Configured{get;private set;}public bool DamageFromSkill{get;set;}public bool Clean=>!cast&&(p==null||p.ActiveCount==0)&&(space==null||!space.enabled);
  public int HitsShown{get;private set;}public int Peak=>p==null?0:p.PeakQuads;public int Dropped=>p==null?0:p.DroppedLayers;
  public bool FinalFreeze=>cast&&impact>=0&&age-impact<.075f;public bool Casting=>cast&&impact<0;
  DarkVfxStyle S=>p.style;float Duration=>Mathf.Max(skill.initialHitDelay+1.1f,skill.castLockDuration);float Progress=>Mathf.Clamp01(age/Mathf.Max(.1f,skill.initialHitDelay));
  public void Initialize(BattleView owner)=>view=owner;
  public void Configure(SkillData data){Cancel();skill=data;Configured=data!=null&&data.eclipsePresentation;if(!Configured)return;if(p==null){p=gameObject.AddComponent<DarkStylePrototype>();p.style=Resources.Load<DarkSkillLibrary>("DarkSkills/Library").style;p.Initialize(view);var go=new GameObject("Eclipse gravitational arena",typeof(RectTransform),typeof(CanvasRenderer),typeof(EclipseSpaceLayer));space=go.GetComponent<EclipseSpaceLayer>();}space.Bind(view.frame.Find("Arena").GetComponent<Image>());space.enabled=false;}
  public void BindBattle(BattleModel battle){bound=battle;}
  public void Cast(){if(!Configured||cast)return;Cancel();cast=true;age=0;impact=-1;view.TryGetCharacterAnchor(DragonVisualAnchor.CharacterCenter,view.frame,out source);target=view.frame.InverseTransformPoint(view.enemyArt.rectTransform.TransformPoint(Vector2.zero));p.Play(DarkSample.CosmicCompression,source,target);}
  public void Hit(){if(!Configured||!DamageFromSkill||!cast)return;HitsShown++;if(impact<0)impact=age;}
  public void Cancel(){if(cast)bound?.CancelProtectedSkill();cast=false;age=100;impact=-1;HitsShown=0;p?.Clear();if(space!=null)space.enabled=false;LegendaryScreenDimming.Set(this,Color.clear);}
  void OnDisable()=>Cancel();void OnDestroy(){Cancel();if(space!=null)Destroy(space.gameObject);}
  static Vector2 D(float a)=>new Vector2(Mathf.Cos(a),Mathf.Sin(a));static Color A(Color c,float alpha){c.a*=Mathf.Clamp01(alpha);return c;}static float F(float t,float start,float end)=>Mathf.Clamp01((end-t)/(end-start));
  public void Step(BattleModel battle,float dt){if(!Configured)return;if(battle==null||battle.Result!=BattleResult.Fighting){Cancel();return;}if(!cast)return;age+=Mathf.Max(0,dt);if(age>=Duration){Cancel();return;}p.BeginLayers(age);float k=Progress,t=impact<0?-1:age-impact;float fade=t<0?1:F(t,.15f,1.1f);LegendaryScreenDimming.Set(this,new Color(.016f,.006f,.058f,.44f*Mathf.Min(1,age/.2f)*(t<0?1:F(t,0,.22f))));
   var local=(Vector2)space.rectTransform.InverseTransformPoint(view.frame.TransformPoint(target));space.Draw(local,age,Mathf.Clamp01(k*1.3f)*fade,t);
   if(t<0){float growth=Mathf.SmoothStep(0,1,k/.69f),compression=Mathf.Clamp01((k-.77f)/.16f);float radius=Mathf.Lerp(9,163,growth)*Mathf.Lerp(1,.12f,compression);Domain(k);Accretion(target+Vector2.up*(62*(1-compression)),radius,age*(1+k*2),1);Suction(k,compression);Caster(k);if(k>.87f)Cracks(Mathf.Clamp01((k-.87f)/.1f),1);if(k>.94f){p.Disc(target,23,.9f,S.core,2);p.Ring(target,27,.82f,0,1.8f,S.pale,2);}}
   else{Shatter(t);Explosion(t);p.Impulse(t,14);}
   p.EndLayers();
  }
  void Domain(float k){for(int i=0;i<64;i++){float a=i*2.39996f;var q=new Vector2(Mathf.Cos(a)*(170+i%5*16),Mathf.Sin(a)*(315+i%3*35));float brightness=(.3f+.25f*Mathf.Sin(age*2+i))*Mathf.Min(1,k*5);p.Crystal(q,1.2f+i%3*.7f,a,brightness,0);}for(int j=0;j<5;j++){float r=195+j*33;for(int i=0;i<45;i++){float a=i*.12f+age*.1f+j;var x=target+new Vector2(Mathf.Cos(a)*r,Mathf.Sin(a)*r*.74f);var y=target+new Vector2(Mathf.Cos(a+.12f)*r,Mathf.Sin(a+.12f)*r*.74f);if(i%7<4)p.Line(x,y,1,A(S.violet,k*.35f),0);}}}
  void Accretion(Vector2 center,float radius,float time,float alpha){if(radius<1)return;
   // Backward lensed halo plus a tilted accretion disk with foreground occlusion.
   p.Disc(center,radius*.62f,1,A(S.navy,alpha*.65f),0);p.Ring(center,radius*.66f,.93f,time*.2f,8,A(S.violet,alpha*.7f),0);p.Ring(center,radius*.59f,.97f,time*.3f,2,A(S.bright,alpha),0);
   for(int band=0;band<7;band++)for(int i=0;i<108;i++){float a=i*Mathf.PI/54+time*(.8f+band*.09f),b=a+Mathf.PI/54;float r=radius*(.73f+band*.075f);Vector2 x=new Vector2(Mathf.Cos(a)*r,Mathf.Sin(a)*r*.26f),y=new Vector2(Mathf.Cos(b)*r,Mathf.Sin(b)*r*.26f);var rot=Quaternion.Euler(0,0,18);x=(Vector2)(rot*x);y=(Vector2)(rot*y);int depth=Mathf.Sin(a)>0?0:2;float w=radius*(.045f+.012f*Mathf.Sin(a*5+time));Color c=band==0?S.pale:band<3?S.bright:band<5?S.purple:S.violet;p.Line(center+x,center+y,w,A(c,alpha*(.55f+.3f*Mathf.Sin(a*3+time)*Mathf.Sin(a*3+time))),depth);if(band==4&&i%13<4)p.Line(center+x,center+y,1.8f,A(S.gold,alpha),depth);}
   p.Disc(center,radius*.48f,1,A(S.core,alpha),0);p.Ring(center,radius*.5f,.97f,time*.3f,2,A(S.purple,alpha),1,5.7f);
   for(int i=0;i<22;i++){float a=i*2.4f+time,rr=radius*(.8f+i%4*.08f);var q=center+new Vector2(Mathf.Cos(a)*rr,Mathf.Sin(a)*rr*.25f);p.Crystal(q,2+i%3,a,alpha,i%2==0?0:2);}
  }
  void Suction(float k,float collapse){float fade=1-Mathf.Clamp01((k-.94f)/.06f);for(int i=0;i<100;i++){float u=Mathf.Repeat(age*(.27f+k*.16f)+i*.0131f,1),a=i*2.39996f+u*u*6+age*.15f;float r=(40+(1-u)*(240+i%4*65))*(1-collapse*.88f);var pos=target+Vector2.up*(62*(1-collapse))+new Vector2(Mathf.Cos(a)*r,Mathf.Sin(a)*r*1.15f);float size=(1-u)*(2+i%7*1.9f)+1;var tangent=D(a+1.57f);p.Line(pos-tangent*size*3,pos,1+size*.16f,A(i%5==0?S.gold:S.bright,fade*Mathf.Sin(u*Mathf.PI)*.65f),i%3==0?0:2);p.Crystal(pos,size,a,fade*Mathf.Sin(u*Mathf.PI),i%3==0?0:2);}}
  void Caster(float k){float a=F(k,.63f,.90f)*Mathf.Min(1,k*9);p.Ring(source,42,.3f,age*2,2,A(S.gold,a),2,5.7f);p.Disc(source+Vector2.up*9,9,.9f,A(S.pale,a*.85f),2);for(int wing=0;wing<2;wing++)for(int i=0;i<22;i++){float u=i/22f;var q=source+new Vector2((wing==0?-1:1)*(25+u*105),20+Mathf.Sin(u*Mathf.PI)*58);p.Crystal(q,2+i%3,age+i,a*.7f,2);}for(int i=0;i<16;i++){float u=Mathf.Repeat(age*.8f+i/16f,1);var pos=Vector2.Lerp(source,target,u)+new Vector2(Mathf.Sin(u*Mathf.PI)*48,0);p.Crystal(pos,2+i%3,u*6,a*Mathf.Sin(u*Mathf.PI),2);}}
  void Cracks(float growth,float alpha){for(int arm=0;arm<11;arm++){var prev=target;float angle=arm*2.39996f;for(int j=1;j<=7;j++){float distance=j*65*growth;var q=target+D(angle)*distance+D(angle+1.57f)*Mathf.Sin(j*2.3f+arm)*19*growth;p.Line(prev,q,12,A(S.core,alpha),2);p.Line(prev,q,5,A(S.purple,alpha),2);p.Line(prev,q,1.8f,A(S.pale,alpha),2);if(j%2==0){var fork=q+D(angle+.6f)*43*growth;p.Line(q,fork,4,A(S.violet,alpha),2);p.Line(q,fork,1,A(S.bright,alpha),2);}prev=q;}}}
  void Shatter(float t){Cracks(1,F(t,.01f,.23f));float f=F(t,.24f,1.1f);for(int i=0;i<44;i++){float a=i*2.39996f;var home=target+D(a)*(90+i%5*53);bool inward=i%3==0;var pos=inward?Vector2.Lerp(home,target,Mathf.Clamp01(t*2)):home+D(a)*(t*100+t*t*170)*(1+i%3*.4f);float size=(15+i%4*13)*(inward?Mathf.Max(0,1-t*2):1+t*.25f);p.Crystal(pos,size,a+t*(i%2==0?2:-2),f,i%3==0?0:2);}}
  void Explosion(float t){float u=1-Mathf.Exp(-t*13),f=F(t,.12f,.65f);if(t<.06f)p.Disc(target,42+t*1700,.9f,A(t<.025f?S.core:S.pale,.8f),2);p.DarkVolume(target,(35+u*150),t*4,f);for(int j=0;j<5;j++)p.Ring(target,(35+u*(160+j*43)),.36f+j*.14f,j+t,Mathf.Max(1,(8-j)*f),A(j<2?S.pale:S.purple,f),j%2==0?2:0);p.Fragments(target,t,2.8f,false);for(int i=0;i<30;i++){var dir=D(i*2.4f);p.Line(target+dir*(45+u*55),target+dir*(100+u*(180+i%5*24)),3+i%4,A(i%4==0?S.pale:S.bright,f),2);}for(int i=0;i<10;i++)p.Ring(target+D(i*2.4f)*110,30+t*85,.45f,i+t,2,A(S.violet,F(t,.4f,1.1f)*.45f),0,3.8f);}
 }
}
