using UnityEngine;using UnityEngine.UI;
namespace DragonTower {
 public sealed partial class HaesinVfx:MonoBehaviour {
  BattleView view;BattleModel model;HaesinProfile profile;SkillData skill;WaterStylePrototype water;RawImage[] halves;Material[] mats;Image actorCopy,swallowed;RectTransform root;Image actor,enemy;bool actorHidden,enemyHidden,actorEnabled,enemyEnabled;float age=100,contact=100;Vector2 target,ground,home;Vector2 actorSize;readonly Vector3[] corners=new Vector3[4];
  public bool Configured=>profile!=null&&skill==profile.skill;public bool DamageFromSkill{get;set;}public int HitsShown{get;private set;}public bool EnemyHidden=>enemyHidden;public bool ActorsVisible=>actor!=null&&enemy!=null&&actor.enabled&&enemy.enabled;public bool Clean=>age>=100&&!enemyHidden&&!actorHidden&&(water==null||water.ActiveCount==0);public int DroppedLayers=>water==null?0:water.DroppedLayers;public int Peak=>water==null?0:water.PeakQuads;
  public void Initialize(BattleView v){view=v;profile=Resources.Load<HaesinProfile>("VFX/Haesin/Profile");}public void BindBattle(BattleModel b){model=b;}
  public void Configure(SkillData s,Graphic player,Graphic foe){Cancel();skill=s;actor=player as Image;enemy=foe as Image;if(Configured)Ensure();}
  void Ensure(){if(water!=null)return;water=gameObject.AddComponent<WaterStylePrototype>();water.style=profile.style;var oldLayers=view.frame.GetComponentsInChildren<LightningMeshLayer>(true);water.Initialize(view);int depth=0;foreach(var layer in view.frame.GetComponentsInChildren<LightningMeshLayer>(true)){if(System.Array.IndexOf(oldLayers,layer)>=0)continue;var canvas=layer.gameObject.AddComponent<Canvas>();canvas.overrideSorting=true;canvas.sortingOrder=32701+depth++;}var go=new GameObject("Haesin shark and actor",typeof(RectTransform),typeof(Canvas));root=go.GetComponent<RectTransform>();root.SetParent(view.frame,false);root.anchorMin=root.anchorMax=root.pivot=Vector2.one*.5f;root.sizeDelta=new Vector2(480,850);var cv=go.GetComponent<Canvas>();cv.overrideSorting=true;cv.sortingOrder=32702;
   halves=new RawImage[2];mats=new Material[2];for(int i=0;i<2;i++){go=new GameObject("Shark half "+i,typeof(RectTransform),typeof(RawImage));halves[i]=go.GetComponent<RawImage>();halves[i].rectTransform.SetParent(root,false);halves[i].texture=profile.shark;halves[i].raycastTarget=false;mats[i]=new Material(Resources.Load<Shader>("VFX/Haesin/SplitWater"));mats[i].SetFloat("_Half",i==0?1:-1);halves[i].material=mats[i];go.SetActive(false);}
   go=new GameObject("Swallowed enemy visual",typeof(RectTransform),typeof(Image));swallowed=go.GetComponent<Image>();swallowed.rectTransform.SetParent(root,false);swallowed.raycastTarget=false;swallowed.preserveAspect=true;go.SetActive(false);
   go=new GameObject("Sharkid dash visual",typeof(RectTransform),typeof(Image));actorCopy=go.GetComponent<Image>();actorCopy.rectTransform.SetParent(root,false);actorCopy.raycastTarget=false;actorCopy.preserveAspect=true;go.SetActive(false);
  }
  public void Cast(){if(!Configured||model==null)return;Cancel();age=0;contact=100;HitsShown=0;target=view.frame.InverseTransformPoint(enemy.rectTransform.TransformPoint(Vector2.zero));ground=target+Vector2.down*80;actor.rectTransform.GetWorldCorners(corners);Vector2 lo=view.frame.InverseTransformPoint(corners[0]),hi=view.frame.InverseTransformPoint(corners[2]);home=(lo+hi)*.5f;actorSize=hi-lo;water.Play(WaterSample.Whirlpool,home,target);Render();}
  public void Hit(){if(!Configured||!DamageFromSkill)return;HitsShown++;contact=0;age=(float)model.SignatureCastElapsed;ShowEnemy();Render();}
  public void Step(BattleModel b,float dt){if(!Configured||age>=100)return;if(b==null||b.Result==BattleResult.Defeat||(b.Result==BattleResult.Victory&&HitsShown==0)){Cancel();return;}if(b.Result==BattleResult.Fighting){if(!b.SignatureCastLocked&&age<skill.protectedCastDuration-.08f){Cancel();return;}age=(float)b.SignatureCastElapsed;}else age+=dt;contact+=dt;Render();if(age>skill.protectedCastDuration+1)Cancel();}
  void HideEnemy(){if(enemyHidden)return;enemyEnabled=enemy.enabled;enemy.enabled=false;enemyHidden=true;}void ShowEnemy(){if(enemyHidden&&enemy!=null)enemy.enabled=enemyEnabled;enemyHidden=false;}
  void ShowActor(){if(actorHidden&&actor!=null)actor.enabled=actorEnabled;actorHidden=false;if(actorCopy!=null)actorCopy.gameObject.SetActive(false);}
  public void Cancel(){ShowEnemy();ShowActor();if(swallowed!=null)swallowed.gameObject.SetActive(false);age=contact=100;HitsShown=0;water?.Clear();if(halves!=null)foreach(var h in halves)h.gameObject.SetActive(false);if(root!=null)LegendaryScreenDimming.Set(this,Color.clear);}
  void OnDisable(){if(Configured)model?.CancelProtectedSkill();Cancel();}void OnDestroy(){Cancel();if(mats!=null)foreach(var m in mats)Destroy(m);if(root!=null)Destroy(root.gameObject);if(water!=null)Destroy(water);}
  static float F(float t,float a,float b)=>Mathf.Clamp01((b-t)/(b-a));static Vector2 D(float a)=>new Vector2(Mathf.Cos(a),Mathf.Sin(a));static Color A(Color c,float a){c.a*=Mathf.Clamp01(a);return c;}
  void Render(){if(water==null)return;water.BeginLayers(age);if(age<100){float fade=F(age,skill.initialHitDelay,skill.protectedCastDuration+.4f);LegendaryScreenDimming.Set(this,new Color(.005f,.03f,.10f,.35f*fade));water.Whirlpool(ground,245,age,fade);Shadow();WaterColumn();Shark();StationarySlash();if(age>=1.39f&&age<1.52f){float jaw=age-1.39f;water.Flow(target,50+jaw*380,.3f,jaw*3,F(jaw,.04f,.13f),2,2,8,5.4f);water.Droplets(target,jaw,1.2f,F(jaw,.05f,.13f),24);}if(age>=1.39f&&age<1.52f){float u=(age-1.39f)/.13f;water.Flow(home,70*(1-u)+12,.55f,age*20,1,2,2,5,5.5f);water.Disc(home,8+u*13,.6f,profile.style.pale,u,2);}if(HitsShown>0)Explosion(contact);for(int i=0;i<20;i++){float u=Mathf.Repeat(age*.6f+i*.051f,1),a=i*2.399f+age;water.Bubble(ground+new Vector2(Mathf.Cos(a)*(260-u*100),u*190-40),3+i%5,fade*(1-u)*.7f,i%3==0?0:2);}}water.EndLayers();}
  void Shadow(){if(age<.3f||age>.96f)return;float a=(age-.3f)*13;var p=ground+new Vector2(Mathf.Cos(a)*140,Mathf.Sin(a)*34);water.Quad(p+new Vector2(-105,0),p+new Vector2(15,35),p+new Vector2(90,0),p+new Vector2(5,-21),new Color(.005f,.018f,.05f,.9f),1);water.Quad(p,p+new Vector2(5,48),p+new Vector2(38,1),p,new Color(.01f,.08f,.15f,.9f),1);water.Line(p+new Vector2(65,5),p+new Vector2(72,5),3,profile.style.pale,1);water.Flow(ground,175+Mathf.Sin(a)*12,.31f,a,.8f,2,1,7,4);}
  void Shark(){float rise=Mathf.SmoothStep(0,1,Mathf.Clamp01((age-.92f)/.38f)),split=Mathf.Clamp01((age-1.76f)/.20f);bool show=age>=.92f&&age<skill.initialHitDelay+.13f;float fade=1;for(int i=0;i<2;i++){var im=halves[i];im.gameObject.SetActive(show);if(!show)continue;int cell=age<1.39f?0:1;im.uvRect=new Rect(cell*.5f,0,.5f,1);mats[i].SetFloat("_Cell",cell);mats[i].SetFloat("_Form",Mathf.Clamp01((age-.97f)/.32f));mats[i].SetFloat("_Break",Mathf.Clamp01((age-skill.initialHitDelay)/.12f));mats[i].SetFloat("_Age",age<1.48f&&age>1.39f?1.39f:age);var r=im.rectTransform;r.sizeDelta=Vector2.one*600;r.anchoredPosition=target+new Vector2(-126,-72-(1-rise)*390)+new Vector2(-.48f,.88f)*(i==0?1:-1)*split*14;mats[i].SetFloat("_Floor",root.TransformPoint(new Vector3(0,ground.y-25,0)).y);r.localRotation=Quaternion.Euler(0,0,(i==0?1:-1)*split*1.5f);im.color=new Color(1,1,1,fade);}
   bool mouthVisible=age>=1.15f&&age<1.39f;swallowed.gameObject.SetActive(mouthVisible);if(mouthVisible){swallowed.sprite=enemy.sprite;swallowed.color=Color.white;enemy.rectTransform.GetWorldCorners(corners);Vector2 lo=view.frame.InverseTransformPoint(corners[0]),hi=view.frame.InverseTransformPoint(corners[2]);swallowed.rectTransform.sizeDelta=(hi-lo)*Mathf.Lerp(1,.55f,Mathf.Clamp01((age-1.25f)/.14f));swallowed.rectTransform.anchoredPosition=target;}
   if(age>=1.39f&&age<1.79f)HideEnemy();else ShowEnemy();if(age>.92f&&age<1.45f){water.Droplets(ground,age-.92f,1.4f,1,38);water.Flow(ground,180+(age-.92f)*120,.32f,age*3,1,2,3,11,4.4f);}if(age>=1.68f&&age<skill.initialHitDelay){float f=Mathf.Clamp01((age-1.68f)/.20f);var dir=new Vector2(.875f,.485f);water.Line(target-dir*260,target+dir*260,12, A(profile.style.azure,f),2);water.Line(target-dir*260,target+dir*260,5,A(profile.style.pale,f),2);}
  }
  // The combat root and casting position never move. Only an in-place visual swing.
  void StationarySlash(){if(age<1.46f||age>=1.80f){ShowActor();return;}if(!actorHidden){actorEnabled=actor.enabled;actor.enabled=false;actorHidden=true;}float u=Mathf.Clamp01((age-1.46f)/.18f),recover=Mathf.Clamp01((age-1.64f)/.16f);actorCopy.gameObject.SetActive(true);actorCopy.sprite=actor.sprite;actorCopy.color=Color.white;actorCopy.rectTransform.sizeDelta=actorSize;actorCopy.rectTransform.anchoredPosition=home;actorCopy.rectTransform.localScale=Vector3.one;actorCopy.rectTransform.localRotation=Quaternion.Euler(0,0,Mathf.Lerp(Mathf.Lerp(9,-13,u),0,recover));
   float t=age-1.52f;if(t<0||t>.12f)return;var dir=new Vector2(.875f,.485f);var start=target-dir*320;var end=Vector2.Lerp(start,target+dir*340,Mathf.Clamp01(t/.07f));float alpha=F(t,.07f,.12f);water.Line(start,end,31,A(profile.style.deep,alpha*.75f),2);water.Line(start+Vector2.down*3,end,20,A(profile.style.azure,alpha*.85f),2);water.Line(start,end,10,A(profile.style.aqua,alpha),2);water.Line(start,end,4,A(profile.style.pale,alpha),2);water.Line(start,end,1.5f,A(profile.style.foam,alpha),2);for(int i=0;i<12;i++){var q=Vector2.Lerp(start,end,i/12f);water.Droplets(q,t*.7f,.3f,alpha,3);}water.Flow(home,90,.4f,age*18,alpha,2,1,9,3.8f);
  }
 }
}
