using UnityEngine;
namespace DragonTower {
 public sealed class HydraVfx:MonoBehaviour {
  BattleView view;BattleModel bound;DarkStylePrototype p;HydraHeadLayer heads;SkillData skill;Vector2 target,source;float age=100,impact=-1,clock,tickAge=100;int ticks;bool cast;
  public bool Configured{get;private set;}public bool DamageFromSkill{get;set;}public bool Clean=>!cast;public bool Casting=>cast&&impact<0;public bool FinalFreeze=>cast&&impact>=0&&age-impact<.085f;public int Peak=>p==null?0:p.PeakQuads;public int Dropped=>p==null?0:p.DroppedLayers;public int HitsShown{get;private set;}
  DarkVfxStyle S=>p.style;static Vector2 D(float a)=>new Vector2(Mathf.Cos(a),Mathf.Sin(a));static Color A(Color c,float a){c.a*=Mathf.Clamp01(a);return c;}static float Fade(float t,float a,float b)=>Mathf.Clamp01((b-t)/(b-a));
  public void Initialize(BattleView v)=>view=v;
  public void Configure(SkillData s){Cancel();skill=s;Configured=s!=null&&s.hydraPresentation;if(Configured&&p==null){p=gameObject.AddComponent<DarkStylePrototype>();p.style=Resources.Load<DarkSkillLibrary>("DarkSkills/Library").style;p.Initialize(view);var go=new GameObject("Hydra articulated heads",typeof(RectTransform),typeof(CanvasRenderer),typeof(HydraHeadLayer));heads=go.GetComponent<HydraHeadLayer>();heads.Initialize(view);}}
  public void BindBattle(BattleModel b){bound=b;ticks=b.PoisonTickCount;}
  public void Cast(){if(!Configured||cast)return;cast=true;age=0;impact=-1;HitsShown=0;view.TryGetCharacterAnchor(DragonVisualAnchor.CharacterCenter,view.frame,out source);target=view.frame.InverseTransformPoint(view.enemyArt.rectTransform.TransformPoint(Vector2.zero));p.Play(DarkSample.ToxicCorruption,source,target);}
  public void Hit(){if(cast&&DamageFromSkill&&impact<0){impact=age;HitsShown++;}}
  public void Cancel(){if(cast)bound?.CancelProtectedSkill();bound?.CancelPoisonAcceleration();cast=false;age=100;impact=-1;p?.Clear();heads?.Clear();LegendaryScreenDimming.Set(this,Color.clear);}
  void OnDisable()=>Cancel();void OnDestroy(){Cancel();if(heads!=null)Destroy(heads.gameObject);}
  public void Step(BattleModel b,float dt){if(!Configured)return;if(b==null||b.Result!=BattleResult.Fighting){Cancel();return;}clock+=dt;tickAge+=dt;if(ticks!=b.PoisonTickCount){ticks=b.PoisonTickCount;tickAge=0;}target=view.frame.InverseTransformPoint(view.enemyArt.rectTransform.TransformPoint(Vector2.zero));p.BeginLayers(clock);heads.Begin(clock);heads.SetRift(target,cast?Mathf.Clamp01((age+dt)/skill.initialHitDelay):1);
   if(b.EnemyPoisoned){p.PoisonStatus(target,clock*(b.EnemyPoisonAccelerated?2.2f:1),b.EnemyPoisonAccelerated?1:.65f);if(b.EnemyPoisonAccelerated){float pulse=Mathf.Repeat(clock*2.5f,1);p.Ring(target,35+pulse*48,.7f,clock,2,A(S.lime,(1-pulse)*.7f),2);if(tickAge<.25f){p.Ring(target,15+tickAge*190,.7f,0,4,A(S.lime,1-tickAge*4),2);for(int i=0;i<10;i++)Bubble(target+D(i*2.4f)*(20+tickAge*150),3,1-tickAge*4,2);}}}
   if(cast){age+=dt;float k=Mathf.Clamp01(age/skill.initialHitDelay),t=impact<0?-1:age-impact;LegendaryScreenDimming.Set(this,new Color(.018f,.002f,.034f,.46f*Mathf.Min(1,age/.2f)*(t<0?1:Fade(t,0,.35f))));if(t<0){float close=Mathf.SmoothStep(0,1,Mathf.Clamp01((k-.86f)/.14f));Rift(k);Heads(k,close);Caster(k);if(k>.76f)BiteImpact((k-.76f)*2.5f);}else{Explosion(t);p.Impulse(t,16);}if(age>=Mathf.Max(skill.castLockDuration,skill.initialHitDelay+1.3f)){cast=false;LegendaryScreenDimming.Set(this,Color.clear);}}
   p.EndLayers();heads.End();
  }
  void Bubble(Vector2 q,float r,float alpha,int depth){p.Disc(q,r,1,A(S.blackPurple,alpha),depth,12);for(int i=0;i<12;i++){float a=i*Mathf.PI/6,b=(i+1)*Mathf.PI/6;p.Line(q+D(a)*r,q+D(b)*r,1.6f,A(i<4?S.lime:S.toxic,alpha),depth);}p.Line(q+new Vector2(-r*.4f,r*.45f),q+new Vector2(-r*.05f,r*.65f),2,A(S.poisonPale,alpha),depth);}
  static readonly Vector2 axis=new Vector2(.82f,.57236f),normal=new Vector2(-.57236f,.82f);
  float Aperture(float u,float k){float opening=Mathf.SmoothStep(0,1,Mathf.Clamp01(k/.20f*1.45f-u*.45f));float closing=Mathf.SmoothStep(0,1,Mathf.Clamp01(((k-.86f)/.14f)*1.5f-(1-u)*.5f));return Mathf.Pow(Mathf.Sin(u*Mathf.PI),.75f)*136*opening*(1-closing);}
  Vector2 Lip(float u,float k,float side){float jag=Mathf.Sin(u*41+side+age*2)*6+Mathf.Sin(u*97-age*4)*3;return target+axis*((u-.5f)*525)+normal*(side*Aperture(u,k)+jag);}
  void Rift(float k){
   // Fixed tear axis. A travelling rip opens its walls; opposing folds zipper shut.
   for(int i=0;i<64;i++){float u=i/64f,v=(i+1)/64f;var a=Lip(u,k,-1);var b=Lip(v,k,-1);var c=Lip(v,k,1);var d=Lip(u,k,1);float w=Aperture(u,k);if(w<.2f)continue;p.Quad(a,b,c,d,S.core,0);
    for(int side=-1;side<=1;side+=2){var x=Lip(u,k,side);var y=Lip(v,k,side);var deepX=Vector2.Lerp(x,target+axis*((u-.5f)*260)+new Vector2(-21,28),.38f);var deepY=Vector2.Lerp(y,target+axis*((v-.5f)*260)+new Vector2(-21,28),.38f);p.Quad(x,y,deepY,deepX,A(side<0?S.violet:S.blackPurple,.8f),0);p.Line(deepX,deepY,3,A(S.purple,.38f),0);p.Line(x,y,11,A(S.blackPurple,.9f),side<0?1:0);p.Line(x,y,4,A(S.purple,.8f),side<0?1:0);p.Line(x,y,1.5f,A(S.lime,.55f+.25f*Mathf.Sin(u*33-age*13)),2);
     if(i%8==0){var edge=x+normal*side*(15+Mathf.Sin(u*51)*8);p.Line(x,edge,3,S.violet,0);p.Line(edge,edge+axis*17,1.5f,S.toxic,0);}
    }
   }
   for(int strand=0;strand<9;strand++){float offset=(strand-4)*.17f;Vector2 prev=target-axis*185;for(int i=1;i<=27;i++){float u=i/28f;float w=Aperture(u,k);var q=target+axis*((u-.5f)*410)+normal*(w*offset+Mathf.Sin(u*15-age*4+strand)*6);p.Line(prev,q,2+strand%3,A(strand%3==0?S.toxic:S.violet,.20f*Mathf.Min(1,k*6)),0);prev=q;}}
   for(int i=0;i<46;i++){float u=Mathf.Repeat(i*.071f+age*.12f,1),side=i%2==0?-1:1;var q=Lip(u,k,side);float drift=Mathf.Repeat(age*.7f+i*.13f,1);Droplet(q+normal*side*drift*40,normal*side,2+i%3,.8f*(1-drift),i%3==0?2:0);}
   if(k>.86f){float f=Mathf.Sin(Mathf.Clamp01((k-.86f)/.14f)*Mathf.PI);p.Line(target-axis*225,target+axis*225,4,A(S.lime,f),2);}
  }
  void Droplet(Vector2 q,Vector2 velocity,float size,float alpha,int depth){if(alpha<=0)return;var dir=velocity.sqrMagnitude<.001f?Vector2.up:velocity.normalized;var n=new Vector2(-dir.y,dir.x);var tail=q-dir*size*2.4f;p.Quad(q+n*size*.7f,tail,q-n*size*.7f,q,A(S.toxic,alpha*.85f),depth);p.Disc(q,size,.86f,A(S.toxic,alpha),depth,12);p.Disc(q+new Vector2(-size*.24f,size*.3f),size*.50f,.8f,A(S.lime,alpha),depth,10);p.Disc(q+new Vector2(-size*.30f,size*.42f),Mathf.Max(.65f,size*.19f),1,A(S.poisonPale,alpha*.85f),depth,8);}
  void LiquidBurst(float t,float scale){for(int i=0;i<84;i++){float life=.48f+(i%9)*.09f;if(t>life)continue;float a=i*2.39996f;var velocity=D(a)*(80+i%11*19)*scale;var q=target+velocity*t+Vector2.down*t*t*145;Droplet(q,velocity+Vector2.down*t*290,(1.4f+i%5*.48f)*scale,Fade(t,life*.52f,life),i%4==0?0:2);}}
  void Mist(Vector2 q,float r,float t,float alpha){for(int i=0;i<8;i++){float a=i*2.4f+t*.45f;var x=q+new Vector2(Mathf.Cos(a)*r*.45f,Mathf.Sin(a)*r*.35f);p.Disc(x,r*(.30f+i%3*.10f),1.2f,A(i%3==0?S.toxic:i%2==0?S.violet:S.blackPurple,alpha*.24f),i%3==0?1:0,20);}}
  void BiteImpact(float t){float f=Fade(t,.07f,.42f);p.Ring(target,20+(1-Mathf.Exp(-t*15))*96,.6f,t,3,A(S.toxic,f),2);LiquidBurst(t,1.1f);Mist(target,70,t,f);}
  void Heads(float k,float close){float reveal=Mathf.SmoothStep(0,1,Mathf.Clamp01((k-.27f)/.16f)),emerge=Mathf.SmoothStep(0,1,Mathf.Clamp01((k-.36f)/.22f));for(int j=0;j<3;j++){int i=j==2?0:j+1;float side=i==0?0:i==1?-1:1;Vector2 rest=target+new Vector2(side*136,i==0?72:-12);float lunge=Mathf.SmoothStep(0,1,Mathf.Clamp01((k-.71f-i*.009f)/.052f));Vector2 bite=target+new Vector2(side*42,i==0?24:-16);Vector2 head=Vector2.Lerp(rest+Vector2.up*(10*(1-emerge)),bite,lunge);head=Vector2.Lerp(head,target+new Vector2(-25,30),close*.5f);float size=(i==0?92:74)*Mathf.Lerp(.7f,1,emerge);float angle=i==0?-Mathf.PI/2:i==1?-.28f:-Mathf.PI+.28f;float jaw=Mathf.Sin(Mathf.Clamp01((k-.48f)/.29f)*Mathf.PI/2)*.68f*(1-Mathf.Clamp01((k-.775f)/.035f));float alpha=reveal;
    if(alpha>0){Neck(target+new Vector2(side*67,110),head,side,size,alpha*(1-close),lunge);heads.Head(i,head,size,i==0?-.85f:i==1?-.12f:.12f,jaw,alpha);}
    // Exactly two eyes per head; no extra eye-shaped markings.
    for(int eye=0;eye<2;eye++){float light=Mathf.Clamp01((k-(.17f+(i*2+eye)*.016f))/.035f)*(1-close)*(1-reveal);if(light>0){Vector2 f=D(angle),n=D(angle+Mathf.PI/2);var q=head-f*size*.12f+n*((eye==0?-1:1)*size*.24f);p.Line(q-n*size*.09f,q+n*size*.09f,size*.065f,A(S.lime,light),2);p.Line(q-n*size*.055f,q+n*size*.055f,2,A(S.poisonPale,light),2);}}
   }}
  void Neck(Vector2 root,Vector2 head,float side,float size,float alpha,float lunge){Vector2 prev=root;for(int n=1;n<=15;n++){float u=n/15f;Vector2 q=Vector2.Lerp(root,head,u)+new Vector2(side*Mathf.Sin(u*Mathf.PI)*(50-lunge*23),Mathf.Sin(u*Mathf.PI)*22);float width=size*Mathf.Lerp(.58f,.69f,u);p.Line(prev,q,width,A(S.core,alpha),1);p.Line(prev+Vector2.left*8,q+Vector2.left*8,width*.68f,A(Color.Lerp(S.blackPurple,S.violet,.50f),alpha*.90f),1);p.Line(prev+Vector2.right*width*.24f,q+Vector2.right*width*.24f,width*.22f,A(Color.Lerp(S.violet,S.purple,.35f),alpha*.78f),1);float flow=Mathf.Pow(.5f+.5f*Mathf.Sin(u*17-age*11+side),3);p.Line(prev+Vector2.left*width*.32f,q+Vector2.left*width*.32f,2.5f,A(S.toxic,alpha*(.25f+flow*.7f)),2);if(n%3==0)Bubble(q+new Vector2(side*width*.6f,6),5,alpha*.35f,2);prev=q;}}
  void Caster(float k){float f=Fade(k,.3f,.55f);for(int i=0;i<3;i++){var q=source+new Vector2((i-1)*19,18+(i==1?16:0));Bubble(q,8+Mathf.Sin(age*14+i)*2,f,2);p.Ring(q,15,.6f,age,2,A(S.lime,f),2,4);}for(int i=0;i<14;i++){float u=Mathf.Repeat(age+i*.07f,1);Bubble(source+new Vector2(Mathf.Sin(i*2.4f)*35,-28+u*70),3,f*Mathf.Sin(u*Mathf.PI),2);}}
  void Explosion(float t){float u=1-Mathf.Exp(-t*12),f=Fade(t,.2f,1.2f);Mist(target,50+u*180,t*3,f);if(t<.085f)p.Disc(target,28+t*1550,.8f,A(t<.02f?S.core:S.poisonPale,1-t/.1f),2);for(int ring=0;ring<3;ring++)p.Ring(target,25+u*(150+ring*42),.38f+ring*.12f,t+ring,Mathf.Max(1,(5-ring*.65f)*f),A(ring<2?S.lime:S.violet,f),ring%2==0?2:0);LiquidBurst(t,2.6f);for(int i=0;i<42;i++){Vector2 dir=D(i*2.4f);float r=35+u*(100+i%7*26);var q=target+dir*r+Vector2.down*t*t*90;Droplet(q,dir,2+i%5*.65f,f,i%3==0?0:2);}for(int i=0;i<6;i++){float a=i*2.4f;var q=target+D(a)*(95+t*90)+Vector2.up*t*28;p.Disc(q,30+i%4*10,1.2f,A(S.blackPurple,Fade(t,.35f,1.3f)*.5f),0,24);p.Ring(q,20+i%4*9,.9f,t+i,4,A(S.violet,Fade(t,.35f,1.3f)*.3f),0,3.8f);}}
 }
}
