using UnityEngine;
namespace DragonTower {
 // Isolated art compositions. Never writes damage, status, cooldown, timeScale or Animator speed.
 public sealed class LightningStylePrototype:MonoBehaviour {
  public LightningVfxStyle style;LightningMeshLayer[] layers;BattleVfxHudVisibility materials;BattleView view;RectTransform arena;Vector2 home,source,target;bool shifted;float age=10;LightningSample sample;
  public int ActiveCount{get;private set;}public int PeakQuads{get;private set;}public int DroppedLayers{get;private set;}public bool Active=>age<(sample==LightningSample.Paralysis?2.4f:1.25f);public bool Clean=>ActiveCount==0&&!shifted;
  public void Initialize(BattleView owner){if(layers!=null)return;view=owner;arena=(RectTransform)view.frame.Find("Arena");materials=new BattleVfxHudVisibility();layers=new LightningMeshLayer[3];for(int i=0;i<3;i++){var go=new GameObject("Lightning depth "+i,typeof(RectTransform),typeof(CanvasRenderer),typeof(LightningMeshLayer));var r=go.GetComponent<RectTransform>();r.SetParent(view.frame,false);r.anchorMin=r.anchorMax=r.pivot=Vector2.one*.5f;r.sizeDelta=new Vector2(480,850);layers[i]=go.GetComponent<LightningMeshLayer>();layers[i].raycastTarget=false;layers[i].material=materials.alpha;if(i==0)r.SetSiblingIndex(view.enemyArt.transform.GetSiblingIndex());}BattleVfxHudVisibility.BringHudForward(view);}
  public void Play(LightningSample kind,Vector2 origin,Vector2 hit){Clear();sample=kind;source=origin;target=hit;age=0;PeakQuads=DroppedLayers=0;}
  public void Clear(){Restore();age=10;ActiveCount=0;if(layers!=null)foreach(var l in layers){if(l==null)continue;l.Begin();l.End();}}
  void Restore(){if(shifted&&arena!=null)arena.anchoredPosition=home;shifted=false;if(layers!=null)foreach(var l in layers)if(l!=null)l.rectTransform.anchoredPosition=Vector2.zero;}
  void OnDisable()=>Clear();void OnDestroy(){Clear();materials?.Dispose();if(layers!=null)foreach(var l in layers)if(l!=null)Destroy(l.gameObject);}
  public void BeginLayers(float time){Restore();age=time;materials.Update(view);foreach(var l in layers)l.Begin();}
  public void EndLayers(){ActiveCount=0;foreach(var l in layers){ActiveCount+=l.Count;DroppedLayers+=l.Overflow;l.End();}PeakQuads=Mathf.Max(PeakQuads,ActiveCount);}
  public void Impulse(float t,float strength,float duration){if(t<0||t>=duration||arena==null)return;Restore();float k=1-t/duration;var offset=new Vector2(Mathf.Sin(t*165)*strength,Mathf.Cos(t*139)*strength*.65f)*k;home=arena.anchoredPosition;arena.anchoredPosition+=offset;shifted=true;foreach(var l in layers)l.rectTransform.anchoredPosition=offset;}
  public void Line(Vector2 p,Vector2 q,float width,Color color,int depth=1)=>layers[depth].Line(p,q,width,color);
  public void Quad(Vector2 a,Vector2 b,Vector2 c,Vector2 d,Color color,int depth=1)=>layers[depth].Quad(a,b,c,d,color);
  static Color A(Color c,float alpha){c.a*=Mathf.Clamp01(alpha);return c;}
  static float R(int seed){uint x=(uint)(seed*747796405+2891336453u);x=((x>>((int)(x>>28)+4))^x)*277803737u;return ((x>>22)^x)/4294967295f;}
  static float Fade(float t,float start,float end)=>Mathf.Clamp01((end-t)/(end-start));
  public void Step(BattleModel model,float dt){Restore();if(layers==null)return;if(model==null||model.Result!=BattleResult.Fighting){Clear();return;}age+=Mathf.Max(0,dt);materials.Update(view);foreach(var l in layers)l.Begin();if(Active){int seed=(int)(age*style.pathRefreshFps);float hit=sample==LightningSample.ElectricProjectile?.39f:sample==LightningSample.LightningArc?.08f:style.chargeDuration;float t=age-hit;bool heavy=sample==LightningSample.HeavyThunderImpact;
    if(sample==LightningSample.Paralysis)Status(target,age,seed);
    else {if(age<hit){if(sample==LightningSample.ElectricProjectile){Charge(source,Mathf.Clamp01(age/.08f),.7f,seed);if(age>.07f){float k=Mathf.Clamp01((age-.07f)/.32f);Projectile(Vector2.Lerp(source,target,k),source,target,k,seed);}}else Charge(sample==LightningSample.LightningArc?source:target,age/hit,heavy?1.5f:1,seed);}
     if(t>=0){float hold=heavy?.045f:0;float local=Mathf.Max(0,t-hold);if(heavy&&t<hold)seed=3;if(sample==LightningSample.LightningArc){if(t<.16f)Bolt(source,target,1,Fade(t,.055f,.16f),seed,1,true);}else if(sample!=LightningSample.ElectricProjectile&&t<style.strikeDuration+hold){var top=target+new Vector2(heavy?-48:24,310);Bolt(top,target,heavy?2.1f:1.25f,Fade(t,.06f+hold,style.strikeDuration+hold),seed,1,true);if(heavy){Bolt(top+new Vector2(150,-20),target+new Vector2(22,2),.85f,.85f,seed+99,0,true);Bolt(top+new Vector2(-130,-32),target-new Vector2(32,5),.9f,.7f,seed+211,0,true);}}
      Impact(target,local,heavy?1.65f:sample==LightningSample.LightningArc?.73f:1,seed,heavy);
      if(local>.10f&&local<style.residualDuration)Residual(target,local,heavy?1.4f:1,seed);
      if(heavy&&t<.12f){float k=1-t/.12f;var offset=new Vector2(Mathf.Sin(t*165)*6,Mathf.Cos(t*139)*4)*k;if(arena!=null){home=arena.anchoredPosition;arena.anchoredPosition+=offset;shifted=true;}foreach(var l in layers)l.rectTransform.anchoredPosition=offset;}
     }
    }
   }ActiveCount=0;foreach(var l in layers){ActiveCount+=l.Count;DroppedLayers+=l.Overflow;l.End();}PeakQuads=Mathf.Max(PeakQuads,ActiveCount);}
  // Same jagged centerline across five envelopes; branch paths are shorter and narrower.
  static readonly float[] Widths={18f,10f,5.5f,3f,1.5f};
  public void Bolt(Vector2 from,Vector2 to,float scale,float alpha,int seed,int depth,bool branches){var delta=to-from;var normal=new Vector2(-delta.y,delta.x).normalized;const int n=12;for(int envelope=0;envelope<5;envelope++){float width=Widths[envelope]*scale;Color color=envelope==0?A(style.navy,alpha*.50f):envelope==1?A(style.blue,alpha*.55f):envelope==2?A(style.cyan,alpha):envelope==3?A(style.pale,alpha):A(style.core,alpha);var prev=from;for(int i=1;i<=n;i++){float k=i/(float)n;var p=Vector2.Lerp(from,to,k)+normal*((R(seed*31+i*17)-.5f)*44*scale*Mathf.Sin(k*Mathf.PI));layers[depth].Line(prev,p,width*(.72f+.42f*R(seed+i*7)),color);if(envelope==4&&branches&&i>2&&i<11&&i%3==0){var end=p+normal*((i%2==0?1:-1)*(22+R(i+seed)*44))*scale+delta.normalized*28*scale;Bolt(p,end,scale*.32f,alpha*.85f,seed+i,depth,false);}prev=p;}}}
  void Charge(Vector2 p,float k,float size,int seed){for(int i=0;i<7;i++){float a=i*2.39996f;var q=p+new Vector2(Mathf.Cos(a),Mathf.Sin(a))*(1-k)*65*size;layers[1].Diamond(q,2*size,5*size,A(style.pale,k));if(i%2==0)Bolt(q,p,.23f,k*.8f,seed+i,0,false);}layers[1].Diamond(p,5*k*size,12*k*size,A(style.core,k));Ring(p,32*(1-k)*size,.55f,1.5f,A(style.blue,k),0,seed);}
  void Ring(Vector2 p,float radius,float aspect,float width,Color color,int depth,int seed){const int count=40;for(int i=0;i<count;i++){float a=i*Mathf.PI*2/count,b=(i+1)*Mathf.PI*2/count;if(i%9==seed%9)continue;layers[depth].Line(p+new Vector2(Mathf.Cos(a),Mathf.Sin(a)*aspect)*radius,p+new Vector2(Mathf.Cos(b),Mathf.Sin(b)*aspect)*radius,width,color);}}
  void Projectile(Vector2 p,Vector2 start,Vector2 end,float progress,int seed){var direction=(end-start).normalized;var side=new Vector2(-direction.y,direction.x);for(int i=5;i>=1;i--){float a=(6-i)/6f;var q=p-direction*i*12;Bolt(q-side*8,q+direction*20+side*8,.4f,a*.5f,seed+i,0,false);}layers[1].Diamond(p,18,28,style.navy);layers[1].Diamond(p+new Vector2(-2,0),14,23,style.blue);layers[1].Diamond(p+new Vector2(2,3),9,17,style.cyan);layers[2].Diamond(p+new Vector2(-3,6),5,11,style.core);for(int i=0;i<4;i++){float a=age*25+i*1.57f;var q=p+new Vector2(Mathf.Cos(a)*30,Mathf.Sin(a)*17);Bolt(q,p,.4f,1,seed+i,i%2==0?0:2,true);}Ring(p,26,.6f,2,A(style.pale,.75f),2,seed);}
  public void Impact(Vector2 p,float t,float size,int seed,bool heavy){if(t>.7f)return;float flash=Fade(t,.025f,.10f);if(flash>0){Burst(p,69*size,A(style.blue,flash*.45f),1,17);Burst(p,48*size,A(style.cyan,flash*.9f),1,17);Burst(p,24*size,A(style.pale,flash),2,17);layers[2].Diamond(p,10*size,34*size,A(style.core,flash));layers[2].Diamond(p,38*size,5*size,A(style.core,flash));}
   if(t<.25f)for(int i=0;i<(heavy?10:6);i++){float angle=i*2.39996f;var dir=new Vector2(Mathf.Cos(angle),Mathf.Sin(angle)*.73f);Bolt(p+dir*18*size,p+dir*(65+t*170)*size,.40f*size,Fade(t,.08f,.25f),seed+i, i%3==0?0:2,true);}
   float f=Fade(t,.12f,.37f),r=(15+Mathf.Clamp01(t/.16f)*105)*size;Ring(p,r,.40f,5*size,A(style.blue,f*.7f),0,0);Ring(p+Vector2.up*4,r*.84f,.48f,2*size,A(style.pale,f),1,1);Ring(p,r*.60f,1.0f,1.5f,A(style.cyan,f*.5f),1,3);
   int count=heavy?style.heavySparks:style.impactSparks;for(int i=0;i<count;i++){float delay=R(i+34)*.05f,h=t-delay,life=.20f+R(i*3)*.35f;if(h<0||h>life)continue;float a=i*2.39996f;var dir=new Vector2(Mathf.Cos(a),Mathf.Sin(a));bool front=i%7==0;float speed=(130+R(i+7)*280)*size;var q=p+dir*speed*h+Vector2.down*h*h*85;float fade=Fade(h,life*.6f,life);int depth=front?2:i%3==0?0:1;float length=(front?18:8)*size*(1-h/life);layers[depth].Line(q,q-dir*length,front?4:2,A(i%3==0?style.violet:i%2==0?style.cyan:style.core,fade));if(i%5==0&&h<.20f)Bolt(q,q+dir*20,.25f,fade,seed+i,depth,false);}
  }
  void Burst(Vector2 p,float radius,Color col,int depth,int seed){for(int i=0;i<12;i++){float a=i*Mathf.PI/6,b=(i+1)*Mathf.PI/6;float r=radius*(.58f+R(seed+i)*.42f);var tip=p+new Vector2(Mathf.Cos(a),Mathf.Sin(a))*r;var left=p+new Vector2(Mathf.Cos(a-.12f),Mathf.Sin(a-.12f))*radius*.20f;var right=p+new Vector2(Mathf.Cos(a+.12f),Mathf.Sin(a+.12f))*radius*.20f;layers[depth].Quad(p,left,tip,right,col);}}
  public void Residual(Vector2 p,float t,float size,int seed){float f=Fade(t,.18f,style.residualDuration);for(int i=0;i<6;i++){if(R(seed+i)<.35f)continue;float a=i*1.047f;var q=p+new Vector2(Mathf.Cos(a)*75,Mathf.Sin(a)*48)*size;Bolt(q,q+new Vector2((R(seed+i+19)-.5f)*60,20)*size,.35f,f,seed+i,i%2==0?0:2,true);}}
  void Status(Vector2 p,float t,int seed){float fade=Mathf.Min(Mathf.Clamp01(t/.12f),Fade(t,2.15f,2.4f));for(int i=0;i<4;i++){if(R(seed+i*13)<.25f)continue;float a=i*1.57f+R(seed+i)*.4f;var q=p+new Vector2(Mathf.Cos(a)*67,Mathf.Sin(a)*45);var end=p+new Vector2(Mathf.Cos(a+.7f)*60,Mathf.Sin(a+.7f)*44);Bolt(q,end,.30f,fade*.85f,seed+i,i%2==0?0:2,true);if(i==seed%4)layers[2].Diamond(q,3,7,A(style.core,fade));}}
 }
}

