using UnityEngine;
namespace DragonTower {
 public sealed class TimeClockworkVfx:MonoBehaviour {
  BattleView view;LightStylePrototype p;SkillData skill;float age=100,release=-100;int imprints;Vector2 target,enemyPosition;Vector3 enemyScale;Quaternion enemyRotation;Color enemyColor;bool frozen;
  static readonly Color navy=new Color(.025f,.045f,.14f),gold=new Color(.90f,.64f,.27f),pale=new Color(1,.87f,.57f),ivory=new Color(1,.98f,.85f);
  public bool Configured{get;private set;}public bool Clean=>!frozen&&(p==null||p.ActiveCount==0);public int Peak=>p==null?0:p.PeakQuads;public int Dropped=>p==null?0:p.DroppedLayers;public int Imprints=>imprints;
  public void Initialize(BattleView owner)=>view=owner;
  public void Configure(SkillData s){Cancel();skill=s;Configured=s!=null&&s.timeDomain;if(Configured&&p==null){p=gameObject.AddComponent<LightStylePrototype>();p.style=Resources.Load<LightSkillLibrary>("LightSkills/Library").style;p.Initialize(view);}}
  public void Cast(){Cancel();age=0;target=view.frame.InverseTransformPoint(view.enemyArt.rectTransform.TransformPoint(Vector2.zero));p.Play(LightSample.HolyImpact,Vector2.zero,target);}
  public void Freeze(){var r=view.enemyArt.rectTransform;enemyPosition=r.anchoredPosition;enemyScale=r.localScale;enemyRotation=r.localRotation;enemyColor=view.enemyArt.color;frozen=true;}
  public void Store()=>imprints++;
  public void Release(){release=age;frozen=false;}
  public void Cancel(){if(frozen&&view!=null){var r=view.enemyArt.rectTransform;r.anchoredPosition=enemyPosition;r.localScale=enemyScale;r.localRotation=enemyRotation;view.enemyArt.color=enemyColor;}frozen=false;age=100;release=-100;imprints=0;p?.Clear();LegendaryScreenDimming.Set(this,Color.clear);}
  void OnDisable()=>Cancel();
  static Vector2 D(float a)=>new Vector2(Mathf.Cos(a),Mathf.Sin(a));static Color A(Color c,float a){c.a=Mathf.Clamp01(a);return c;}static float Fade(float t,float a,float b)=>Mathf.Clamp01((b-t)/(b-a));
  public void Step(BattleModel b,float dt){if(!Configured)return;if(b==null||b.Result!=BattleResult.Fighting){Cancel();return;}age+=Mathf.Max(0,dt);p.BeginLayers(age);float duration=(float)b.TimeDomainDuration;float elapsed=duration-(float)b.TimeDomainRemaining;float tail=release<0?-1:age-release;
   if(b.TimeDomainBusy){float opening=Mathf.Clamp01(age/Mathf.Max(.01f,skill.timeDomainDelay));LegendaryScreenDimming.Set(this,new Color(.015f,.025f,.10f,.30f*opening));float progress=duration>0?Mathf.Clamp01(elapsed/duration):1;if(b.EnemyTimeStopped&&b.TimeDomainRemaining<=.1)progress=1;float turn=b.EnemyTimeStopped?Mathf.Min(elapsed,Mathf.Max(0,duration-.1f)):0;float power=1+Mathf.Min(imprints,20)*.025f;
    Domain(opening);Clock(target+Vector2.up*30,194*opening,turn,progress,power,1);Gear(target+new Vector2(-168,106),76*opening,-turn*.4f,.7f,0);Gear(target+new Vector2(171,-62),92*opening,turn*.52f,1,1);Gear(target+new Vector2(-143,-126),57*opening,turn*.7f,.7f,0);
    if(!b.EnemyTimeStopped){view.TryGetCharacterAnchor(DragonVisualAnchor.SkillOrigin,view.frame,out var origin);for(int i=0;i<20;i++){var dir=D(i*2.4f);var q=origin+dir*(95*(1-opening)+8);p.Line(q+dir*15,q,2,A(pale,opening),2);}p.Star(origin,24*opening,opening,2);}
    if(b.EnemyTimeStopped){if(!frozen)Freeze();var r=view.enemyArt.rectTransform;r.anchoredPosition=enemyPosition;r.localScale=enemyScale;r.localRotation=enemyRotation;view.enemyArt.color=enemyColor;for(int i=0;i<28;i++){var q=target+D(i*2.4f)*(93+i%4*11);p.Star(q,i%4==0?4:2,.85f,2);}p.Ring(target,118,Quaternion.Euler(37,15,0),0,1.5f,gold,.8f,1,72);DrawImprints(0);if(elapsed<.20f){p.Impact(target,elapsed,1.1f);p.Impulse(elapsed,4,.07f);}if(b.TimeDomainRemaining<.06)Cracks(Mathf.Clamp01((.06f-(float)b.TimeDomainRemaining)/.06f),1);}
   }else if(tail>=0&&tail<1.35f){float t=Mathf.Max(0,tail-.045f);LegendaryScreenDimming.Set(this,new Color(.015f,.025f,.10f,.30f*Fade(t,0,.65f)));Shatter(t);DrawImprints(t+.001f);p.Impact(target,t,2.45f);p.Impulse(tail,12,.18f);p.Disc(target,260,Quaternion.identity,ivory,Fade(t,.035f,.15f)*.55f,2);}else{LegendaryScreenDimming.Set(this,Color.clear);frozen=false;}
   p.EndLayers();
  }
  void Domain(float alpha){for(int i=0;i<7;i++){float y=-270+i*102;p.Line(new Vector2(-225,y),new Vector2(225,y+50),1,A(gold,alpha*.14f),0);}p.Disc(target,295,Quaternion.identity,navy,alpha*.7f,0);}
  void Gear(Vector2 c,float r,float angle,float alpha,int depth){if(r<2)return;var q=Quaternion.Euler(17,22,0);p.Ring(c,r*.78f,q,angle,9,gold,alpha,depth,64);p.Ring(c,r*.68f,q,angle,2,pale,alpha,depth,64);p.Ring(c,r*.26f,q,angle,5,gold,alpha,depth,36);for(int i=0;i<16;i++){float a=angle+i*Mathf.PI/8;var dir=D(a);var n=D(a+Mathf.PI/2);var center=c+dir*r*.9f;p.Quad(center-dir*r*.13f-n*r*.1f,center+dir*r*.13f-n*r*.1f,center+dir*r*.13f+n*r*.1f,center-dir*r*.13f+n*r*.1f,A(gold,alpha),depth);p.Line(center+dir*r*.13f-n*r*.1f,center+dir*r*.13f+n*r*.1f,3,A(ivory,alpha),depth);p.Line(center-dir*r*.12f-n*r*.08f,center+dir*r*.10f-n*r*.08f,2,A(pale,alpha),depth);if(i%2==0)p.Line(c+dir*r*.29f,c+dir*r*.65f,5,A(gold,alpha),depth);}}
  void Clock(Vector2 c,float r,float t,float progress,float power,float alpha){if(r<1)return;var q=Quaternion.Euler(12,-12,0);p.Disc(c,r,q,navy,alpha*.9f,0);p.Ring(c,r,q,0,8,gold,alpha,0,128);p.Ring(c+Vector2.down*4,r*1.025f,q,0,8,navy,alpha,0,128);p.Ring(c,r*.965f,q,0,3,ivory,alpha,0,128);p.Ring(c,r*1.035f,q,0,1.5f,pale,alpha*.9f,2,128);p.Ring(c,r*.77f,q,0,2,pale,alpha,0,96);p.Ring(c,r*.68f,q,-t*.15f,1,gold,alpha,0,96);
   for(int i=0;i<60;i++){float a=i*Mathf.PI/30;var dir=D(a);p.Line(c+dir*r*(i%5==0?.79f:.89f),c+dir*r*.94f,i%5==0?4:1.5f,A(i%5==0?ivory:gold,alpha),0);if(i%5==0)p.Glyph(c,r*.60f,q,a+t*.05f,r*.027f,i,alpha,0);}
   var hand=D(Mathf.PI*.5f-progress*Mathf.PI*2);p.Line(c-hand*26,c+hand*r*.85f,8,A(gold,alpha),0);p.Line(c,c+hand*r*.85f,3,A(ivory,alpha),2);p.Line(c,c+D(2.3f-progress*.5f)*r*.44f,7,A(pale,alpha),0);p.Star(c,20,alpha,2);
   p.Ring(c,r*1.02f,q,-Mathf.PI*.5f,3,pale,alpha*.7f,2,128,progress);for(int i=0;i<12;i++){float a=i*Mathf.PI/6+t*.13f;var pos=c+D(a)*(r+10);p.Star(pos,3*power,alpha*.7f,2);}}
  Vector2 ImprintPoint(int i)=>target+D(i*2.39996f)*(44+(i%5)*18);
  void DrawImprints(float releaseTime){int n=Mathf.Min(imprints,36);for(int i=0;i<n;i++){var c=ImprintPoint(i);var dir=D(.65f+i%3*.7f);float t=releaseTime-i%3*.012f;if(releaseTime<=0){p.Line(c-dir*28,c+dir*28,10,A(pale,.22f),2);var side=new Vector2(-dir.y,dir.x);p.Quad(c-dir*27,c-side*6,c+dir*30,c+side*4,gold,1);p.Line(c-dir*23,c+dir*27,3,ivory,2);p.Ring(c,12,Quaternion.Euler(24,i*13,0),0,1,pale,.65f,1,24);}else if(t>=0&&t<.6f){p.Star(c,32,Fade(t,.035f,.15f),2);p.Line(c-dir*(25+t*120),c+dir*(25+t*120),3,A(ivory,Fade(t,.04f,.35f)),2);}}}
  void Cracks(float growth,float alpha){for(int j=0;j<9;j++){var dir=D(j*.698f);var prev=target;for(int i=1;i<6;i++){float r=i*66*growth;var q=target+dir*r+D(j*.7f+1.57f)*((i%2==0?1:-1)*13);p.Line(prev,q,8,A(navy,alpha),1);p.Line(prev,q,4,A(pale,alpha),1);p.Line(prev,q,1.6f,A(ivory,alpha),2);prev=q;}}}
  void Shatter(float t){float alpha=Fade(t,.25f,1.15f);Cracks(1,Fade(t,.03f,.24f));for(int y=0;y<7;y++)for(int x=0;x<6;x++){int i=y*6+x;var c=new Vector2(-215+x*86+Mathf.Sin(i*7.1f)*19,-315+y*106+Mathf.Cos(i*2.7f)*18);var dir=(c-target).normalized;float depth=1+i%3*.45f;var move=dir*(t*t*220+t*75)*depth+Vector2.down*t*t*70;var a=c+move;float scale=1+t*depth*.4f;var b=a+new Vector2(56+i%4*13,9+i%3*7)*scale;var d=a+new Vector2(9+i%5*8,72+i%4*17)*scale;int layer=i%3==0?1:0;p.Quad(a,b,d,a,A(navy,alpha*.7f),layer);p.Line(a,b,2,A(gold,alpha),layer);p.Line(b,d,1.5f,A(pale,alpha*.7f),layer);if(i%3==0)p.Glyph(a+new Vector2(25,25),0,Quaternion.Euler(0,0,i*17+t*75),i,10*scale,i,alpha,layer);}for(int i=0;i<12;i++){var dir=D(i*2.4f);var c=target+dir*(150+t*160);p.Ring(c,35*(1+t*.6f),Quaternion.Euler(25,i*21,t*90),t*(i%2==0?2:-2),5,gold,alpha,1,30,.34f);}}
 }
}
