using UnityEngine;using UnityEngine.UI;
namespace DragonTower {
 public sealed class VolcanicMeteorVfx:MonoBehaviour {
  const int Capacity=640;BattleView view;BattleModel model;SkillData skill;FireVfxStyle fire;FireStylePrototype burnPainter;BattleVfxHudVisibility materials;Image[] pool;Sprite[] atlas=new Sprite[48];RectTransform rear,front;Image silhouette,arena;Vector2 arenaHome;bool shifted;Vector2 source,target,ground;float age=100,finalAge=-1,contactAge=100;readonly float[] contacts=new float[64];int used;
  public bool Configured=>skill!=null&&skill.volcanicPresentation;public bool DamageFromSkill{get;set;}public int ScheduledHits{get;set;}public int HitsShown{get;private set;}public int HitCount=>Mathf.Max(skill==null?1:skill.hitCount,ScheduledHits);public int PeakImages{get;private set;}public int DroppedLayers{get;private set;}public bool Active=>Configured&&age<End+1.5f;public bool Clean=>used==0&&!shifted&&(burnPainter==null||burnPainter.ActiveCount==0);float End=>skill==null?0:Offset(HitCount-1);public Vector2 LastOrigin=>source;
  float Offset(int i){var times=skill.hitTimeOffsets;int count=Mathf.Max(1,skill.hitCount);return times!=null&&times.Length==count?(i/count)*(times[count-1]+skill.hitInterval)+times[i%count]:skill.initialHitDelay+i*skill.hitInterval;}
  public void Initialize(BattleView owner){view=owner;}public void BindBattle(BattleModel battle){model=battle;}
  public void Configure(SkillData data,Graphic graphic){Cancel();skill=data;if(!Configured)return;Ensure();silhouette.rectTransform.SetParent(graphic.transform,false);silhouette.rectTransform.anchorMin=Vector2.zero;silhouette.rectTransform.anchorMax=Vector2.one;silhouette.rectTransform.offsetMin=silhouette.rectTransform.offsetMax=Vector2.zero;var im=graphic as Image;silhouette.sprite=im==null?null:im.sprite;silhouette.preserveAspect=im!=null&&im.preserveAspect;}
  RectTransform Root(string name){var go=new GameObject(name,typeof(RectTransform),typeof(RectMask2D),typeof(Canvas));var r=go.GetComponent<RectTransform>();r.SetParent(view.frame,false);r.anchorMin=r.anchorMax=r.pivot=Vector2.one*.5f;r.anchoredPosition=new Vector2(0,95);r.sizeDelta=new Vector2(480,660);return r;}
  void Ensure(){if(pool!=null)return;materials=new BattleVfxHudVisibility();fire=Resources.Load<FireSkillLibrary>("FireSkills/Library").style;var sprites=Resources.LoadAll<Sprite>("VFX/VolcanicMeteor/VolcanicAtlas");for(int row=0;row<6;row++)for(int f=0;f<8;f++)foreach(var s in sprites)if(s.name=="Volcanic"+row+"_"+f)atlas[row*8+f]=s;rear=Root("Volcano rear");rear.SetSiblingIndex(view.enemyArt.transform.GetSiblingIndex());front=Root("Volcano front");pool=new Image[Capacity];for(int i=0;i<Capacity;i++){var go=new GameObject("Volcano pooled "+i,typeof(RectTransform),typeof(Image));pool[i]=go.GetComponent<Image>();pool[i].raycastTarget=false;pool[i].rectTransform.SetParent(front,false);go.SetActive(false);}var flash=new GameObject("Volcano silhouette",typeof(RectTransform),typeof(Image));silhouette=flash.GetComponent<Image>();silhouette.raycastTarget=false;silhouette.material=Resources.Load<Material>("VFX/Wisp/Silhouette");flash.SetActive(false);arena=view.frame.Find("Arena").GetComponent<Image>();burnPainter=gameObject.AddComponent<FireStylePrototype>();burnPainter.style=fire;burnPainter.Initialize(view);BattleVfxHudVisibility.BringHudForward(view);}
  public void Cast(){if(!Configured)return;Cancel();view.TryGetCharacterAnchor(DragonVisualAnchor.SkillOrigin,view.frame,out source);target=view.frame.InverseTransformPoint(view.enemyArt.rectTransform.TransformPoint(Vector2.zero));ground=target-new Vector2(0,66);age=0;HitsShown=PeakImages=DroppedLayers=0;for(int i=0;i<contacts.Length;i++)contacts[i]=-1;Render();}
  public void Hit(){if(!Active)Cast();if(HitsShown<contacts.Length)contacts[HitsShown]=age;HitsShown++;contactAge=0;if(HitsShown>=HitCount)finalAge=0;Render();}
  public void Step(BattleModel b,float dt){Restore();if(!Configured||b==null||b.Result==BattleResult.Defeat||(b.Result==BattleResult.Victory&&finalAge<0)){Cancel();return;}age+=dt;contactAge+=dt;if(finalAge>=0)finalAge+=dt;Render();if(burnPainter!=null){burnPainter.BeginLayers(age,target,ground);burnPainter.Status(b.Result==BattleResult.Fighting&&b.EnemyBurning);burnPainter.EndLayers();}float shake=finalAge>=0?(finalAge<.23f?10*(1-finalAge/.23f):0):(contactAge<.065f?1.4f*(1-contactAge/.065f):0);if(shake>0){arenaHome=arena.rectTransform.anchoredPosition;arena.rectTransform.anchoredPosition=arenaHome+new Vector2(Mathf.Sin(contactAge*109),Mathf.Cos(contactAge*91)*.6f)*shake;shifted=true;}silhouette.gameObject.SetActive(contactAge<(finalAge>=0?.075f:.033f));silhouette.color=new Color(1,.76f,.43f,1);}
  void Restore(){if(shifted&&arena!=null)arena.rectTransform.anchoredPosition=arenaHome;shifted=false;}
  public void Cancel(){Restore();age=100;finalAge=-1;contactAge=100;HitsShown=0;if(pool!=null)foreach(var im in pool)if(im!=null)im.gameObject.SetActive(false);used=0;if(silhouette!=null)silhouette.gameObject.SetActive(false);if(burnPainter!=null)burnPainter.Clear();}
  void OnDisable(){if(Configured)model?.CancelTargetModifier();Cancel();}void OnDestroy(){Cancel();materials?.Dispose();if(front!=null)Destroy(front.gameObject);if(rear!=null)Destroy(rear.gameObject);if(silhouette!=null)Destroy(silhouette.gameObject);if(burnPainter!=null)Destroy(burnPainter);}
  Sprite S(int row,float time)=>atlas[row*8+Mathf.FloorToInt(Mathf.Repeat(time*12,8))];
  void Draw(Sprite sprite,Vector2 p,Vector2 size,Color tint,float angle=0,bool back=false,bool glow=false){if(tint.a<=.002f)return;if(used>=Capacity){DroppedLayers++;return;}var im=pool[used++];im.sprite=sprite;im.color=tint;im.material=glow?materials.additive:materials.alpha;var r=im.rectTransform;var parent=back?rear:front;if(r.parent!=parent)r.SetParent(parent,false);r.SetAsLastSibling();r.anchorMin=r.anchorMax=r.pivot=Vector2.one*.5f;r.anchoredPosition=new Vector2(Mathf.Round(p.x/2)*2,Mathf.Round((p.y-95)/2)*2);r.sizeDelta=size;r.localRotation=Quaternion.Euler(0,0,angle);im.gameObject.SetActive(true);}
  static Color W(float a)=>new Color(1,1,1,Mathf.Clamp01(a));
  void F(FireStyleModule module,Vector2 p,Vector2 size,float a=1,float angle=0,bool back=false,bool glow=false,float phase=-1)=>Draw(phase<0?fire.Get(module,age):fire.Frame(module,phase),p,size,W(a),angle,back,glow);
  Vector2 Contact(int i)=>i>=HitCount-1?target:target+new Vector2(Mathf.Sin(i*2.4f)*65,(i%3-1)*17);
  void Render(){if(pool==null)return;int previous=used;used=0;materials.Update(view);if(Active){Sky();if(finalAge<0){Cracks(Mathf.Clamp01(HitsShown/5f),1);for(int i=0;i<HitCount;i++)if(i>=HitsShown)Falling(i);for(int i=0;i<HitsShown&&i<contacts.Length;i++)SmallImpact(Contact(i),age-contacts[i],i);}else Cataclysm(finalAge);}if(model!=null&&model.TargetCriticalRemaining>0)Aftereffect((float)model.TargetCriticalRemaining);for(int i=used;i<previous;i++)pool[i].gameObject.SetActive(false);PeakImages=Mathf.Max(PeakImages,used);}
  void Sky(){float fade=Mathf.Clamp01(age/.16f)*Mathf.Clamp01((End+1.45f-age)/.7f);Draw(null,new Vector2(0,95),new Vector2(480,660),new Color(.065f,.006f,.018f,.66f*fade),0,true);for(int i=0;i<6;i++){var p=new Vector2(-210+i*86+Mathf.Sin(age*.9f+i)*18,350+i%2*40);F(FireStyleModule.Smoke,p,new Vector2(180,130),fade*.78f,i*35,true);F(FireStyleModule.Heat,p,new Vector2(170,100),fade*.30f,0,true);}for(int i=0;i<35;i++){float u=Mathf.Repeat(age*.27f+i*.137f,1);var p=new Vector2(Mathf.Sin(i*2.399f)*240,420-u*590);if(i%3==0)Draw(S(4,age+i),p,Vector2.one*(5+i%4*2),new Color(.33f,.22f,.23f,fade*.7f),i*29,true);else F(FireStyleModule.Ember,p,new Vector2(5,13),fade*(1-u)*.6f,i*19,true,true);}if(age<.4f)for(int i=0;i<14;i++){float u=Mathf.Clamp01(age/.4f);var p=source+new Vector2(Mathf.Sin(i*2.4f)*(15+u*60),u*(140+i%4*35));F(FireStyleModule.Tongue,p,new Vector2(23,60),1-u,i*18,false,true);}}
  void Falling(int i){bool final=i==HitCount-1;float due=Offset(i),travel=final?.40f:.22f+i%3*.055f,begin=due-travel;if(age<begin||age>=due)return;float t=Mathf.Clamp01((age-begin)/travel);var end=Contact(i);var sky=new Vector2(final?-70:Mathf.Sin(i*2.1f)*210,final?560:500+i%2*50);float ease=final?t*t*.65f+t*.35f:t*t;var p=Vector2.Lerp(sky,end,ease);float size=final?Mathf.Lerp(195,290,t):75+i%3*23;var d=end-sky;float angle=Mathf.Atan2(d.y,d.x)*Mathf.Rad2Deg-90;float tail=final?260:140+i%3*40;
   F(FireStyleModule.Shockwave,end-new Vector2(0,56),new Vector2(size*1.4f,size*.32f),.5f,0,true,false,.4f);
   for(int j=6;j>=0;j--){float u=j/6f;var q=p-d.normalized*(tail*u);F(FireStyleModule.Smoke,q,new Vector2(size*(.55f+u*.6f),size*(.7f+u*.4f)),.65f*(1-u*.6f),j*37,true);F(FireStyleModule.Tongue,q,new Vector2(size*(.82f-u*.55f),tail*.6f),.9f*(1-u*.65f),angle+180,true);if(j<4)Draw(S(3,age+j*.08f),q,new Vector2(size*.5f,tail*.65f),W(.65f),angle+180,true,true);}
   F(FireStyleModule.Body,p,Vector2.one*size*1.45f,1,angle+180);Draw(S(0,age+i*.2f),p,Vector2.one*size,W(1),age*(final?37:85)+i*19);Draw(S(1,age+i*.2f),p,Vector2.one*size,W(final?.70f:.38f),age*(final?37:85)+i*19,false,true);for(int k=0;k<8;k++){float u=Mathf.Repeat(age*2+k*.137f,1);var q=p-d.normalized*(u*tail)+new Vector2(Mathf.Sin(k*2.4f)*size*.45f,0);F(FireStyleModule.Ember,q,new Vector2(11,27),1-u,angle+180,false,true);}}
  void Cracks(float power,float fade){if(power<=0)return;for(int i=0;i<5;i++){var p=ground+new Vector2((i-2)*52,Mathf.Sin(i*2.4f)*16);Draw(atlas[16+Mathf.Clamp((int)(power*7),0,7)],p,new Vector2(160,65)*(1+power*.22f),new Color(1,.5f+power*.5f,.25f+power*.75f,fade),i*31,true,power>.6f);if(power>.6f)F(FireStyleModule.Ember,p+new Vector2(0,Mathf.Repeat(age+i*.13f,1)*50),new Vector2(11,24),fade*.7f,i*17,false,true);}}
  void SmallImpact(Vector2 p,float h,int seed){if(h<0||h>.48f)return;float quiet=Offset(HitCount-1)-.50f;float hush=age>=quiet&&age<Offset(HitCount-1)?Mathf.Clamp01((quiet+.025f-age)/.025f):1;float e=1-Mathf.Pow(1-Mathf.Clamp01(h/.15f),3),fade=Mathf.Clamp01((.48f-h)/.25f)*hush;F(FireStyleModule.Burst,p,Vector2.one*(65+e*140),fade,seed*27,false,false,h/.48f);if(h<.07f)F(FireStyleModule.Core,p,Vector2.one*90,1-h/.07f,0,false,true);F(FireStyleModule.Shockwave,p-new Vector2(0,56),new Vector2(110+e*160,30+e*30),fade,0,false,true,h/.48f);for(int k=0;k<10;k++){float a=k*2.399f+seed;var q=p+new Vector2(Mathf.Cos(a)*h*220,Mathf.Sin(a)*h*160-100*h*h);Draw(S(4,age+k),q,Vector2.one*(14+k%3*8),W(fade),k*41+h*110);if(k%2==0)F(FireStyleModule.Ember,q,new Vector2(12,26),fade,a*Mathf.Rad2Deg,false,true);}for(int k=0;k<3;k++)F(FireStyleModule.Smoke,p+new Vector2((k-1)*60,h*40),Vector2.one*(65+h*60),fade*.55f,k*23,true);}
  void Cataclysm(float t){float h=t<.07f?0:t-.07f,e=1-Mathf.Pow(1-Mathf.Clamp01(h/.25f),3),fade=Mathf.Clamp01((1.4f-t)/.7f);Cracks(1,fade);if(t<.13f)Draw(null,new Vector2(0,95),new Vector2(480,660),new Color(1,.47f,.12f,(1-t/.13f)*.7f),0,false,true);
   if(t<.85f){F(FireStyleModule.Burst,target,Vector2.one*(140+e*550),fade,-17,true,false,h/.85f);F(FireStyleModule.Burst,target,Vector2.one*(95+e*440),fade,37,false,false,h/.73f);if(t<.20f)F(FireStyleModule.Core,target,Vector2.one*(130+e*170),1-t/.20f,90,false,true);F(FireStyleModule.Shockwave,ground,new Vector2(170+e*670,45+e*200),fade,0,false,true,h/.8f);}
   // The ground erupts after contact; visual jets do not create extra damage events.
   if(t>.07f)for(int i=0;i<7;i++){float jet=h-i%3*.025f;if(jet<0)continue;float grow=Mathf.Clamp01(jet/.12f),jf=Mathf.Clamp01((.95f-jet)/.4f);var foot=ground+new Vector2((i-3)*57,Mathf.Sin(i*2.4f)*20);float height=(210+i%3*65)*grow;var p=foot+new Vector2(0,height*.38f);Draw(S(3,age+i*.17f),p,new Vector2(90,height),W(jf),((i-3)*-5),i%2==0);Draw(S(3,age*1.4f+i*.2f),p,new Vector2(34,height*.9f),W(jf*.7f),((i-3)*-5),false,true);F(FireStyleModule.Body,p,new Vector2(110,height*1.2f),jf*.7f,(i-3)*-5,true);}
   for(int i=0;i<28;i++){float a=i*2.399f;var q=target+new Vector2(Mathf.Cos(a)*h*(200+i%4*40),Mathf.Sin(a)*h*(180+i%5*35)-120*h*h);float size=(18+i%4*12)*(1-h*.3f);Draw(S(4,age+i*.1f),q,Vector2.one*size,W(fade),i*41+h*110);if(i%3==0)Draw(S(1,age),q,Vector2.one*size,W(fade*.6f),i*41+h*110,false,true);}
   for(int i=0;i<45;i++){float a=i*2.399f;var p=ground+new Vector2(Mathf.Cos(a)*h*(170+i%4*50),h*(200+i%5*80)-h*h*240);F(FireStyleModule.Ember,p,new Vector2(12,27)*(1+i%3*.4f),fade,i*29,i%3==0,true);}
   for(int i=0;i<9;i++){var p=target+new Vector2(Mathf.Sin(i*2.4f)*170,h*100+Mathf.Cos(i*2.4f)*75);F(FireStyleModule.Smoke,p,Vector2.one*(90+h*110),fade*.78f,i*37,true);}F(FireStyleModule.Heat,target+new Vector2(0,h*80),new Vector2(390,350),fade*.24f,0,true);
  }
  void Aftereffect(float remaining){float fade=Mathf.Clamp01(remaining/.65f);float strength=finalAge>=0&&finalAge<1?1:.35f;Draw(atlas[23],ground,new Vector2(150,50),new Color(1,.45f,.15f,fade*.65f),0,true,true);F(FireStyleModule.Shockwave,ground,new Vector2(175,35),fade*.32f,0,true,true,.3f);for(int i=0;i<8;i++){float u=Mathf.Repeat(age*.6f+i*.137f,1);var p=ground+new Vector2(Mathf.Sin(i*2.4f)*80,u*95);F(FireStyleModule.Ember,p,new Vector2(8,17),fade*(1-u)*strength,i*17,false,true);}}
 }
}
