using System;using System.IO;using System.Collections.Generic;using System.Reflection;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.UI;
namespace DragonTower.Editor {
 public static class AscensionValidation {
  static int wait;public static void Run(){AscensionSetup.Install();Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.Ascension.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetBool("AscensionCheck",true);EditorApplication.isPlaying=true;}
  [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("AscensionCheck",false)){wait=0;EditorApplication.update+=After;}};}
  static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("AscensionCheck",false);try{Test();Debug.Log("ASCENSION_VALIDATION_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
  static void Check(bool b,string label){if(!b)throw new Exception("ASCENSION_FAIL "+label);Debug.Log("ASCENSION_CHECK "+label);}
  static void Test(){var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon4.asset");var storm=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon12.asset");var skill=d.signatureSkill;Check(skill!=null&&skill.attackEmpowerDuration==5&&skill.CanEquip(d.StableId)&&!skill.CanEquip(storm.StableId),"exclusive data");
   var stats=d.Snapshot(20);stats.skill=skill.Snapshot();stats.passiveMechanic=DragonPassiveMechanic.None;stats.criticalChance=0;var enemy=BattleEnemyStats.Normal();enemy.maxHP=999999;enemy.interval=100;var unit=new BattleModel(stats,enemy,stats.maxHP,()=>.9);int extras=0,basics=0;double began=-1,ended=-1;unit.Cue+=(cue,damage)=>{if(cue==CombatCue.EmpowerStarted)began=unit.Time;if(cue==CombatCue.EmpowerEnded)ended=unit.Time;if(cue==CombatCue.Attack&&damage>0)basics++;if(cue==CombatCue.EmpoweredAttackHit){Check(unit.EmpoweredHitPattern==extras%3,"ABC "+extras);extras++;}};
   int hp=unit.EnemyHP;Check(unit.Skill(),"cast");Check(unit.EnemyHP==hp,"activation no damage");Check(unit.Attack(),"attack during priming");Check(extras==0,"no early proc");unit.Tick(.24f);Check(unit.AttackEmpowered,"form starts after descent");var ready=unit.AttackReady;Check(!unit.Attack(),"cooldown rejected attack");Check(extras==0,"rejected attack no proc");unit.Tick(.08f);Check(unit.Dodge(),"dodge works");double remaining=unit.AttackEmpowerRemaining;for(int i=0;i<200;i++){unit.Tick(.025f);if(unit.Time<5.2)unit.Attack();}Check(extras>8,"repeated basics proc");Check(Math.Abs(ended-began-5)<.00001,"exact five seconds");int finished=extras;unit.Tick(1);unit.Attack();Check(extras==finished&&!unit.AttackEmpowered,"no post-expiry proc");Check(unit.SkillReady==20,"cooldown retained");
   var other=storm.Snapshot(20);other.skill=skill.Snapshot();Check(!new BattleModel(other,enemy,other.maxHP).Skill(),"Storm cannot cast");
   var fast=d.Snapshot(20);fast.skill=skill.Snapshot();fast.attackCooldown=.01f;fast.criticalChance=0;fast.passiveMechanic=DragonPassiveMechanic.None;var rapid=new BattleModel(fast,enemy,fast.maxHP,()=>.9);int rapidBasic=0,rapidExtra=0;rapid.Cue+=(cue,n)=>{if(cue==CombatCue.Attack&&n>0)rapidBasic++;if(cue==CombatCue.EmpoweredAttackHit)rapidExtra++;};rapid.Skill();rapid.Tick(.24f);for(int i=0;i<160;i++){rapid.Tick(.025f);rapid.Attack();}Check(rapidBasic==rapidExtra&&rapidExtra>30,"fast attacks exactly once "+rapidExtra);
   double roll=.9;var missEnemy=BattleEnemyStats.Normal();missEnemy.maxHP=999999;missEnemy.interval=100;missEnemy.bossPattern=EnemyBossPattern.SentryParalysis;var miss=new BattleModel(stats,missEnemy,stats.maxHP,()=>roll);miss.Skill();miss.Tick(.25f);roll=0;int missHP=miss.EnemyHP;miss.Attack();Check(miss.EnemyHP==missHP&&miss.EmpoweredHitCount==0,"missed attack no extra damage");miss.CancelAttackEmpower();Check(!miss.AttackEmpowered,"cancel removes empowerment");
   var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var v=c.view;v.frame.Find("Collection screens")?.gameObject.SetActive(false);var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var rect=(RectTransform)canvas.transform;rect.position=Vector3.zero;rect.localScale=Vector3.one;rect.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/Ascension");
   c.BeginBattle(d,stats,enemy,1,false,stats.maxHP,null,20,skill);c.SendMessage("OnApplicationFocus",true);var b=c.CurrentBattle;var fx=v.GetComponent<AscensionVfx>();int hitEvents=0;b.Cue+=(cue,n)=>{if(cue==CombatCue.EmpoweredAttackHit)hitEvents++;};Check(c.RequestSkill(),"visual cast");
   for(int f=0;f<420;f++){b.Tick(1f/60);if(f>22&&f<307&&f%19==0)c.RequestAttack();if(f==110||f==225)Check(c.RequestDodge(f==110?-1:1),"visual dodge");v.StepAnimation(b,1f/60);v.Show(b);if(f%2==0)Capture(v,cam,rt,f);if(f==150)Check(b.AttackEmpowered,"state persists through dodge");}
   Check(fx.HitsShown==hitEvents,"visual hits match actual extra events");Check(fx.Clean&&fx.Dropped==0,"effect completed no overflow");Check(Time.timeScale==1,"global clock preserved");Check(v.GetComponent<LegendaryScreenDimming>().Clean,"full screen dim released");Debug.Log("ASCENSION_VISUAL extras="+hitEvents+" peakQuads="+fx.PeakQuads);
   b.Tick(20);c.RequestSkill();b.Tick(.3f);v.StepAnimation(b,.3f);c.EndBattle();Check(!b.AttackEmpowered&&fx.Clean,"battle exit clears state and VFX");
   c.BeginBattle(d,fast,enemy,1,false,fast.maxHP,null,20,skill);c.RequestSkill();var stress=c.CurrentBattle;int stressEvents=0;stress.Cue+=(cue,n)=>{if(cue==CombatCue.EmpoweredAttackHit)stressEvents++;};for(int i=0;i<320;i++){stress.Tick(.02f);if(stress.AttackEmpowered)c.RequestAttack();v.StepAnimation(stress,.02f);}Check(stressEvents==fx.HitsShown&&fx.Dropped==0,"fast visual events no drops "+stressEvents+" shown="+fx.HitsShown+" dropped="+fx.Dropped);c.EndBattle();
   for(int level=1;level<=10;level+=9){var younger=d.Snapshot(level);younger.skill=skill.Snapshot();c.BeginBattle(d,younger,enemy,1,false,younger.maxHP,null,level,skill);c.RequestSkill();c.CurrentBattle.Tick(.3f);v.StepAnimation(c.CurrentBattle,.3f);Check(c.CurrentBattle.AttackEmpowered&&fx.ActiveQuads>0,"earlier evolution anchors "+level);c.EndBattle();}
   var killer=enemy;killer.damage=9999;killer.interval=.5f;c.BeginBattle(d,stats,killer,1,false,1,null,20,skill);c.RequestSkill();var dead=c.CurrentBattle;for(int i=0;i<120&&dead.Result==BattleResult.Fighting;i++){dead.Tick(.02f);v.StepAnimation(dead,.02f);}Check(dead.Result==BattleResult.Defeat&&!dead.AttackEmpowered&&fx.Clean,"death cleanup");
   cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);
  }
  static void Capture(BattleView v,Camera cam,RenderTexture rt,int f){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var t=new Texture2D(480,850,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,480,850),0,0);t.Apply();File.WriteAllBytes("Validation/Ascension/"+f.ToString("000")+".png",t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);RenderTexture.active=old;}
 }
}
