using System;using System.IO;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.UI;
namespace DragonTower.Editor {
 public static class CatastropheValidation {
  static int wait;public static void Run(){CatastropheSetup.Install();Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.Catastrophe.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetBool("CatastropheCheck",true);EditorApplication.isPlaying=true;}
  [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("CatastropheCheck",false)){wait=0;EditorApplication.update+=After;}};}
  static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("CatastropheCheck",false);try{Test();Debug.Log("CATASTROPHE_VALIDATION_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
  static void Check(bool b,string label){if(!b)throw new Exception("CATASTROPHE_FAIL "+label);Debug.Log("CATASTROPHE_CHECK "+label);}
  static BattleStats Stats(DragonData d,SkillData s,int level=20){var a=d.Snapshot(level);a.skill=s.Snapshot();a.passiveMechanic=DragonPassiveMechanic.None;a.criticalChance=0;return a;}
  static BattleEnemyStats Enemy(){var e=BattleEnemyStats.Normal();e.maxHP=50000;e.interval=100;return e;}
  static void Test(){var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon12.asset");var bolt=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon4.asset");var s=d.signatureSkill;Check(s!=null&&s.CanEquip(d.StableId)&&!s.CanEquip(bolt.StableId),"Storm exclusive signature");var stats=Stats(d,s);var e=Enemy();var run=new TowerRun(stats.maxHP,1,2,d.elementType,ElementType.Wind,d.StableId,d);var built=run.BuildBattleStats(stats);Check(built.skill.useSecondaryElement&&built.skill.secondaryElement==ElementType.Wind,"tower snapshot preserves both elements");
   foreach(ElementType type in Enum.GetValues(typeof(ElementType))){e=Enemy();e.elementType=type;var b=new BattleModel(stats,e,stats.maxHP,()=>.9);int hits=0,sum=0,status=0;b.Feedback+=text=>{if(text.StartsWith("마비!"))status++;};double final=0;b.Cue+=(cue,n)=>{if(b.ResolvingSkillHit){Check(Math.Abs(b.Time-s.hitTimeOffsets[hits])<.0201,"hit time "+hits+" "+type);hits++;sum+=n;if(hits==s.hitCount)final=b.Time;}};Check(b.Skill(),"cast "+type);Check(!b.Skill(),"cooldown rejection");for(int i=0;i<160;i++)b.Tick(.02f);int baseExpected=Math.Max(ElementRules.Damage(s.damage,ElementType.Wind,type),ElementRules.Damage(s.damage,ElementType.Lightning,type));int finalExpected=Math.Max(ElementRules.Damage((int)(s.damage*s.finalHitDamageMultiplier),ElementType.Wind,type),ElementRules.Damage((int)(s.damage*s.finalHitDamageMultiplier),ElementType.Lightning,type));Check(hits==7&&sum==baseExpected*6+finalExpected,"single best matchup without multiplication "+type);Check(status==1&&b.EnemyParalyzed,"one guaranteed final paralysis "+type);b.Tick((float)(final+s.statusDuration-b.Time-.02));Check(b.EnemyParalyzed,"status full duration");b.Tick(.04f);Check(!b.EnemyParalyzed,"status expires");Check(b.SkillReady==s.cooldown,"cooldown data");}
   var wrong=Stats(bolt,s);Check(!new BattleModel(wrong,Enemy(),wrong.maxHP).Skill(),"Bolt cannot cast");
   var doubled=Stats(d,s);doubled.augments=new[]{new BattleAugment{mechanic=AugmentMechanic.DoubleCasting}};var twice=new BattleModel(doubled,Enemy(),doubled.maxHP,()=>.9);int doubleHits=0;twice.Cue+=(cue,n)=>{if(twice.ResolvingSkillHit)doubleHits++;};twice.Skill();twice.Tick(8);Check(doubleHits==14,"existing double casting supported");
   var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var v=c.view;v.frame.Find("Collection screens")?.gameObject.SetActive(false);var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var rect=(RectTransform)canvas.transform;rect.position=Vector3.zero;rect.localScale=Vector3.one;rect.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/Catastrophe");
   c.BeginBattle(d,stats,Enemy(),1,false,stats.maxHP,null,20,s);c.SendMessage("OnApplicationFocus",true);var battle=c.CurrentBattle;var fx=v.GetComponent<CatastropheVfx>();int events=0;battle.Cue+=(cue,n)=>{if(battle.ResolvingSkillHit)events++;};Check(c.RequestSkill(),"visual cast");
   var watch=System.Diagnostics.Stopwatch.StartNew();double maxStep=0,totalStep=0;for(int f=0;f<420;f++){battle.Tick(1f/60);double before=watch.Elapsed.TotalMilliseconds;v.StepAnimation(battle,1f/60);double elapsed=watch.Elapsed.TotalMilliseconds-before;maxStep=Math.Max(maxStep,elapsed);totalStep+=elapsed;v.Show(battle);if(f%2==0)Capture(v,cam,rt,f);}
   Check(events==7&&fx.HitsShown==7,"damage/visual contacts exactly once");Check(fx.Clean&&fx.Dropped==0,"weather restored without mesh overflow");Check(v.GetComponent<LegendaryScreenDimming>().Clean,"full screen dim released");Check(Time.timeScale==1,"global time preserved");Debug.Log("CATASTROPHE_VISUAL peakQuads="+fx.PeakQuads+" averageStepMs="+(totalStep/420)+" maxStepMs="+maxStep+" desktop editor only");
   for(int level=1;level<=20;level+=9){var a=Stats(d,s,level);c.BeginBattle(d,a,Enemy(),1,false,a.maxHP,null,level,s);Check(c.RequestSkill(),"evolution cast "+level);for(int f=0;f<270;f++){c.CurrentBattle.Tick(1f/60);v.StepAnimation(c.CurrentBattle,1f/60);}Check(fx.HitsShown==7&&fx.Dropped==0,"evolution effect "+level);c.EndBattle();Check(fx.Clean,"battle exit cleanup");}
   foreach(float cancel in new[]{.25f,1.35f,2.96f,3.20f}){c.BeginBattle(d,stats,Enemy(),1,false,stats.maxHP,null,20,s);c.RequestSkill();c.CurrentBattle.Tick(cancel);v.StepAnimation(c.CurrentBattle,cancel);c.EndBattle();Check(fx.Clean&&v.GetComponent<LegendaryScreenDimming>().Clean,"cancel cleanup "+cancel);}
   var weak=Enemy();weak.maxHP=1;c.BeginBattle(d,stats,weak,1,false,stats.maxHP,null,20,s);c.RequestSkill();c.CurrentBattle.Tick(1);v.StepAnimation(c.CurrentBattle,1);Check(c.CurrentBattle.Result==BattleResult.Victory&&fx.Clean,"target death cleanup");c.EndBattle();
   var lethal=Enemy();lethal.damage=99999;lethal.interval=.5f;c.BeginBattle(d,stats,lethal,1,false,1,null,20,s);c.RequestSkill();for(int i=0;i<200&&c.CurrentBattle.Result==BattleResult.Fighting;i++){c.CurrentBattle.Tick(.02f);v.StepAnimation(c.CurrentBattle,.02f);}Check(c.CurrentBattle.Result==BattleResult.Defeat&&fx.Clean,"Storm death cleanup");c.EndBattle();
   cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);
  }
  static void Capture(BattleView v,Camera cam,RenderTexture rt,int f){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var t=new Texture2D(480,850,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,480,850),0,0);t.Apply();File.WriteAllBytes("Validation/Catastrophe/"+f.ToString("000")+".png",t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);RenderTexture.active=old;}
 }
}
