using System;using System.IO;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;
namespace DragonTower.Editor {
 public static class CelestialValidation {
 static int wait;static void Check(bool ok,string label){if(!ok)throw new Exception("CELESTIAL_FAIL "+label);Debug.Log("CELESTIAL_CHECK "+label);}
 public static void Run(){CelestialSetup.Install();Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.Celestial.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetBool("CelestialCheck",true);EditorApplication.isPlaying=true;}
 [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("CelestialCheck",false)){wait=0;EditorApplication.update+=After;}};}
 static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("CelestialCheck",false);try{Rules();Visual();Debug.Log("CELESTIAL_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
 static SkillData Data=>AssetDatabase.LoadAssetAtPath<SkillData>(CelestialSetup.SkillPath);
 static BattleStats Stats(int level=20){var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon7.asset");var s=d.Snapshot(level);s.skill=Data.Snapshot();s.passiveMechanic=DragonPassiveMechanic.None;s.criticalChance=0;s.attackDamage=20;s.augments=Array.Empty<BattleAugment>();s.items=Array.Empty<BattleItem>();return s;}
 static BattleEnemyStats Enemy(){var e=BattleEnemyStats.Normal();e.maxHP=200000;e.damage=0;e.interval=100;return e;}
 static void Rules(){var s=Stats();double random=.0999;var b=new BattleModel(s,Enemy(),s.maxHP,()=>random);b.Attack();Check(b.CelestialRolls==0,"ready skill never rolls");b.Tick(.5f);Check(b.Skill(),"successful cast");Check(b.CelestialCooldownActive,"armed immediately on cooldown");b.Tick(1.29f);Check(b.EnemyHP==199980,"no premature main damage");b.Tick(.011f);Check(b.EnemyHP==199620,"one scheduled main hit");b.Attack();Check(b.CelestialRolls==1&&b.CelestialProcs==1,"one original-hit roll below ten percent");int hp=b.EnemyHP;b.Tick(.099f);Check(b.EnemyHP==hp,"mini charges before damage");b.Tick(.0011f);Check(b.CelestialExtraHits==1&&b.EnemyHP==hp-42&&b.CelestialRolls==1,"separate extra damage no recursion");b.Tick(.4f);random=.10;b.Attack();Check(b.CelestialRolls==2&&b.CelestialProcs==1,"exact ten percent boundary fails");b.Tick(.4f);random=0;b.Attack();b.SkillReady=b.Time;b.Tick(.11f);Check(b.CelestialExtraHits==1&&!b.CelestialCooldownActive,"live cooldown reduction cancels pending charge");b.Tick(.4f);b.Attack();Check(b.CelestialRolls==3,"ready again no roll");
 s=Stats();s.augments=new[]{new BattleAugment{mechanic=AugmentMechanic.Spread,primaryValue=50}};b=new BattleModel(s,Enemy(),s.maxHP,()=>0);b.Skill();b.Attack();b.Tick(.11f);Check(b.CelestialRolls==1&&b.CelestialExtraHits==1,"augment extra is not a second roll");typeof(BattleModel).GetField("playerParalyzeUntil",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).SetValue(b,100d);b.Tick(.4f);b.Attack();Check(b.CelestialRolls==1,"missed original attack never rolls");b.CancelCelestial();Check(!b.CelestialCooldownActive,"explicit cancel");
 s=Stats();b=new BattleModel(s,Enemy(),s.maxHP,()=>0);typeof(BattleModel).GetField("playerParalyzeUntil",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).SetValue(b,100d);b.Skill();Check(!b.CelestialCooldownActive,"missed cast does not arm");s=Stats();s.speciesId="chrono";b=new BattleModel(s,Enemy(),s.maxHP,()=>0);b.Skill();b.Attack();Check(b.CelestialRolls==0&&!Data.CanEquip("chrono"),"Dante exclusive");
 s=Stats();b=new BattleModel(s,Enemy(),s.maxHP,()=>0);b.Skill();for(int i=0;i<5;i++){b.Attack();Check(b.CelestialEventPattern==i,"direction pattern "+i);b.Tick(.31f);}Check(b.CelestialExtraHits==5&&b.CelestialRolls==5,"five hits five rolls");b.SkillReady=b.Time+.05;b.Attack();b.Tick(.1f);Check(!b.CelestialCooldownActive,"natural cooldown expiry");
 s=Stats();var lethal=Enemy();lethal.damage=99999;lethal.interval=.025f;b=new BattleModel(s,lethal,1,()=>0);b.Skill();b.Attack();b.Tick(.15f);Check(b.Result==BattleResult.Defeat&&!b.CelestialCooldownActive&&b.CelestialExtraHits==0,"death clears pending extra");
 int successes=0;for(int n=0;n<1000;n++){double roll=n/1000.0;s=Stats();b=new BattleModel(s,Enemy(),s.maxHP,()=>roll);b.Skill();b.Attack();successes+=b.CelestialProcs;}Check(successes==100,"ten percent exhaustive roll grid");foreach(string path in LightBatchSetup.Paths){s=Stats();s.skill=AssetDatabase.LoadAssetAtPath<SkillData>(path).Snapshot();b=new BattleModel(s,Enemy(),s.maxHP,()=>.5);b.Skill();b.Tick(2);Check(b.EnemyHP==200000-s.skill.damage*s.skill.hitCount&&b.CelestialRolls==0,"shared Light preserved "+path);}
 }
 static void Visual(){var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var v=c.view;var screens=v.frame.Find("Collection screens");if(screens!=null)screens.gameObject.SetActive(false);var dragon=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon7.asset");var stats=Stats();c.BeginBattle(dragon,stats,Enemy(),1,false,stats.maxHP,null,20,Data);c.SendMessage("OnApplicationFocus",true);var b=c.CurrentBattle;var rng=new System.Random(14);typeof(BattleModel).GetField("random",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).SetValue(b,(Func<double>)(()=>rng.NextDouble()));var fx=v.GetComponent<CelestialVfx>();
 var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var rect=(RectTransform)canvas.transform;rect.position=Vector3.zero;rect.localScale=Vector3.one;rect.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/Celestial");Check(c.RequestSkill(),"visual main cast");int main=0;b.Cue+=(cue,d)=>{if(cue==CombatCue.Skill||cue==CombatCue.SkillHit)main++;};
 double activeMs=0;long activeAlloc=0;int measured=0;var timer=new System.Diagnostics.Stopwatch();for(int f=0;f<720;f++){b.Tick(1f/30);if(f>95&&f%10==0)c.RequestAttack();if(f==160)c.RequestDodge(1);long mem=GC.GetAllocatedBytesForCurrentThread();timer.Restart();v.StepAnimation(b,1f/30);timer.Stop();if(f>10&&f<78){activeMs+=timer.Elapsed.TotalMilliseconds;activeAlloc+=GC.GetAllocatedBytesForCurrentThread()-mem;measured++;}v.Show(b);Capture(v,cam,rt,f);}
 Debug.Log("CELESTIAL_DESKTOP animation_step_ms="+(activeMs/measured)+" managed_bytes_per_step="+(activeAlloc/measured));Check(main==1&&fx.MainHits==1,"one main impact");Check(fx.MaxBeams>=8,"all eight portals fire simultaneously");Check(b.CelestialProcs>0&&fx.MiniHits==b.CelestialExtraHits,"real ten percent mini cues rendered");Check(!b.CelestialCooldownActive,"video ends after cooldown");Check(fx.Dropped==0,"zero geometry overflow");Check(Time.timeScale==1,"global clock unchanged");Debug.Log("CELESTIAL_VISUAL peak="+fx.Peak+" beams="+fx.MaxBeams+" rolls="+b.CelestialRolls+" procs="+b.CelestialProcs+" hits="+b.CelestialExtraHits);c.EndBattle();Check(fx.Clean&&!b.CelestialCooldownActive,"battle exit cleanup");
 foreach(int level in new[]{1,10}){stats=Stats(level);c.BeginBattle(dragon,stats,Enemy(),1,false,stats.maxHP,null,level,Data);c.RequestSkill();for(int i=0;i<90;i++){c.CurrentBattle.Tick(1f/30);v.StepAnimation(c.CurrentBattle,1f/30);}Check(fx.MainHits==1&&fx.Dropped==0,"earlier evolution casting fallback "+level);c.EndBattle();Check(fx.Clean,"earlier evolution cleanup "+level);}
 cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);}
 static void Capture(BattleView v,Camera cam,RenderTexture rt,int f){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var t=new Texture2D(480,850,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,480,850),0,0);t.Apply();File.WriteAllBytes("Validation/Celestial/"+f.ToString("000")+".png",t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);RenderTexture.active=old;}
 public static void BuildWeb(){CelestialSetup.Install();var report=BuildPipeline.BuildPlayer(new[]{"Assets/Scenes/Battle.unity"},"../Celestial-WebGL",BuildTarget.WebGL,BuildOptions.None);if(report.summary.result!=UnityEditor.Build.Reporting.BuildResult.Succeeded)throw new Exception("Celestial WebGL failed");Debug.Log("CELESTIAL_WEBGL_OK");}
 }
}


