using System;using System.IO;using System.Reflection;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.UI;
namespace DragonTower.Editor {
 public static class CrushingBeamValidation {
  static int wait;public static void Run(){CrushingBeamSetup.Install();Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.Beam.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetBool("BeamCheck",true);EditorApplication.isPlaying=true;}
  [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("BeamCheck",false)){wait=0;EditorApplication.update+=After;}};}
  static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("BeamCheck",false);try{Test();Debug.Log("BEAM_VALIDATION_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
  static void Check(bool yes,string label){if(!yes)throw new Exception("BEAM_FAIL "+label);Debug.Log("BEAM_CHECK "+label);}
  static BattleStats Stats(DragonData d,SkillData s){var st=d.Snapshot(20);st.skill=s.Snapshot();st.maxHP=10000;st.criticalChance=0;st.passiveMechanic=DragonPassiveMechanic.None;return st;}
  static BattleEnemyStats Enemy(float interval=100,int hp=99999){var e=BattleEnemyStats.Normal();e.maxHP=hp;e.damage=100;e.interval=interval;return e;}
  static void To(BattleModel m,double t){while(m.Time<t-1e-7&&m.Result==BattleResult.Fighting)m.Tick((float)Math.Min(.01,t-m.Time));}
  static void Damage(BattleModel m,int value){typeof(BattleModel).GetMethod("DamagePlayer",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(m,new object[]{value,"test"});}
  static void Test(){var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon11.asset");var other=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon3.asset");var s=AssetDatabase.LoadAssetAtPath<SkillData>(CrushingBeamSetup.SkillPath);var stats=Stats(d,s);double start=s.chargeDuration+s.beamIgnitionDelay,end=start+s.beamDuration;Check(d.signatureSkill==s&&d.CanOfferSkill(s)&&!other.CanOfferSkill(s)&&!new BattleModel(Stats(other,s),Enemy()).Skill(),"Titan exclusive; Blendy rejected");
   var m=new BattleModel(stats,Enemy());Check(m.Skill()&&!m.Skill(),"charge starts once");Check(!m.ProtectedSkillActive&&m.Attack()&&m.Dodge(),"attack dodge allowed, no charge immunity");To(m,1);Damage(m,100);Check(m.BeamPhase==ChargedBeamPhase.Failed&&m.PlayerHP==9900&&Math.Abs(m.SkillReady-s.cooldown)<.001,"actual damage fails and retains cooldown");int hp=m.EnemyHP;To(m,12);Check(m.EnemyHP==hp&&!m.ProtectedSkillActive&&!m.Skill(),"failed charge never fires or refunds");
   m=new BattleModel(stats,Enemy());m.Skill();Damage(m,0);Check(m.BeamPhase==ChargedBeamPhase.Charging,"zero damage does not fail");typeof(BattleModel).GetField("shieldHP",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(m,100);typeof(BattleModel).GetField("shieldUntil",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(m,20.0);Damage(m,100);Check(m.PlayerHP==10000&&m.BeamPhase==ChargedBeamPhase.Charging,"fully absorbed damage does not fail");Damage(m,1);Check(m.BeamPhase==ChargedBeamPhase.Failed,"positive post-shield damage fails");
   m=new BattleModel(stats,Enemy(1));m.Skill();To(m,.8);Check(m.Dodge(),"swipe dodge accepted while charging");To(m,1.1);Check(m.PlayerHP==10000&&m.BeamPhase==ChargedBeamPhase.Charging,"successful dodge preserves charge");
   m=new BattleModel(stats,Enemy(5));m.Skill();To(m,5.01);Check(m.BeamPhase==ChargedBeamPhase.Failed,"damage at five-second boundary wins over charge success");
   m=new BattleModel(stats,Enemy());int hits=0,total=0;double first=-1,last=-1;m.Cue+=(cue,damage)=>{if(m.ResolvingSkillHit){hits++;total+=damage;if(first<0)first=m.Time;last=m.Time;}};m.Skill();To(m,4.99);Check(hits==0&&m.BeamPhase==ChargedBeamPhase.Charging,"full five seconds required");To(m,5.01);Check(m.BeamPhase==ChargedBeamPhase.Priming&&!m.ProtectedSkillActive,"success atmosphere has no early immunity");Damage(m,100);Check(m.BeamPhase==ChargedBeamPhase.Priming,"post-success damage cannot retroactively fail charge");To(m,start+.001);Check(m.BeamPhase==ChargedBeamPhase.Beam&&m.ProtectedSkillActive&&hits==1,"first beam hit and immunity start together");Check(!m.Attack()&&!m.Dodge()&&!m.Skill(),"beam channel input lock");int before=m.PlayerHP;Damage(m,100);Check(m.PlayerHP==before,"beam blocks status reflection damage");To(m,end-.001);Check(m.ProtectedSkillActive&&hits==s.hitCount-1,"protected through five-second beam");To(m,end+.001);Check(!m.ProtectedSkillActive&&hits==s.hitCount&&Math.Abs(first-start)<.012&&Math.Abs(last-end)<.012,"final hit exactly at five-second beam end");Check(total==s.damage*(s.hitCount-1)+(int)(s.damage*s.finalHitDamageMultiplier),"damage data drives all hits and final multiplier");Damage(m,100);Check(m.PlayerHP==before-100,"damage restored immediately after beam");To(m,end+.3);Check(m.Attack()&&m.Dodge(),"recovery restores controls");
   foreach(float frame in new[]{1f/30,1f/60,.1f}){m=new BattleModel(stats,Enemy());int count=0;m.Cue+=(cue,damage)=>{if(m.ResolvingSkillHit)count++;};m.Skill();for(int f=0;f<12/frame;f++)m.Tick(frame);Check(count==s.hitCount&&!m.ProtectedSkillActive,"frame-rate independent hits "+frame);}
   m=new BattleModel(stats,Enemy(6));m.Skill();To(m,9);Check(m.PlayerHP==10000,"normal enemy attacks blocked during beam");
   var aug=Stats(d,s);aug.augments=new[]{new BattleAugment{mechanic=AugmentMechanic.IndomitableWill}};m=new BattleModel(aug,Enemy(1));m.Skill();To(m,1.1);Check(m.SkillReady>=s.cooldown&&!m.Skill(),"failure cooldown not refunded by on-hit reset");
   foreach(double at in new[]{1.0,5.1,6.0}){m=new BattleModel(stats,Enemy());m.Skill();To(m,at);int enemyHP=m.EnemyHP;m.CancelChargedBeam();To(m,12);Check(m.EnemyHP==enemyHP&&!m.ProtectedSkillActive&&m.BeamPhase==ChargedBeamPhase.Idle,"cancel phase "+at);}
   m=new BattleModel(stats,Enemy(.5f),1);m.Skill();To(m,2);Check(m.Result==BattleResult.Defeat&&!m.ProtectedSkillActive&&m.BeamPhase==ChargedBeamPhase.Idle,"charge death cleanup");
   var g=AssetDatabase.LoadAssetAtPath<SkillData>(GenesisSetup.SkillPath);m=new BattleModel(Stats(other,g),Enemy());m.Skill();To(m,.4);Check(m.ProtectedSkillActive,"Genesis immunity regression");To(m,2.3);Damage(m,100);Check(m.CompletionDefenseActive&&m.PlayerHP==9950,"Genesis armor regression");
   Visual(d,s,stats);
  }
  static void Visual(DragonData d,SkillData s,BattleStats stats){var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var v=c.view;var screens=v.frame.Find("Collection screens");if(screens!=null)screens.gameObject.SetActive(false);var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var rect=(RectTransform)canvas.transform;rect.position=Vector3.zero;rect.localScale=Vector3.one;rect.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/CrushingBeam");
   for(int stage=0;stage<3;stage++){c.BeginBattle(d,stats,Enemy(),1,false,10000,null,stage==0?1:stage*10,s);c.SendMessage("OnApplicationFocus",true);var b=c.CurrentBattle;var fx=v.GetComponent<CrushingBeamVfx>();int objects=v.frame.GetComponentsInChildren<Transform>(true).Length;int hits=0;b.Cue+=(cue,value)=>{if(b.ResolvingSkillHit){hits++;Check(fx.HitsShown==hits,"same-frame beam impact "+hits);}};Check(c.RequestSkill(),"visual charge accepted");
    for(int f=0;f<380;f++){if(f==30)Check(c.RequestAttack(),"tap attack during charge");if(f==75)Check(c.RequestDodge(1),"swipe during charge");b.Tick(1f/30);v.StepAnimation(b,1f/30);v.Show(b);if(stage==2||f==90||f==151||f==170||f==305)Capture(v,cam,rt,"titan-"+stage+"-"+f.ToString("000"));}
    Check(hits==s.hitCount&&fx.Clean&&fx.DroppedLayers==0,"success sequence clean and pool within capacity");Check(objects==v.frame.GetComponentsInChildren<Transform>(true).Length,"no per-cast objects");Check(v.skillButton.transform.Find("Equipped skill name").GetComponent<Text>().text=="분쇄광선","HUD data name");Debug.Log("BEAM_FORM_OK "+stage+" peak="+fx.PeakImages+" origin="+fx.LastOrigin);c.EndBattle();}
   c.BeginBattle(d,stats,Enemy(1),1,false,10000,null,20,s);c.RequestSkill();for(int f=0;f<210;f++){c.CurrentBattle.Tick(1f/30);v.StepAnimation(c.CurrentBattle,1f/30);v.Show(c.CurrentBattle);if(f<75)Capture(v,cam,rt,"failed-"+f.ToString("000"));}Check(c.CurrentBattle.BeamPhase==ChargedBeamPhase.Failed&&v.GetComponent<CrushingBeamVfx>().HitsShown==0&&v.GetComponent<CrushingBeamVfx>().Clean,"failed visual never fires");c.EndBattle();
   foreach(float at in new[]{1f,5.1f,6f,10.3f}){c.BeginBattle(d,stats,Enemy(),1,false,10000,null,20,s);c.RequestSkill();var b=c.CurrentBattle;b.Tick(at);v.StepAnimation(b,at);c.EndBattle();Check(v.GetComponent<CrushingBeamVfx>().Clean&&!b.ProtectedSkillActive,"exit restores all visuals "+at);}
   c.BeginBattle(d,stats,Enemy(100,1),1,false,10000,null,20,s);c.RequestSkill();for(int i=0;i<380;i++){c.CurrentBattle.Tick(1f/30);v.StepAnimation(c.CurrentBattle,1f/30);}Check(v.GetComponent<CrushingBeamVfx>().Clean&&!c.CurrentBattle.ProtectedSkillActive,"early enemy death stops beam");c.EndBattle();cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);
  }
  static void Capture(BattleView v,Camera cam,RenderTexture rt,string name){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(480,850,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,480,850),0,0);tex.Apply();File.WriteAllBytes("Validation/CrushingBeam/"+name+".png",tex.EncodeToPNG());UnityEngine.Object.DestroyImmediate(tex);RenderTexture.active=old;}
 }
}
