using System;using System.IO;using System.Linq;using UnityEditor;using UnityEngine;using UnityEngine.UI;
namespace DragonTower.Editor {
 public static class DarkStyleValidation {
  static int wait;public static void Run(){DarkStyleSetup.Install();Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.DarkStyle.Validation");SessionState.SetBool("DarkStyleCheck",true);EditorApplication.isPlaying=true;}
  [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("DarkStyleCheck",false)){wait=0;EditorApplication.update+=After;}};}
  static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("DarkStyleCheck",false);try{Test();Debug.Log("DARK_STYLE_VALIDATION_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
  static void Check(bool ok,string label){if(!ok)throw new Exception("DARK_STYLE_FAIL "+label);Debug.Log("DARK_CHECK "+label);}
  static void Test(){var p=UnityEngine.Object.FindFirstObjectByType<DarkStylePreview>();p.autoplay=false;p.Initialize();var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();var v=c.view;var fx=p.Effect;var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var r=(RectTransform)canvas.transform;r.position=Vector3.zero;r.localScale=Vector3.one;r.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/DarkStyle");
   for(int d=0;d<2;d++)for(int s=0;s<5;s++){p.dragonIndex=d;p.evolution=2;p.sample=(DarkSample)s;p.Restart();var b=p.Model;int hp=b.EnemyHP,playerHP=b.PlayerHP;Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;var hud=v.frame.anchoredPosition;bool actorsStable=true;int count=v.frame.GetComponentsInChildren<Transform>(true).Length;for(int f=0;f<120;f++){b.Tick(1f/30);v.StepAnimation(b,1f/30);v.Show(b);var enemyBefore=v.enemyArt.rectTransform.anchoredPosition;var playerBefore=v.playerArt.rectTransform.anchoredPosition;fx.Step(b,1f/30);actorsStable &= v.enemyArt.rectTransform.anchoredPosition==enemyBefore && v.playerArt.rectTransform.anchoredPosition==playerBefore && v.frame.anchoredPosition==hud;Capture(v,cam,rt,(d==0?"nova":"venom")+"-"+s+"-"+f.ToString("000"));}Check(b.PlayerHP==playerHP&&(s==4?b.EnemyPoisoned&&b.EnemyHP<hp:b.EnemyHP==hp),"visual only / original poison "+d+"/"+s);Check(b.SkillReady==0&&Time.timeScale==1,"cooldown and time preserved");Check(fx.Clean&&fx.DroppedLayers==0,"cleanup and pool budget");Check(actorsStable,"HUD and actor unaffected");Check(count==v.frame.GetComponentsInChildren<Transform>(true).Length,"pool stable");Debug.Log("DARK_SAMPLE_OK "+d+"/"+s+" peak="+fx.PeakQuads);}
   Check(v.frame.GetComponentsInChildren<LightningMeshLayer>(true).All(i=>!i.raycastTarget),"no input interception");p.Restart();for(int i=0;i<3;i++)Cycle(fx,p.Model);var watch=new System.Diagnostics.Stopwatch();watch.Start();long before=GC.GetAllocatedBytesForCurrentThread();for(int i=0;i<5;i++)Cycle(fx,p.Model);long allocated=GC.GetAllocatedBytesForCurrentThread()-before;watch.Stop();Debug.Log("DARK_UPDATE_ALLOC "+allocated+" CPU average ms="+watch.Elapsed.TotalMilliseconds/1000);Check(allocated==0,"warmed renderer no allocation");p.Restart();p.Step(.25f);fx.enabled=false;Check(fx.Clean,"disable cleans offsets");fx.enabled=true;p.Restart();p.Step(.3f);c.EndBattle();fx.Step(null,0);Check(fx.Clean,"battle exit cleans");cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);}
  static void Cycle(DarkStylePrototype fx,BattleModel model){fx.Play(DarkSample.HeavyDarkImpact,new Vector2(0,-200),new Vector2(0,75));for(int i=0;i<200;i++)fx.Step(model,1f/60);fx.Clear();}
  static void Capture(BattleView v,Camera cam,RenderTexture rt,string name){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(480,850,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,480,850),0,0);tex.Apply();File.WriteAllBytes("Validation/DarkStyle/"+name+".png",tex.EncodeToPNG());UnityEngine.Object.DestroyImmediate(tex);RenderTexture.active=old;}
  public static void BuildWeb(){var report=BuildPipeline.BuildPlayer(new[]{DarkStyleSetup.ScenePath},"../DarkStyle-WebGL",BuildTarget.WebGL,BuildOptions.None);if(report.summary.result!=UnityEditor.Build.Reporting.BuildResult.Succeeded)throw new Exception("Dark build failed");Debug.Log("DARK_STYLE_WEBGL_OK");}
 }
}

