using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;
namespace DragonTower.Editor {
 public static class EarthStyleSetup {
  public const string Folder="Assets/Art/EarthStylePrototype",StylePath=Folder+"/EarthStyle.asset",ScenePath="Assets/Scenes/Prototypes/EarthStylePreview.unity";
  [MenuItem("Dragon Tower/Earth Style/Install isolated prototypes")]
  public static void Install(){Directory.CreateDirectory(Folder);AssetDatabase.Refresh();var style=AssetDatabase.LoadAssetAtPath<EarthVfxStyle>(StylePath);if(style==null){style=ScriptableObject.CreateInstance<EarthVfxStyle>();AssetDatabase.CreateAsset(style,StylePath);}const int tile=128,w=1024,h=1280;var tex=new Texture2D(w,h,TextureFormat.RGBA32,false);var px=new Color[w*h];for(int m=0;m<10;m++)for(int f=0;f<8;f++)for(int y=0;y<tile;y++)for(int x=0;x<tile;x++)px[(m*tile+y)*w+f*tile+x]=Pixel(m,f,x,y,style);tex.SetPixels(px);tex.Apply();File.WriteAllBytes(Folder+"/EarthAtlas.png",tex.EncodeToPNG());UnityEngine.Object.DestroyImmediate(tex);AssetDatabase.Refresh();var im=(TextureImporter)AssetImporter.GetAtPath(Folder+"/EarthAtlas.png");im.textureType=TextureImporterType.Sprite;im.spriteImportMode=SpriteImportMode.Multiple;im.filterMode=FilterMode.Point;im.mipmapEnabled=false;im.alphaIsTransparency=true;im.textureCompression=TextureImporterCompression.Uncompressed;im.npotScale=TextureImporterNPOTScale.None;im.spritePixelsPerUnit=100;im.maxTextureSize=2048;im.isReadable=false;var slices=new SpriteMetaData[80];for(int m=0;m<10;m++)for(int f=0;f<8;f++)slices[m*8+f]=new SpriteMetaData{name=((EarthModule)m)+"_"+f,rect=new Rect(f*tile,m*tile,tile,tile),pivot=Vector2.one*.5f,alignment=0};
 #pragma warning disable 618
 im.spritesheet=slices;
 #pragma warning restore 618
 im.SaveAndReimport();var sprites=AssetDatabase.LoadAllAssetsAtPath(Folder+"/EarthAtlas.png").OfType<Sprite>().ToArray();style.frames=slices.Select(s=>sprites.First(p=>p.name==s.name)).ToArray();EditorUtility.SetDirty(style);AssetDatabase.SaveAssets();var go=new GameObject("Earth art prototype - no damage");go.AddComponent<EarthStylePrototype>().style=style;PrefabUtility.SaveAsPrefabAsset(go,"Assets/Prefabs/Prototypes/EarthStylePrototype.prefab");UnityEngine.Object.DestroyImmediate(go);EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");var driver=new GameObject("Earth style review only").AddComponent<EarthStylePreview>();driver.style=style;driver.dragons=new[]{AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon3.asset"),AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon11.asset")};EditorSceneManager.SaveScene(EditorSceneManager.GetActiveScene(),ScenePath);AssetDatabase.SaveAssets();Debug.Log("EARTH_STYLE_INSTALLED");}
  static Color Alpha(Color c,float a){c.a=Mathf.Clamp01(a);return c;}
  // Orthographic ray intersection with an irregular beveled solid: changing visible faces, not a flat rotated polygon.
  static readonly Vector3[] planes={new Vector3(1,0,0),new Vector3(-1,0,0),new Vector3(0,1,0),new Vector3(0,-1,0),new Vector3(0,0,1),new Vector3(0,0,-1),new Vector3(1,1,0).normalized,new Vector3(-1,1,0).normalized,new Vector3(1,-1,0).normalized,new Vector3(-1,-1,0).normalized,new Vector3(1,0,1).normalized,new Vector3(-1,0,1).normalized,new Vector3(0,1,1).normalized,new Vector3(0,-1,1).normalized,new Vector3(1,1,1).normalized,new Vector3(-1,1,1).normalized,new Vector3(1,0,-1).normalized,new Vector3(-1,0,-1).normalized,new Vector3(0,1,-1).normalized};
  static Color Rock(float x,float y,int frame,EarthVfxStyle s){var rotation=Quaternion.Euler(14,frame*45,13);var o=new Vector3(x,y,3);var d=Vector3.back;float enter=0,exit=10;Vector3 normal=Vector3.forward;for(int i=0;i<planes.Length;i++){var n=rotation*planes[i];float bound=(i<6?.70f:.59f)+Mathf.Sin(i*7.13f)*.12f;float numerator=bound-Vector3.Dot(n,o),denom=Vector3.Dot(n,d);if(Mathf.Abs(denom)<.0001f){if(numerator<0)return Color.clear;continue;}float t=numerator/denom;if(denom<0){if(t>enter){enter=t;normal=n;}}else exit=Mathf.Min(exit,t);if(enter>exit)return Color.clear;}var p=o+d*enter;float light=Vector3.Dot(normal,new Vector3(-.45f,.72f,.65f).normalized);Color c=light<-.15f?s.shadow:light<.18f?s.dark:light<.48f?s.earth:light<.78f?s.warm:s.sand;float second=10;for(int i=0;i<planes.Length;i++){var n=rotation*planes[i];if(Vector3.Dot(n,normal)>.99f)continue;second=Mathf.Min(second,(i<6?.70f:.59f)+Mathf.Sin(i*7.13f)*.12f-Vector3.Dot(n,p));}if(second<.022f)c=light>.45f?s.edge:s.shadow;var local=Quaternion.Inverse(rotation)*p;float seam=Mathf.Abs(local.y+.27f*local.x+.07f*Mathf.Sin(local.x*12));if(seam<.015f)c=Color.Lerp(c,s.shadow,.55f);return c;}
  static Color Pixel(int m,int f,int x,int y,EarthVfxStyle s){float px=(x-63.5f)/60,py=(y-63.5f)/60,k=f/7f,r=Mathf.Sqrt(px*px+py*py),a=Mathf.Atan2(py,px);if(m==0)return Rock(px,py,f,s);if(m==1)return Rock(px*.95f,py*.97f+px*.1f,f,s);
   if(m==2){float dist=5;float branch=5;for(int i=0;i<7;i++){float angle=i*.8976f+.11f,along=px*Mathf.Cos(angle)+py*Mathf.Sin(angle),across=-px*Mathf.Sin(angle)+py*Mathf.Cos(angle);float path=.025f*Mathf.Sin(along*16+i)+.035f*Mathf.Sin(along*9-i);if(along>0&&along<.14f+k*.83f)dist=Mathf.Min(dist,Mathf.Abs(across-path));if(k>.36f&&along>.25f&&along<k*.9f){float fork=path+(along-.25f)*.55f;branch=Mathf.Min(branch,Mathf.Abs(across-fork));}}if(r>1)return Color.clear;float width=.025f+(1-r)*.026f;if(dist<width)return s.shadow;if(dist<width+.015f)return py>.05f?s.sand:s.earth;if(branch<.017f)return s.dark;if(k<.7f&&dist<width+.028f&&r<.6f)return Alpha(s.amber,.7f);return Color.clear;}
   if(m>=3&&m<=5){float nearest=9;for(int i=0;i<6;i++){float cx=Mathf.Sin(i*2.4f)*.43f,cy=Mathf.Cos(i*2.4f)*.25f;float radius=.26f+i%3*.055f+k*.09f;nearest=Mathf.Min(nearest,(new Vector2(px-cx,py-cy)).magnitude/radius);}if(nearest>1)return Color.clear;float fold=py+.055f*Mathf.Sin(px*15+f*.6f);Color c=nearest>.88f?s.dark:fold>.16f?s.sand:fold>-.11f?s.warm:s.earth;if(m==4)c=Color.Lerp(c,s.shadow,.22f);return Alpha(c,1-k*.48f);}
   if(m==6){float edge=(.2f+k*.69f)*(1+.25f*Mathf.Sin(a*7)+.1f*Mathf.Sin(a*13));if(r>edge||r<k*.47f)return Color.clear;return r>edge*.86f?s.earth:r>edge*.54f?s.sand:s.edge;}
   if(m==7){float radius=.15f+k*.76f;float jag=.017f*Mathf.Sin(a*17);if(Mathf.Abs(r-radius+jag)>.045f||Mathf.Sin(a*11+f*.3f)<-.2f)return Color.clear;return Alpha(s.sand,.5f);}
   if(m==8){if(Mathf.Abs(px)+Mathf.Abs(py)*1.25f>.36f)return Color.clear;return px+py>.0f?s.sand:s.dark;}
   if(m==9){if(r>.86f)return Color.clear;return Alpha(s.shadow,(1-r/.86f)*.72f);}
   return Color.clear;
  }
 }
}
