using System.IO;using System.Linq;using UnityEngine;using UnityEditor;
namespace DragonTower.Editor {
 public static class EclipseSetup {
  public const string SkillPath="Assets/Data/Skills/skill_eclipse.asset",Folder="Assets/Art/Eclipse";
  public static void Install(){Directory.CreateDirectory(Folder);Icon();AssetDatabase.Refresh();var imp=(TextureImporter)AssetImporter.GetAtPath(Folder+"/Icon.png");imp.textureType=TextureImporterType.Sprite;imp.spriteImportMode=SpriteImportMode.Single;imp.filterMode=FilterMode.Point;imp.mipmapEnabled=false;imp.textureCompression=TextureImporterCompression.Uncompressed;imp.SaveAndReimport();var s=AssetDatabase.LoadAssetAtPath<SkillData>(SkillPath);if(s==null){s=ScriptableObject.CreateInstance<SkillData>();s.damage=600;s.cooldown=22;s.initialHitDelay=3.05f;s.castLockDuration=4.25f;s.cooldownRecastMaxHpPercent=10;AssetDatabase.CreateAsset(s,SkillPath);}s.skillId="skill_eclipse";s.displayName="이클립스";s.description="노바 전용 · 블랙홀의 중력으로 공간을 붕괴시킵니다. 쿨타임 중 재사용 시 최대 HP 10% 소비(최소 1 HP 필요). 시전 중 재사용 불가.";s.exclusiveDragonId="nova";s.elementType=ElementType.Dark;s.effectKind=SkillEffectKind.Dark;s.rarity=ContentRarity.Legendary;s.eclipsePresentation=true;s.hitCount=1;s.icon=AssetDatabase.LoadAssetAtPath<Sprite>(Folder+"/Icon.png");EditorUtility.SetDirty(s);var nova=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon6.asset");nova.signatureSkill=s;EditorUtility.SetDirty(nova);var db=AssetDatabase.LoadAssetAtPath<ContentDatabase>("Assets/Resources/ContentDatabase.asset");if(!db.skills.Contains(s)){db.skills=db.skills.Concat(new[]{s}).ToArray();EditorUtility.SetDirty(db);}AssetDatabase.SaveAssets();Debug.Log("ECLIPSE_INSTALLED");}
  // Same geometric palette as runtime disk, rendered at the existing pixel icon resolution.
  static void Icon(){const int n=128;var tex=new Texture2D(n,n,TextureFormat.RGBA32,false);var colors=new Color[n*n];for(int y=0;y<n;y++)for(int x=0;x<n;x++){float px=(x-63.5f)/58,py=(y-63.5f)/58,r=Mathf.Sqrt(px*px+py*py);var c=new Color(.025f,.012f,.06f,1);if(r>.99f)c=Color.clear;else{float tilt=py-px*.28f;float disk=Mathf.Sqrt(px*px+tilt*tilt*10);float theta=Mathf.Atan2(tilt*3,px);if(disk>.4f&&disk<1)c=Color.Lerp(new Color(.2f,.04f,.5f),new Color(.79f,.4f,1),Mathf.Repeat(theta*2+disk*6,1));if(Mathf.Abs(disk-.89f)<.025f)c=new Color(1,.7f,.28f);if(r<.36f&&tilt>-.1f)c=new Color(.005f,.003f,.015f);if(Mathf.Abs(r-.375f)<.02f&&tilt>-.08f)c=new Color(.64f,.28f,.98f);if((x*17+y*31)%223==0&&r>.52f)c=new Color(.93f,.77f,1);if(r>.94f)c=new Color(.40f,.16f,.67f);}colors[y*n+x]=c;}tex.SetPixels(colors);tex.Apply();File.WriteAllBytes(Folder+"/Icon.png",tex.EncodeToPNG());Object.DestroyImmediate(tex);}
 }
}
