using System;using System.IO;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.UI;
namespace DragonTower.Editor {
 public static class EclipseValidation {
  static int wait;static void Check(bool b,string label){if(!b)throw new Exception("ECLIPSE_FAIL "+label);Debug.Log("ECLIPSE_CHECK "+label);}
  public static void Run(){EclipseSetup.Install();Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.Eclipse.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetBool("EclipseCheck",true);EditorApplication.isPlaying=true;}
  [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("EclipseCheck",false)){wait=0;EditorApplication.update+=After;}};}
  static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("EclipseCheck",false);try{Rules();Visual();Debug.Log("ECLIPSE_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
  static SkillData Data=>AssetDatabase.LoadAssetAtPath<SkillData>(EclipseSetup.SkillPath);
  static BattleStats Stats(){var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon6.asset");var s=d.Snapshot(20);s.maxHP=1000;s.skill=Data.Snapshot();s.criticalChance=0;s.augments=Array.Empty<BattleAugment>();s.items=Array.Empty<BattleItem>();return s;}
  static BattleEnemyStats Enemy(){var e=BattleEnemyStats.Normal();e.maxHP=20000;e.damage=0;e.interval=100;return e;}
  static void Rules(){var s=Stats();var b=new BattleModel(s,Enemy(),1000,()=>.99);int hits=0;b.Cue+=(cue,n)=>{if(b.ResolvingSkillHit)hits++;};Check(b.Skill()&&b.PlayerHP==1000,"normal cast no HP cost");Check(!b.ProtectedSkillActive,"cinematic lock is not invincibility");for(int i=0;i<12;i++)Check(!b.Skill(),"duplicate rejected");Check(b.PlayerHP==1000,"rejections no cost");b.Tick(s.skill.initialHitDelay-.001f);Check(hits==0,"no premature damage");b.Tick(.002f);Check(hits==1&&b.EnemyHP==19400,"single final damage");b.SkillReady=0;Check(!b.Skill(),"lock independent of cooldown");b.SkillReady=22;b.Tick(1.3f);Check(b.Skill()&&b.PlayerHP==900,"cooldown reuse exact 10 percent max HP");Check(!b.Skill()&&b.PlayerHP==900,"reuse spam charged once");b.CancelProtectedSkill();int hp=b.EnemyHP;b.Tick(5);Check(b.EnemyHP==hp&&!b.SignatureCastLocked,"cancel clears pending damage and lock");
   s=Stats();s.maxHP=2000;b=new BattleModel(s,Enemy(),601,()=>.99);b.SkillReady=20;Check(b.Skill()&&b.PlayerHP==401,"2000 max HP costs 200 independent of current HP");b.CancelProtectedSkill();
   s=Stats();b=new BattleModel(s,Enemy(),100,()=>.99);b.SkillReady=20;Check(!b.CanUseSkill&&!b.Skill()&&b.PlayerHP==100&&b.SkillReady==20,"insufficient HP rejected without mutation");b=new BattleModel(s,Enemy(),101,()=>.99);b.SkillReady=20;Check(b.Skill()&&b.PlayerHP==1,"exact one HP boundary");
   for(int stage=0;stage<3;stage++){s=Stats();s.passiveStage=stage;s.skill=AssetDatabase.LoadAssetAtPath<SkillData>("Assets/Data/Skill6.asset").Snapshot();b=new BattleModel(s,Enemy(),1000,()=>.99);b.SkillReady=20;Check(b.Skill()&&b.PlayerHP==1000-(100-stage*20),"legacy passive stage cost "+stage);}
   s=Stats();s.speciesId="venom";b=new BattleModel(s,Enemy(),1000);Check(!b.Skill(),"non-owner denied");var nova=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon6.asset");var venom=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon14.asset");Check(nova.signatureSkill==Data&&nova.CanOfferSkill(Data)&&!venom.CanOfferSkill(Data),"signature ownership");
   s=Stats();var e=Enemy();e.damage=2000;e.interval=.2f;b=new BattleModel(s,e,1000,()=>.99);b.Skill();b.Tick(1);Check(b.Result==BattleResult.Defeat&&!b.SignatureCastLocked,"death unlocks no invulnerability");
  }
  static void Visual(){var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var v=c.view;var screens=v.frame.Find("Collection screens");if(screens!=null)screens.gameObject.SetActive(false);var dragon=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon6.asset");var stats=Stats();c.BeginBattle(dragon,stats,Enemy(),1,false,1000,null,20,Data);c.SendMessage("OnApplicationFocus",true);var b=c.CurrentBattle;var fx=v.GetComponent<EclipseVfx>();
   var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var rect=(RectTransform)canvas.transform;rect.position=Vector3.zero;rect.localScale=Vector3.one;rect.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/Eclipse");
   Check(c.RequestSkill(),"visual cast");int objects=v.frame.GetComponentsInChildren<Transform>(true).Length;
   for(int f=0;f<330;f++){b.Tick(1f/30);v.StepAnimation(b,1f/30);v.Show(b);if(f==145)Check(c.RequestSkill()&&b.PlayerHP==900,"visual repeated overcast");Capture(v,cam,rt,f);}
   Check(fx.Clean&&!b.SignatureCastLocked,"normal visual expiry");Check(objects==v.frame.GetComponentsInChildren<Transform>(true).Length&&fx.Dropped==0,"stable pool no overflow");Check(v.GetComponent<LegendaryScreenDimming>().Clean,"full screen grade restored");Check(Time.timeScale==1,"global clock unchanged");Debug.Log("ECLIPSE_VISUAL peak="+fx.Peak+" hp="+b.PlayerHP);
   Check(c.RequestSkill(),"cancel test starts");v.StepAnimation(b,.35f);fx.enabled=false;Check(fx.Clean&&!b.SignatureCastLocked,"component disable clears state and background");fx.enabled=true;c.RequestSkill();v.StepAnimation(b,.3f);c.EndBattle();Check(fx.Clean&&!b.SignatureCastLocked,"battle end cleanup");cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);
  }
  static void Capture(BattleView v,Camera cam,RenderTexture rt,int f){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var t=new Texture2D(480,850,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,480,850),0,0);t.Apply();File.WriteAllBytes("Validation/Eclipse/"+f.ToString("000")+".png",t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);RenderTexture.active=old;}
 }
}

