using System;using System.Linq;using UnityEngine;using UnityEditor;
namespace DragonTower.Editor {
 public static class FloorProgressionValidation {
  static int checks;static void Check(bool value,string name){if(!value)throw new Exception("FLOOR_FAIL "+name);checks++;}
  static TowerRun New(ContentDatabase db,int roll){var d=db.dragons[0];var r=new TowerRun(d.maxHP,roll,1,d.elementType,d.alternateSkillElement,d.StableId,d);r.AttachInstance("test");r.BeginFloorRoom(0,4321);return r;}
  public static void Run(){try{Verify();Debug.Log("FLOOR_TEST_OK checks="+checks);EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
  public static void Verify(){var db=ContentDatabase.Load();var c=FloorProgressionConfig.Load();Check(c.experienceWeights.Sum()==100&&c.experienceMultipliers.Length==5,"config arrays");
   var a=New(db,60);a.AddAugment(db.augments.First(x=>x.grade==AugmentGrade.Common&&x.requirements==AugmentRequirement.None),false);Check(a.CompleteRoomEvent(c,39,99)&&a.AdditionalBattle&&a.Experience==15,"augment battle 40 and room EXP");Check(!a.CompleteRoomEvent(c,99,0)&&a.AdditionalBattle&&a.Experience==15,"one decision and reward");a.BeginFloorCombat(c,0);Check(a.BattleExperiencePercent==150,"no XP reroll");Check(a.CompleteFloorCombat(50,c)&&a.Level==2&&a.Experience==65,"additional battle EXP separate");Check(!a.CompleteFloorCombat(50,c)&&a.MonstersDefeated==1,"no duplicate victory");a.CompleteBattleRewards();a.MoveToNextFloor(0,1);Check(a.Floor==2&&a.Phase==FloorPhase.Choosing,"advance after battle");
   var g=New(db,85);g.AddGold(50);g.CompleteRoomEvent(c,50,0);Check(!g.AdditionalBattle&&g.Gold==50&&g.Experience==10,"gold no battle");
   var copy=TowerRun.Restore(JsonUtility.FromJson<TowerRunSave>(JsonUtility.ToJson(g.Capture())),db);Check(copy.RewardClaimed&&!copy.CompleteRoomEvent(c,0,99)&&copy.Gold==50&&copy.Experience==10,"save no duplicate or reroll");
   Check(copy.ExperiencePresentationPending&&copy.PreviousExperienceLevel==1&&copy.PreviousExperience==0,"unread EXP presentation survives save");copy.AcknowledgeExperience();var acknowledged=TowerRun.Restore(JsonUtility.FromJson<TowerRunSave>(JsonUtility.ToJson(copy.Capture())),db);Check(!acknowledged.ExperiencePresentationPending&&acknowledged.Experience==10,"EXP acknowledgment does not award again");
   var m=New(db,0);m.BeginFloorCombat(c,15);Check(!m.AdditionalBattle&&m.BattleExperiencePercent==75,"mandatory monster");m.CompleteFloorCombat(50,c);m.CompleteBattleRewards();m.MoveToNextFloor(0,1);Check(m.Phase==FloorPhase.Choosing,"monster no extra");
   for(int floor=2;floor<=80;floor++){m.BeginFloorRoom(0,5);m.BeginFloorCombat(c,40);m.CompleteFloorCombat(50,c);while(m.PendingLevelAugments>0)m.ConsumeEmptyAugmentReward(true);if(m.PendingEvolutionStage>0)m.ConsumeEvolution();m.CompleteBattleRewards();if(floor%10==0)Check(m.Room==TowerRoomKind.Boss,"boss "+floor);if(floor<80)m.MoveToNextFloor(0,1);}
   var partial=New(db,60);partial.RecordBattleVictory(50,90);partial.CompleteRoomEvent(c,99,0);Check(partial.Level==2&&partial.Experience==5,"room EXP level up");
   int[] count=new int[5];for(int i=0;i<100;i++)count[Array.IndexOf(c.experienceMultipliers,c.PickExperienceMultiplier(i))]++;Check(count.SequenceEqual(new[]{15,25,35,20,5}),"EXP weights exact");
   foreach(var kind in new[]{TowerRoomKind.Item,TowerRoomKind.Recovery,TowerRoomKind.Nest,TowerRoomKind.Shop})Check(c.BattleChance(kind)==35,"event chance "+kind);
   // Reconstruct all timer/counter/legendary states from the same original inputs.
   foreach(var d in db.dragons){var r=new TowerRun(d.maxHP,0,1,d.elementType,d.alternateSkillElement,d.StableId,d);r.AttachInstance("test");while(r.Level<20){r.RecordBattleVictory(r.MaxHP);if(r.PendingEvolutionStage>0)r.ConsumeEvolution();}while(r.PendingLevelAugments>0)r.ConsumeEmptyAugmentReward(true);if(d.signatureSkill!=null)r.ReplaceSkill(d.signatureSkill,false);r.BeginFloorRoom(0,9);r.BeginFloorCombat(c,40);var enemy=new BattleEnemyStats{maxHP=10000000,damage=1,interval=3};var tape=new BattleResumeData{initialRunJson=JsonUtility.ToJson(r.Capture(false)),enemy=enemy,seed=72};var random=new System.Random(72);var model=new BattleModel(r.BuildBattleStats(d.Snapshot(r.Level)),enemy,r.CurrentHP,()=>random.NextDouble());
    for(int i=0;i<120;i++){if(i==0&&model.Skill())tape.inputs.Add(new BattleInputRecord{action=2});if(i%8==0&&model.Attack())tape.inputs.Add(new BattleInputRecord{action=1});if(i%30==0&&model.Dodge())tape.inputs.Add(new BattleInputRecord{action=3});model.Tick(.05f);tape.inputs.Add(new BattleInputRecord{action=0,delta=.05f});}
    r.BattleResume=tape;r.SyncHealth(model.PlayerHP,model.PassiveConsumed);var restored=TowerRun.Restore(JsonUtility.FromJson<TowerRunSave>(JsonUtility.ToJson(r.Capture())),db);var replay=BattleReplay.Restore(restored.BattleResume,db,"test");Check(replay.PlayerHP==model.PlayerHP&&replay.EnemyHP==model.EnemyHP&&Math.Abs(replay.Time-model.Time)<.00001&&replay.SkillReady==model.SkillReady&&replay.AttackReady==model.AttackReady,"battle resume "+d.StableId);
   }
   const string key="DragonTower.Test.FloorRun";PlayerPrefs.DeleteKey(key+".A");PlayerPrefs.DeleteKey(key+".B");var session=new CollectionSession(new ProfileStore(key),db.dragons);session.Hatch(0);g.AttachInstance(session.Profile.selectedInstanceId);session.SaveRun(g);var loaded=new CollectionSession(new ProfileStore(key),db.dragons);Check(loaded.Profile.activeRun.Gold==50&&loaded.Profile.activeRun.RewardClaimed,"profile resume");g.End();session.FinishRun(g);loaded=new CollectionSession(new ProfileStore(key),db.dragons);Check(!loaded.HasSavedRun&&loaded.Profile.lastRun.floor==1,"death ends run");
  }
 }
}
