using System;using System.IO;using System.Reflection;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.UI;
namespace DragonTower.Editor {
 public static class GenesisValidation {
  static int wait;
  public static void Run(){GenesisSetup.Install();Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.Genesis.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetBool("GenesisCheck",true);EditorApplication.isPlaying=true;}
  [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("GenesisCheck",false)){wait=0;EditorApplication.update+=After;}};}
  static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("GenesisCheck",false);try{Test();Debug.Log("GENESIS_VALIDATION_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
  static void Check(bool b,string m){if(!b)throw new Exception("GENESIS_FAIL "+m);Debug.Log("GENESIS_CHECK "+m);}
  static BattleStats Stats(DragonData d,SkillData s){var st=d.Snapshot(20);st.skill=s.Snapshot();st.maxHP=10000;st.criticalChance=0;st.passiveMechanic=DragonPassiveMechanic.None;return st;}
  static BattleEnemyStats Enemy(int hp=99999,float interval=100){var e=BattleEnemyStats.Normal();e.maxHP=hp;e.interval=interval;e.damage=100;return e;}
  static void To(BattleModel m,double t){while(m.Time<t-.0000001&&m.Result==BattleResult.Fighting)m.Tick((float)Math.Min(.01,t-m.Time));}
  static void StatusDamage(BattleModel m,int damage){typeof(BattleModel).GetMethod("DamagePlayer",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(m,new object[]{damage,"test"});}
  static void Test(){var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon3.asset");var titan=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon11.asset");var s=AssetDatabase.LoadAssetAtPath<SkillData>(GenesisSetup.SkillPath);var stats=Stats(d,s);
   Check(d.signatureSkill==s&&d.CanOfferSkill(s)&&!titan.CanOfferSkill(s)&&!new BattleModel(Stats(titan,s),Enemy()).Skill(),"Blendy exclusive, Titan blocked");
   var m=new BattleModel(stats,Enemy(),10000);int hits=0;m.Cue+=(cue,damage)=>{if(m.ResolvingSkillHit){hits++;Check(Math.Abs(m.Time-s.initialHitDelay)<.012,"one synchronized main hit");}};
   Check(m.Skill()&&!m.Skill()&&!m.Attack()&&!m.Dodge(),"cast input lock and cooldown");To(m,.29);Check(!m.ProtectedSkillActive,"entry before fully buried is not immune");StatusDamage(m,100);Check(m.PlayerHP==9900,"entry damage ordinary");To(m,.301);Check(m.ProtectedSkillActive,"buried immunity begins");StatusDamage(m,100);Check(m.PlayerHP==9900,"status/reflection immunity");To(m,2.249);Check(m.ProtectedSkillActive&&!m.CompletionDefenseActive&&hits==1,"immunity through return, no early armor");To(m,2.251);Check(!m.ProtectedSkillActive&&m.CompletionDefenseActive,"return transitions immunity to armor");StatusDamage(m,100);Check(m.PlayerHP==9850,"100 final damage becomes 50");To(m,7.249);Check(m.CompletionDefenseActive&&m.CompletionDefenseRemaining<.002,"armor lasts exactly five seconds");To(m,7.251);StatusDamage(m,100);Check(m.PlayerHP==9750&&!m.CompletionDefenseActive,"normal damage after five seconds");
   var enemy=Enemy(99999,.5f);m=new BattleModel(stats,enemy,10000);m.Skill();To(m,2.01);Check(m.PlayerHP==10000,"normal strikes blocked underground");To(m,2.51);Check(m.PlayerHP==9950,"normal strike takes 50 after return");To(m,7.51);Check(m.PlayerHP==9400,"ten half hits then normal hit");
   var reduced=Stats(d,s);reduced.damageReductionPercent=20;m=new BattleModel(reduced,Enemy(),10000);m.Skill();To(m,2.251);StatusDamage(m,100);Check(m.PlayerHP==9960,"existing mitigation composes: 100 to 80 to 40");
   m=new BattleModel(stats,Enemy(),10000);m.Skill();To(m,.15);m.CancelProtectedSkill();To(m,8);Check(m.EnemyHP==99999&&!m.CompletionDefenseActive&&!m.ProtectedSkillActive,"cancel before burial clears pending hit and buffs");
   m=new BattleModel(stats,Enemy(),10000);m.Skill();To(m,2.5);m.CancelProtectedSkill();Check(!m.CompletionDefenseActive,"armor cancellation");
   m=new BattleModel(stats,Enemy(1),10000);m.Skill();To(m,3);Check(m.Result==BattleResult.Victory&&!m.ProtectedSkillActive&&!m.CompletionDefenseActive,"lethal hit leaves no combat buffs");
   m=new BattleModel(stats,Enemy(99999,.10f),1);m.Skill();To(m,3);Check(m.Result==BattleResult.Defeat&&!m.CompletionDefenseActive&&!m.ProtectedSkillActive,"entry death never grants immunity or armor");
   var doubled=Stats(d,s);doubled.augments=new[]{new BattleAugment{mechanic=AugmentMechanic.DoubleCasting}};m=new BattleModel(doubled,Enemy(),10000);m.Skill();To(m,2.251);Check(m.ProtectedSkillActive&&!m.CompletionDefenseActive,"double cast extends return safely");To(m,2.40);Check(m.CompletionDefenseActive,"double cast earns one completion armor");To(m,7.40);Check(!m.CompletionDefenseActive,"double cast armor still five seconds");
   var dt=AssetDatabase.LoadAssetAtPath<SkillData>("Assets/Data/Skills/skill_dantian.asset");if(dt!=null){var st=Stats(d,dt);st.speciesId=dt.exclusiveDragonId;m=new BattleModel(st,Enemy(),10000);m.Skill();Check(m.ProtectedSkillActive,"Dantian immediate immunity unchanged");StatusDamage(m,100);Check(m.PlayerHP==10000,"Dantian status immunity unchanged");}
   Visual(d,s,stats);
  }
  static void Visual(DragonData d,SkillData s,BattleStats stats){var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var v=c.view;var screens=v.frame.Find("Collection screens");if(screens!=null)screens.gameObject.SetActive(false);var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var rect=(RectTransform)canvas.transform;rect.position=Vector3.zero;rect.localScale=Vector3.one;rect.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/Genesis");
   for(int stage=0;stage<3;stage++){c.BeginBattle(d,stats,Enemy(99999,.5f),1,false,10000,null,stage==0?1:stage*10,s);c.SendMessage("OnApplicationFocus",true);var b=c.CurrentBattle;var fx=v.GetComponent<GenesisVfx>();int objects=v.frame.GetComponentsInChildren<Transform>(true).Length;int count=0;b.Cue+=(cue,value)=>{if(b.ResolvingSkillHit){count++;Check(fx.HitsShown==count,"same-frame impact");}};Check(c.RequestSkill(),"visual cast accepted");
    for(int f=0;f<240;f++){b.Tick(1f/30);v.StepAnimation(b,1f/30);v.Show(b);if(stage==2||f==5||f==15||f==35||f==69||f==120)Capture(v,cam,rt,"blendy-"+stage+"-"+f.ToString("000"));if(f==15)Check(fx.Hidden&&b.ProtectedSkillActive,"burrow matches immunity");if(f==70)Check(!fx.Hidden&&!b.ProtectedSkillActive&&b.CompletionDefenseActive,"reappearance matches armor");}
    Check(count==1&&fx.Clean&&fx.DroppedLayers==0,"complete sequence clean, no overflow");Check(objects==v.frame.GetComponentsInChildren<Transform>(true).Length,"pooled objects stable");Check(v.skillButton.transform.Find("Equipped skill name").GetComponent<Text>().text==s.displayName,"HUD reads signature name");Debug.Log("GENESIS_FORM_OK "+stage+" peak="+fx.PeakImages+" ground="+fx.LastGround);b.Tick(15);Check(c.RequestSkill(),"repeat cast");b.Tick(.6f);v.StepAnimation(b,.6f);c.EndBattle();Check(fx.Clean&&!b.ProtectedSkillActive&&!b.CompletionDefenseActive,"exit restores actor and buffs");}
   for(int i=0;i<4;i++){c.BeginBattle(d,stats,Enemy(),1,false,10000,null,20,s);c.RequestSkill();var b=c.CurrentBattle;b.Tick(new[]{.12f,.6f,1.4f,2.6f}[i]);v.StepAnimation(b,new[]{.12f,.6f,1.4f,2.6f}[i]);c.EndBattle();Check(v.GetComponent<GenesisVfx>().Clean&&!b.ProtectedSkillActive&&!b.CompletionDefenseActive,"cancel phase "+i);}
   c.BeginBattle(d,stats,Enemy(1),1,false,10000,null,20,s);c.RequestSkill();for(int i=0;i<140;i++){c.CurrentBattle.Tick(1f/30);v.StepAnimation(c.CurrentBattle,1f/30);}Check(v.GetComponent<GenesisVfx>().Clean,"lethal impact restores actor and clears tail");c.EndBattle();cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);
  }
  static void Capture(BattleView v,Camera cam,RenderTexture rt,string name){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(480,850,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,480,850),0,0);tex.Apply();File.WriteAllBytes("Validation/Genesis/"+name+".png",tex.EncodeToPNG());UnityEngine.Object.DestroyImmediate(tex);RenderTexture.active=old;}
 }
}
