using System.IO;using System.Linq;using UnityEditor;using UnityEngine;
namespace DragonTower.Editor {public static class HaesinSetup {
 public const string Folder="Assets/Resources/VFX/Haesin",SkillPath="Assets/Data/Skills/skill_haesin.asset";
 public static void Install(){AssetDatabase.Refresh();var ti=(TextureImporter)AssetImporter.GetAtPath(Folder+"/SharkAtlas.png");ti.textureType=TextureImporterType.Default;ti.filterMode=FilterMode.Point;ti.mipmapEnabled=false;ti.alphaIsTransparency=true;ti.maxTextureSize=1024;ti.textureCompression=TextureImporterCompression.Uncompressed;ti.npotScale=TextureImporterNPOTScale.None;ti.SaveAndReimport();
  var s=AssetDatabase.LoadAssetAtPath<SkillData>(SkillPath);if(s==null){s=ScriptableObject.CreateInstance<SkillData>();AssetDatabase.CreateAsset(s,SkillPath);}var dragon=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon13.asset");s.skillId="skill_haesin";s.displayName="해신";s.description="샤키드 전용 · 거대 수압 상어를 삼킴과 대각선 절단으로 폭발시킵니다. 시전부터 복귀까지 무적.";s.elementType=ElementType.Water;s.effectKind=SkillEffectKind.Water;s.rarity=ContentRarity.Legendary;s.exclusiveDragonId=dragon.StableId;s.damage=340;s.cooldown=20;s.hitCount=1;s.initialHitDelay=2;s.protectedCastDuration=2.7f;s.protectedCastDelay=0;s.vfxDuration=3.7f;
  Icon();s.icon=AssetDatabase.LoadAssetAtPath<Sprite>(Folder+"/Icon.png");dragon.signatureSkill=s;var profile=AssetDatabase.LoadAssetAtPath<HaesinProfile>(Folder+"/Profile.asset");if(profile==null){profile=ScriptableObject.CreateInstance<HaesinProfile>();AssetDatabase.CreateAsset(profile,Folder+"/Profile.asset");}profile.skill=s;profile.style=AssetDatabase.LoadAssetAtPath<WaterVfxStyle>(WaterStyleSetup.StylePath);profile.shark=AssetDatabase.LoadAssetAtPath<Texture2D>(Folder+"/SharkAtlas.png");var db=AssetDatabase.LoadAssetAtPath<ContentDatabase>("Assets/Resources/ContentDatabase.asset");if(!db.skills.Contains(s)){db.skills=db.skills.Concat(new[]{s}).ToArray();EditorUtility.SetDirty(db);}EditorUtility.SetDirty(s);EditorUtility.SetDirty(dragon);EditorUtility.SetDirty(profile);AssetDatabase.SaveAssets();Debug.Log("HAESIN_INSTALLED");
 }
 static void Icon(){const int n=96;var t=new Texture2D(n,n,TextureFormat.RGBA32,false);for(int y=0;y<n;y++)for(int x=0;x<n;x++){float u=(x-47.5f)/48,v=(y-47.5f)/48,r=Mathf.Sqrt(u*u+v*v);Color c=r>.98f?Color.clear:r>.89f?new Color(.35f,.86f,1):new Color(.015f,.055f,.14f);float mouth=u*u/.45f+v*v/.65f;if(mouth<1){c=new Color(.015f,.025f,.06f);float tooth=Mathf.Abs(Mathf.Repeat((u+1)*6,1)-.5f);if(Mathf.Abs(v)>.38f+tooth*.45f)c=new Color(.85f,1,1);}else if(mouth<1.5f)c=new Color(.04f,.52f,.72f);if(Mathf.Abs(v-.65f*u)<.05f&&r<.92f)c=new Color(.8f,1,1);t.SetPixel(x,y,c);}t.Apply();File.WriteAllBytes(Folder+"/Icon.png",t.EncodeToPNG());Object.DestroyImmediate(t);AssetDatabase.Refresh();var im=(TextureImporter)AssetImporter.GetAtPath(Folder+"/Icon.png");im.textureType=TextureImporterType.Sprite;im.spriteImportMode=SpriteImportMode.Single;im.filterMode=FilterMode.Point;im.mipmapEnabled=false;im.alphaIsTransparency=true;im.textureCompression=TextureImporterCompression.Uncompressed;im.SaveAndReimport();}
}}
