using System;using System.IO;using System.Reflection;using UnityEngine;using UnityEngine.UI;using UnityEditor;using UnityEditor.SceneManagement;
namespace DragonTower.Editor {public static class HaesinValidation {
 static int wait;public static void Run(){HaesinSetup.Install();Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.Haesin.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetBool("HaesinCheck",true);EditorApplication.isPlaying=true;}
 [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("HaesinCheck",false)){wait=0;EditorApplication.update+=After;}};}
 static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("HaesinCheck",false);try{Test();Debug.Log("HAESIN_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
 static void Check(bool b,string m){if(!b)throw new Exception("HAESIN_FAIL "+m);Debug.Log("HAESIN_CHECK "+m);}
 static BattleEnemyStats Enemy(int hp=99999){var e=BattleEnemyStats.Normal();e.maxHP=hp;e.interval=.2f;e.damage=10;return e;}
 static void To(BattleModel b,double t){while(b.Time<t-.000001&&b.Result==BattleResult.Fighting)b.Tick((float)Math.Min(.01,t-b.Time));}
 static void Damage(BattleModel b){typeof(BattleModel).GetMethod("DamagePlayer",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(b,new object[]{100,"test"});}
 static void Test(){var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon13.asset");var octa=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon5.asset");var s=AssetDatabase.LoadAssetAtPath<SkillData>(HaesinSetup.SkillPath);var stats=d.Snapshot(20);stats.skill=s.Snapshot();stats.maxHP=10000;stats.passiveMechanic=DragonPassiveMechanic.None;stats.criticalChance=0;
 Check(s.icon!=null,"icon imported");Check(d.signatureSkill==s&&d.CanOfferSkill(s)&&!octa.CanOfferSkill(s),"exclusive signature");var other=octa.Snapshot(20);other.skill=s.Snapshot();Check(!new BattleModel(other,Enemy()).Skill(),"Octa cannot cast");var b=new BattleModel(stats,Enemy(),10000);int hits=0;b.Cue+=(cue,n)=>{if(b.ResolvingSkillHit){hits++;Check(Math.Abs(b.Time-s.initialHitDelay)<.012,"final damage timing");}};Check(b.Skill()&&b.ProtectedSkillActive&&!b.Attack()&&!b.Dodge(),"protected cinematic begins");Damage(b);To(b,2.69);Check(b.PlayerHP==10000&&b.ProtectedSkillActive&&hits==1,"full immunity and one damage event");To(b,2.71);Check(!b.ProtectedSkillActive,"immunity ends on recovery");int hp=b.PlayerHP;Damage(b);Check(b.PlayerHP==hp-100,"normal damage restored");
 var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var v=c.view;var screens=v.frame.Find("Collection screens");if(screens!=null)screens.gameObject.SetActive(false);var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var rect=(RectTransform)canvas.transform;rect.position=Vector3.zero;rect.localScale=Vector3.one;rect.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/Haesin");
 for(int form=0;form<3;form++){c.BeginBattle(d,stats,Enemy(),1,false,10000,null,form==0?1:form*10,s);c.SendMessage("OnApplicationFocus",true);b=c.CurrentBattle;var fx=v.GetComponent<HaesinVfx>();Check(fx.Configured,"configured");int objects=v.frame.GetComponentsInChildren<Transform>(true).Length;int count=0;b.Cue+=(cue,n)=>{if(b.ResolvingSkillHit){count++;Check(fx.HitsShown==count,"same frame impact");}};Check(c.RequestSkill(),"cast");for(int f=0;f<150;f++){b.Tick(1f/30);v.StepAnimation(b,1f/30);v.Show(b);Capture(v,cam,rt,form,f);if(f==48){var copy=(Image)typeof(HaesinVfx).GetField("actorCopy",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(fx);var home=(Vector2)typeof(HaesinVfx).GetField("home",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(fx);Check(Vector2.Distance(copy.rectTransform.anchoredPosition,home)<.01f,"stationary slash no dash");}if(f==43)Check(fx.EnemyHidden,"jaw close conceals target");if(f==54)Check(!fx.EnemyHidden,"split reveals target");}Check(count==1&&fx.Clean&&fx.DroppedLayers==0,"single hit clean no overflow");Check(fx.ActorsVisible,"actors restored");Check(objects==v.frame.GetComponentsInChildren<Transform>(true).Length,"pool stable");Debug.Log("HAESIN_FORM_OK "+form+" peak="+fx.Peak);b.Tick(20);Check(c.RequestSkill(),"repeat");b.Tick(1.45f);v.StepAnimation(b,1.45f);c.EndBattle();Check(fx.Clean&&!b.ProtectedSkillActive&&fx.ActorsVisible,"exit cleanup");}
 foreach(float phase in new[]{.4f,1.43f,1.62f,1.85f,2.2f}){c.BeginBattle(d,stats,Enemy(),1,false,10000,null,20,s);c.RequestSkill();b=c.CurrentBattle;b.Tick(phase);v.StepAnimation(b,phase);var fx=v.GetComponent<HaesinVfx>();fx.enabled=false;Check(fx.Clean&&!b.ProtectedSkillActive&&fx.ActorsVisible,"disable cleanup "+phase);fx.enabled=true;}
 foreach(var terminal in new[]{BattleResult.Victory,BattleResult.Defeat}){c.BeginBattle(d,stats,Enemy(),1,false,10000,null,20,s);c.RequestSkill();b=c.CurrentBattle;b.Tick(1.44f);v.StepAnimation(b,1.44f);typeof(BattleModel).GetProperty("Result").SetValue(b,terminal);v.StepAnimation(b,.01f);var fx=v.GetComponent<HaesinVfx>();Check(fx.Clean&&fx.ActorsVisible&&!b.ProtectedSkillActive,"external terminal cleanup "+terminal);c.EndBattle();}
 c.BeginBattle(d,stats,Enemy(1),1,false,10000,null,20,s);c.RequestSkill();for(int f=0;f<150;f++){c.CurrentBattle.Tick(1f/30);v.StepAnimation(c.CurrentBattle,1f/30);}Check(v.GetComponent<HaesinVfx>().Clean&&v.GetComponent<HaesinVfx>().ActorsVisible,"lethal cleanup");c.EndBattle();cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);
 }
 static void Capture(BattleView v,Camera cam,RenderTexture rt,int form,int f){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var t=new Texture2D(480,850,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,480,850),0,0);t.Apply();File.WriteAllBytes("Validation/Haesin/sharkid-"+form+"-"+f.ToString("000")+".png",t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);RenderTexture.active=old;}
 public static void BuildWeb(){HaesinSetup.Install();const string path="Assets/Scenes/Prototypes/HaesinPreview.unity";EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");var preview=new GameObject("Haesin review").AddComponent<HaesinPreview>();preview.dragonData=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon13.asset");preview.signature=AssetDatabase.LoadAssetAtPath<SkillData>(HaesinSetup.SkillPath);EditorSceneManager.SaveScene(EditorSceneManager.GetActiveScene(),path);var report=BuildPipeline.BuildPlayer(new[]{path},"../Haesin-WebGL",BuildTarget.WebGL,BuildOptions.None);if(report.summary.result!=UnityEditor.Build.Reporting.BuildResult.Succeeded)throw new Exception("Haesin WebGL failed");Debug.Log("HAESIN_WEBGL_OK");}

}}

