using System;using System.IO;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.UI;
namespace DragonTower.Editor {
 public static class HydraValidation {
  static int wait;static void Check(bool b,string label){if(!b)throw new Exception("HYDRA_FAIL "+label);Debug.Log("HYDRA_CHECK "+label);}
  public static void Run(){HydraSetup.Install();Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.Hydra.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetBool("HydraCheck",true);EditorApplication.isPlaying=true;}
  [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("HydraCheck",false)){wait=0;EditorApplication.update+=After;}};}
  static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("HydraCheck",false);try{Rules();Visual();Debug.Log("HYDRA_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
  static SkillData Data=>AssetDatabase.LoadAssetAtPath<SkillData>(HydraSetup.SkillPath);
  static BattleStats Stats(){var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon14.asset");var s=d.Snapshot(20);s.maxHP=1000;s.skill=Data.Snapshot();s.criticalChance=0;s.augments=Array.Empty<BattleAugment>();s.items=Array.Empty<BattleItem>();return s;}
  static BattleEnemyStats Enemy(){var e=BattleEnemyStats.Normal();e.maxHP=20000;e.damage=0;e.interval=100;return e;}
  static void Rules(){var s=Stats();var b=new BattleModel(s,Enemy(),1000,()=>.99);int hits=0;b.Cue+=(cue,n)=>{if(b.ResolvingSkillHit)hits++;};b.Tick(1.001f);Check(b.PoisonTickCount==1,"initial poison at 1 second");b.Tick(2);Check(b.PoisonTickCount==2&&b.PoisonTickInterval==2,"base poison every 2 seconds");Check(b.Skill(),"cast");b.Tick(3.401f);Check(hits==1&&b.EnemyPoisonAccelerated&&b.PoisonTickInterval==1,"one final hit and 1 second accelerated interval");double applied=b.Time;int count=b.PoisonTickCount;int hp=b.EnemyHP;b.Tick(4.99f);Check(b.EnemyPoisonAccelerated&&b.PoisonTickCount-count==5,"five accelerated ticks with preserved partial interval");Check(hp-b.EnemyHP==5*System.Math.Max(1,(int)System.Math.Round(s.attackDamage*.18f)),"per tick damage unchanged");b.Tick(.02f);Check(!b.EnemyPoisonAccelerated&&b.PoisonTickInterval==2,"restores base interval after 5 seconds");
   s=Stats();s.skill.initialHitDelay=0;s.skill.castLockDuration=0;s.skill.cooldown=0;b=new BattleModel(s,Enemy(),1000,()=>.99);b.Tick(.5f);b.Skill();b.Tick(.24f);Check(b.PoisonTickCount==0,"partial initial interval retained");b.Tick(.02f);Check(b.PoisonTickCount==1,"partial interval scaled not reset");b.Tick(2);b.Skill();Check(b.PoisonTickInterval==1&&b.PoisonAccelerationRemaining>4.999,"refresh does not stack");b.Tick(5.01f);Check(b.PoisonTickInterval==2&&!b.EnemyPoisonAccelerated,"refresh expiry");
   s=Stats();s.passiveMechanic=DragonPassiveMechanic.None;s.skill.initialHitDelay=0;s.skill.castLockDuration=0;s.skill.cooldown=0;b=new BattleModel(s,Enemy(),1000,()=>.99);b.Skill();Check(!b.EnemyPoisoned&&b.EnemyPoisonAccelerated,"unpoisoned target retains modifier only");b.Tick(1);s.skill.statusOnHit=true;s.skill.statusEffect=CombatStatusEffect.Poison;s.skill.statusChancePercent=100;s.skill.statusPower=7;s.skill.poisonAccelerationDuration=0;b.Skill();b.Tick(.51f);Check(b.PoisonTickCount==1&&b.EnemyPoisonAccelerated,"new poison uses remaining tempo");b.Tick(4);Check(!b.EnemyPoisonAccelerated&&b.EnemyPoisoned,"poison survives acceleration expiry");
   s=Stats();s.speciesId="nova";b=new BattleModel(s,Enemy(),1000);Check(!b.Skill(),"other dragon denied");var venom=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon14.asset");var nova=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon6.asset");Check(venom.signatureSkill==Data&&venom.CanOfferSkill(Data)&&!nova.CanOfferSkill(Data),"signature ownership");
   s=Stats();s.skill.initialHitDelay=0;s.skill.castLockDuration=0;b=new BattleModel(s,Enemy(),1000);b.Tick(.5f);b.Skill();b.Tick(5);Check(b.PoisonTickCount==5&&!b.EnemyPoisonAccelerated,"exact expiry boundary");b.Tick(.49f);Check(b.PoisonTickCount==5,"remaining progress stretched at expiry");b.Tick(.02f);Check(b.PoisonTickCount==6,"next normal tick no duplicate or omission");b.CancelPoisonAcceleration();Check(b.PoisonTickInterval==2,"explicit cleanup");
   s=Stats();var lethal=Enemy();lethal.damage=2000;lethal.interval=.2f;b=new BattleModel(s,lethal,1000);b.Skill();b.Tick(1);Check(b.Result==BattleResult.Defeat&&!b.EnemyPoisonAccelerated,"caster death clears modifier");
   s=Stats();s.skill.initialHitDelay=0;lethal=Enemy();lethal.maxHP=1;b=new BattleModel(s,lethal,1000);b.Skill();Check(b.Result==BattleResult.Victory&&!b.EnemyPoisonAccelerated,"target death no lingering modifier");
   s=Stats();b=new BattleModel(s,Enemy(),1000);b.Skill();b.CancelProtectedSkill();b.Tick(4);Check(!b.EnemyPoisonAccelerated,"cancel no late skill damage");
  }
  static void Visual(){var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var v=c.view;var screens=v.frame.Find("Collection screens");if(screens!=null)screens.gameObject.SetActive(false);var dragon=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon14.asset");var stats=Stats();c.BeginBattle(dragon,stats,Enemy(),1,false,1000,null,20,Data);c.SendMessage("OnApplicationFocus",true);var b=c.CurrentBattle;var fx=v.GetComponent<HydraVfx>();
   var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var rect=(RectTransform)canvas.transform;rect.position=Vector3.zero;rect.localScale=Vector3.one;rect.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/Hydra");
   Check(c.RequestSkill(),"visual cast");int objects=v.frame.GetComponentsInChildren<Transform>(true).Length;
   for(int f=0;f<330;f++){b.Tick(1f/30);v.StepAnimation(b,1f/30);v.Show(b);Capture(v,cam,rt,f);}
   Check(fx.Clean&&!b.SignatureCastLocked,"normal visual expiry");Debug.Log("HYDRA_POOL before="+objects+" after="+v.frame.GetComponentsInChildren<Transform>(true).Length+" dropped="+fx.Dropped+" peak="+fx.Peak);Check(fx.Dropped==0,"no mesh overflow");Check(v.GetComponent<LegendaryScreenDimming>().Clean,"full screen grade restored");Check(Time.timeScale==1,"global clock unchanged");Debug.Log("HYDRA_VISUAL peak="+fx.Peak+" hp="+b.PlayerHP);
   b.SkillReady=0;Check(c.RequestSkill(),"cancel test starts");v.StepAnimation(b,.35f);fx.enabled=false;Check(fx.Clean&&!b.SignatureCastLocked,"component disable clears state and background");fx.enabled=true;b.SkillReady=0;c.RequestSkill();v.StepAnimation(b,.3f);c.EndBattle();Check(fx.Clean&&!b.SignatureCastLocked,"battle end cleanup");cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);
  }
  static void Capture(BattleView v,Camera cam,RenderTexture rt,int f){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var t=new Texture2D(480,850,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,480,850),0,0);t.Apply();File.WriteAllBytes("Validation/Hydra/"+f.ToString("000")+".png",t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);RenderTexture.active=old;}
 }
}

