using System;using System.Linq;using UnityEngine;using UnityEditor;
namespace DragonTower.Editor {
 public static class InventorySplitValidation {
 static int checks;static void Check(bool ok,string label){if(!ok)throw new Exception("INVENTORY_FAIL "+label);checks++;}
 public static void Run(){try{Verify();MonsterRewardValidation.Verify();ProgressionRewardsValidation.Verify();FloorProgressionValidation.Verify();Debug.Log("INVENTORY_OK checks="+checks+" plus floor score shop regression");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
 public static void Verify(){var db=ContentDatabase.Load();var d=db.dragons[0];var r=new TowerRun(d.maxHP,0,1,d.elementType,d.alternateSkillElement,d.StableId,d);var gear=db.items.Where(x=>x.kind==ItemKind.Equipment).Take(4).ToArray();var pot=db.items.First(x=>x.StableId=="item_healing_potion");var other=db.items.First(x=>x.StableId=="item_time_shard");
 foreach(var g in gear.Take(3))r.AddItem(g);Check(r.ItemSlots.Count==3&&!r.CanAddItem(gear[3]),"three equipment");Check(!r.CanAddItem(gear[0]),"duplicate rejected");try{r.AddItem(gear[0]);throw new Exception("duplicate allowed");}catch(InvalidOperationException){}
 Check(r.CanAddItem(pot),"independent consumable slot");for(int i=0;i<3;i++)r.AddItem(pot);Check(r.ItemCountAt(3)==3&&!r.CanAddItem(pot),"cap three");try{r.AddItem(pot);throw new Exception("fourth allowed");}catch(InvalidOperationException){}
 Check(!r.CanAddItem(other),"different consumable needs choice");r.AddItem(other,3);r.AddItem(other);r.AddItem(other);Check(r.ItemCountAt(3)==3&&r.ItemAt(3)==other,"override old maximumStacks two to three");r.AddItem(gear[3],1);Check(r.ItemAt(1)==gear[3]&&r.ItemAt(3)==other,"equipment replacement isolated");
 var copy=TowerRun.Restore(JsonUtility.FromJson<TowerRunSave>(JsonUtility.ToJson(r.Capture())),db);Check(copy.ItemSlots.Count==3&&copy.ItemCountAt(3)==3&&copy.ItemAt(3)==other,"3+1 save");copy.ConsumeItem(3);Check(copy.ItemCountAt(3)==2&&copy.ItemSlots.Count==3,"consume only dedicated slot");copy.ConsumeItem(3);copy.ConsumeItem(3);Check(copy.ItemAt(3)==null&&copy.ItemSlots.Count==3,"empty after last use");
 var old=r.Capture();old.inventoryVersion=0;old.consumable=null;old.slots=new[]{new SavedItemSlot{id=gear[0].StableId,count=2},new SavedItemSlot{id=pot.StableId,count=5},new SavedItemSlot{id=other.StableId,count=2}};var migrated=TowerRun.Restore(old,db);Check(migrated.ItemSlots.Count==1&&migrated.ItemCountAt(0)==1&&migrated.ItemCountAt(3)==3,"legacy split");Check(migrated.PendingInventory.Sum(x=>x.Count)==5,"legacy surplus preserved");var twice=TowerRun.Restore(migrated.Capture(),db);Check(twice.PendingInventory.Sum(x=>x.Count)==5,"migration only once");var historical=TowerRun.Restore(old,db,true);Check(historical.ItemSlots.Count==3&&historical.ItemCountAt(0)==2,"legacy replay retains original equipment stacks");
 var healRun=new TowerRun(d.maxHP,0,1,d.elementType,d.alternateSkillElement,d.StableId,d);healRun.AddItem(pot);healRun.AddItem(pot);var initial=healRun.Capture(false);var enemy=new BattleEnemyStats{maxHP=100000,damage=10,interval=1};var b=new BattleModel(healRun.BuildBattleStats(d.Snapshot()),enemy,d.maxHP,()=>new System.Random(1).NextDouble());b.Tick(1.5f);Check(b.UseItem(pot),"consumable battle effect");healRun.ConsumeItem(3);Check(healRun.ItemCountAt(3)==1,"battle consumption");
 }
 }
}
