using System;using System.Linq;using UnityEngine;using UnityEditor;
namespace DragonTower.Editor {
 public static class ItemPhase2Validation {
  static int checks;static ContentDatabase db;static ItemData Gear(string id)=>db.items.First(x=>x.StableId==id);
  static void Check(bool x,string n){if(!x)throw new Exception("ITEM_PHASE2_FAIL "+n);checks++;}
  static BattleModel Model(string dragon,params string[] gear){var d=db.dragons.First(x=>x.displayName==dragon);var s=d.Snapshot(20);s.maxHP=10000;s.attackDamage=100;s.criticalChance=0;s.items=gear.Select(x=>Gear(x).Snapshot()).ToArray();s.augments=Array.Empty<BattleAugment>();return new BattleModel(s,new BattleEnemyStats{maxHP=1000000,damage=100,interval=1,elementType=ElementType.Neutral},s.maxHP,()=>.5);}
  const string Fire="item_infighting_glove",Frost="item_mana_prism",Wind="item_yata_mirror",Meteor="item_meteor_fragment",Guard="item_guardian_brooch";
  public static void Run(){try{db=ContentDatabase.Load();Verify();ItemProcValidation.Verify();InventorySplitValidation.Verify();MonsterRewardValidation.Verify();ProgressionRewardsValidation.Verify();FloorProgressionValidation.Verify();Debug.Log("ITEM_PHASE2_OK checks="+checks+" plus phase1 inventory progression regressions");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
  static void Verify(){
   Check(new[]{Fire,Frost,Wind,Meteor,Guard}.All(x=>Gear(x).autoTrigger.enabled&&Gear(x).mechanic==ItemMechanic.None&&Gear(x).effects.Count==0),"five assets migrated without old effects");
   var fire=Model("볼트",Fire);fire.Attack();Check(fire.ItemProcCount==1&&fire.ItemProcHitCount==0,"fire starts only then flight");fire.Tick(.35f);Check(fire.ItemProcHitCount==1,"fire contact damage");fire.Attack();Check(fire.ItemProcCount==1,"fire cooldown");
   var frost=Model("크로노",Frost);frost.Dragon.skill=new SkillStats{damage=10,cooldown=1,hitCount=5,hitInterval=.1f};frost.Skill();frost.Tick(Gear(Frost).autoTrigger.activationDelay+.6f);Check(frost.ItemProcCount==1&&frost.ItemProcHitCount==1&&frost.EnemySlowed,"frost multihit once and slow");
   var dodge=Model("오로라",Wind);dodge.Dodge();dodge.Tick(.5f);Check(dodge.ItemProcCount==0,"empty swipe no proc");dodge.Tick(1.3f);dodge.Dodge();dodge.Tick(.3f);Check(dodge.ItemProcCount==1,"Aurora one real dodge");dodge.Tick(.2f);Check(dodge.ItemProcHitCount==1,"wind damage");
   var meteor=Model("노바",Meteor);meteor.Skill();Check(meteor.ItemProcCount==1&&meteor.ItemProcHitCount==0,"meteor approved cast only");meteor.Tick(Gear(Meteor).autoTrigger.activationDelay+.8f);Check(meteor.ItemProcHitCount==1,"meteor impact");
   var nova=Model("노바",Meteor);nova.Dragon.items[0].autoTrigger.cooldown=0; // refresh immutable rule by rebuilding
   var ns=nova.Dragon;var n=new BattleModel(ns,new BattleEnemyStats{maxHP=100000,damage=1,interval=100},10000,()=>.5);Check(n.Skill(),"Nova first approved");int hp=n.PlayerHP;Check(n.Skill()&&n.PlayerHP<hp&&n.ItemProcCount==2,"Nova paid recast approved");
   var poor=new BattleModel(ns,new BattleEnemyStats{maxHP=100000,damage=1,interval=100},1,()=>.5);poor.Skill();int count=poor.ItemProcCount;Check(!poor.Skill()&&poor.ItemProcCount==count,"Nova unaffordable recast no proc");
   var guard=Model("블랜디",Guard);var baseline=Model("블랜디");int before=guard.PlayerHP;guard.Tick(1.01f);baseline.Tick(1.01f);int normal=before-baseline.PlayerHP;Check(before-guard.PlayerHP==(int)Math.Round(normal*.88,MidpointRounding.AwayFromZero)&&guard.ItemProcCount==1,"guard multiplicative before HP");int prev=guard.PlayerHP;guard.Tick(1);Check(prev-guard.PlayerHP==normal&&guard.ItemProcCount==1,"guard cooldown no permanent reduction");
   var bolt=Model("볼트",Fire);bolt.Dragon.skill=db.dragons.First(x=>x.displayName=="볼트").signatureSkill.Snapshot();bolt.Skill();bolt.Tick(bolt.Dragon.skill.attackEmpowerDelay+.01f);bolt.Attack();Check(bolt.EmpoweredHitCount==1&&bolt.ItemProcCount==1,"Bolt bonus lightning no recursive fire");
   var chrono=Model("크로노",Fire);chrono.Dragon.skill=db.dragons.First(x=>x.displayName=="크로노").signatureSkill.Snapshot();chrono.Skill();chrono.Tick(chrono.Dragon.skill.timeDomainDelay+.01f);chrono.Attack();long stored=chrono.StoredBasicDamage;int enemy=chrono.EnemyHP;chrono.Tick(.36f);Check(stored>0&&chrono.StoredBasicDamage==stored&&chrono.EnemyHP<enemy&&chrono.ItemProcHitCount==1,"Chrono fire immediate not stored");
   var blended=Model("블랜디",Guard);var clean=Model("블랜디");var sk=db.dragons.First(x=>x.displayName=="블랜디").signatureSkill;blended.Dragon.skill=sk.Snapshot();clean.Dragon.skill=sk.Snapshot();blended.Skill();clean.Skill();float wait=sk.protectedCastDuration+.02f;blended.Tick(wait);clean.Tick(wait);Check(blended.CompletionDefenseActive,"Blendy earth armor active");int bh=blended.PlayerHP,ch=clean.PlayerHP;float until=(float)(blended.NextEnemyStrike-blended.Time+.01);blended.Tick(until);clean.Tick(until);Check(bh-blended.PlayerHP==(int)Math.Round((ch-clean.PlayerHP)*.88,MidpointRounding.AwayFromZero),"Blendy existing final reduction then guard once");
   var triple=Model("크로노",Fire,Frost,Meteor);triple.Dragon.skill=new SkillStats{damage=10,hitCount=3,hitInterval=.1f,cooldown=1};triple.Attack();triple.Skill();triple.Tick(Math.Max(Gear(Frost).autoTrigger.activationDelay,Gear(Meteor).autoTrigger.activationDelay)+.8f);Check(triple.ItemProcCount==3&&triple.ItemProcHitCount==3,"three equipped no proc chains");var saved=triple.CaptureItemCooldowns();var restored=Model("크로노",Fire,Frost,Meteor);restored.RestoreItemCooldowns(saved);Check(saved.All(x=>Math.Abs(x.remaining-restored.ItemCooldownRemaining(x.itemId))<.0001),"three cooldowns restore");triple.Dragon.items=Array.Empty<BattleItem>();triple.Tick(16);triple.Attack();Check(triple.ItemProcCount==3,"unmount no further procs");
  }
 }
}

