using System;using System.IO;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;
namespace DragonTower.Editor {public static class KrakenValidation {
 static int wait;public static void Run(){KrakenSetup.Install();Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.Kraken.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetBool("KrakenCheck",true);EditorApplication.isPlaying=true;}
 [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("KrakenCheck",false)){wait=0;EditorApplication.update+=After;}};}
 static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("KrakenCheck",false);try{Test();Debug.Log("KRAKEN_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
 static void Check(bool b,string m){if(!b)throw new Exception("KRAKEN_FAIL "+m);Debug.Log("KRAKEN_CHECK "+m);}
 static BattleEnemyStats Enemy(int hp=99999){var e=BattleEnemyStats.Normal();e.maxHP=hp;e.damage=1;e.interval=2;return e;}
 static BattleStats Stats(DragonData d,SkillData s){var b=d.Snapshot(20);b.skill=s.Snapshot();b.maxHP=10000;b.passiveMechanic=DragonPassiveMechanic.None;b.criticalChance=0;return b;}
 static void Test(){var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon5.asset");var shark=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon13.asset");var s=AssetDatabase.LoadAssetAtPath<SkillData>(KrakenSetup.SkillPath);var aqua=AssetDatabase.LoadAssetAtPath<SkillData>("Assets/Data/Skill5.asset");var sequence=s.persistentAttack.Snapshot();Check(s.icon!=null&&d.signatureSkill==s&&d.CanOfferSkill(s)&&!shark.CanOfferSkill(s),"signature and icon");Check(!new BattleModel(Stats(shark,s),Enemy()).Skill(),"Sharkid excluded");
  foreach(float dt in new[]{1f/30,.007f,.7f}){var stats=Stats(d,s);var b=new BattleModel(stats,Enemy(),10000,()=>1);int count=0,other=0;double begun=b.Time;int total=0;b.Cue+=(cue,n)=>{if(cue==CombatCue.PersistentHit){var beat=sequence.attacks[count];Check(Math.Abs(b.Time-begun-beat.time)<.00001,"impact deadline "+count);count++;total+=n;}if(b.ResolvingSkillHit)other++;};Check(b.Skill()&&b.PersistentAttackActive&&!b.SignatureCastLocked&&!b.ProtectedSkillActive,"unlocked summon");Check(b.Attack()&&b.Dodge(),"immediate attack dodge");bool swapped=false;for(int j=0;j<Mathf.CeilToInt(12/dt);j++){b.Tick(dt);if(b.Time>3&&!swapped){stats.skill=aqua.Snapshot();b.SkillReady=b.Time;Check(b.Skill(),"other skill during summon");swapped=true;}if(b.Time>5)b.Attack();}Check(count==sequence.attacks.Length&&other==1&&!b.PersistentAttackActive,"independent complete hits and other skill");int expected=0;foreach(var beat in sequence.attacks)expected+=(int)Math.Round(s.damage*beat.damageMultiplier);Check(total==expected,"snapshot damage unchanged by skill swap");int old=count;b.Tick(20);Check(count==old,"no late damage");}
  var cancel=new BattleModel(Stats(d,s),Enemy());cancel.Skill();cancel.Tick(3);int pre=cancel.PersistentHits;cancel.CancelPersistentAttack();cancel.Tick(12);Check(cancel.PersistentHits==pre&&!cancel.PersistentAttackActive,"model cancel");
  var recast=new BattleModel(Stats(d,s),Enemy());recast.Skill();recast.Tick(2);recast.SkillReady=recast.Time;recast.Skill();recast.Tick(11);Check(recast.PersistentHits==sequence.attacks.Length,"recast replaces no duplicate summon");
  var lethal=new BattleModel(Stats(d,s),Enemy(1));lethal.Skill();lethal.Tick(12);Check(lethal.Result==BattleResult.Victory&&lethal.PersistentHits==1&&!lethal.PersistentAttackActive,"lethal stops attacks");
  var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var v=c.view;var screens=v.frame.Find("Collection screens");if(screens!=null)screens.gameObject.SetActive(false);var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var rect=(RectTransform)canvas.transform;rect.position=Vector3.zero;rect.localScale=Vector3.one;rect.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/Kraken");
  for(int form=0;form<3;form++){var stats=Stats(d,s);c.BeginBattle(d,stats,Enemy(),1,false,10000,null,form==0?1:form*10,s);c.SendMessage("OnApplicationFocus",true);var b=c.CurrentBattle;var fx=v.GetComponent<KrakenVfx>();int hits=0;b.Cue+=(cue,n)=>{if(cue==CombatCue.PersistentHit){hits++;Check(fx.HitsShown==hits,"same frame damage VFX");}};Check(c.RequestSkill(),"battle cast");int objects=v.frame.GetComponentsInChildren<Transform>(true).Length;for(int f=0;f<360;f++){b.Tick(1f/30);if(f==30||f==80||f==150||f==210)c.RequestAttack();if(f==100)Check(c.RequestDodge(1),"battle dodge");if(f==120){stats.skill=aqua.Snapshot();b.SkillReady=b.Time;v.SetSkillPresentation(aqua);Check(c.RequestSkill()&&fx.Active,"battle simultaneous common skill");}v.StepAnimation(b,1f/30);v.Show(b);Capture(v,cam,rt,form,f);}Check(hits==sequence.attacks.Length&&fx.Clean&&fx.DroppedLayers==0,"complete cleanup and no geometry overflow");Check(objects==v.frame.GetComponentsInChildren<Transform>(true).Length,"stable object pool");Debug.Log("KRAKEN_FORM_OK "+form+" peak="+fx.Peak);c.EndBattle();}
  foreach(float t in new[]{.4f,1.3f,5f,9.8f}){c.BeginBattle(d,Stats(d,s),Enemy(),1,false,10000,null,20,s);c.RequestSkill();c.CurrentBattle.Tick(t);v.StepAnimation(c.CurrentBattle,t);var b=c.CurrentBattle;var fx=v.GetComponent<KrakenVfx>();c.EndBattle();Check(fx.Clean&&!b.PersistentAttackActive,"battle exit "+t);}
  foreach(var terminal in new[]{BattleResult.Victory,BattleResult.Defeat}){c.BeginBattle(d,Stats(d,s),Enemy(),1,false,10000,null,20,s);c.RequestSkill();c.CurrentBattle.Tick(3);v.StepAnimation(c.CurrentBattle,3);typeof(BattleModel).GetProperty("Result").SetValue(c.CurrentBattle,terminal);v.StepAnimation(c.CurrentBattle,.01f);Check(v.GetComponent<KrakenVfx>().Clean&&!c.CurrentBattle.PersistentAttackActive,"terminal cleanup "+terminal);c.EndBattle();}
  c.BeginBattle(d,Stats(d,s),Enemy(),1,false,10000,null,20,s);c.RequestSkill();c.CurrentBattle.Tick(2);v.StepAnimation(c.CurrentBattle,2);var effect=v.GetComponent<KrakenVfx>();effect.enabled=false;Check(effect.Clean&&!c.CurrentBattle.PersistentAttackActive,"disable cleanup");effect.enabled=true;c.EndBattle();cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);
 }
 static void Capture(BattleView v,Camera cam,RenderTexture rt,int form,int f){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var t=new Texture2D(480,850,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,480,850),0,0);t.Apply();File.WriteAllBytes("Validation/Kraken/octa-"+form+"-"+f.ToString("000")+".png",t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);RenderTexture.active=old;}
 public static void BuildWeb(){KrakenSetup.Install();const string path="Assets/Scenes/Prototypes/KrakenPreview.unity";EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");var preview=new GameObject("Kraken review").AddComponent<KrakenPreview>();preview.dragonData=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon5.asset");preview.signature=AssetDatabase.LoadAssetAtPath<SkillData>(KrakenSetup.SkillPath);preview.common=AssetDatabase.LoadAssetAtPath<SkillData>("Assets/Data/Skill5.asset");EditorSceneManager.SaveScene(EditorSceneManager.GetActiveScene(),path);var report=BuildPipeline.BuildPlayer(new[]{path},"../Kraken-WebGL",BuildTarget.WebGL,BuildOptions.None);if(report.summary.result!=UnityEditor.Build.Reporting.BuildResult.Succeeded)throw new Exception("Kraken WebGL failed");Debug.Log("KRAKEN_WEBGL_OK");}
}}
