using System;using System.IO;using System.Linq;using UnityEditor;using UnityEngine;
namespace DragonTower.Editor {public static class KrakenSetup {
 public const string Folder="Assets/Resources/VFX/Kraken",SkillPath="Assets/Data/Skills/skill_kraken.asset";
 public static void Install(){Directory.CreateDirectory(Folder);AssetDatabase.Refresh();var data=AssetDatabase.LoadAssetAtPath<PersistentAttackData>(Folder+"/AttackSequence.asset");if(data==null){data=ScriptableObject.CreateInstance<PersistentAttackData>();data.duration=10;
 var times=new[]{1.4f,2.3f,3.15f,4.1f,4.85f,5.55f,6.2f,6.8f,7.35f,7.9f,8.4f,9.20f,9.34f,9.48f,9.62f,9.76f,9.90f};var limbs=new[]{2,3,0,5,4,1,2,3,5,0,4,0,2,3,1,5,4};var motions=new[]{0,1,0,3,2,1,0,2,3,1,0,4,4,4,4,4,4};data.attacks=new PersistentAttackBeat[times.Length];for(int i=0;i<times.Length;i++)data.attacks[i]=new PersistentAttackBeat{time=times[i],limb=limbs[i],motion=(PersistentAttackMotion)motions[i],damageMultiplier=i==times.Length-1?4.5f:i>=11?1.6f:1};AssetDatabase.CreateAsset(data,Folder+"/AttackSequence.asset");}
 var s=AssetDatabase.LoadAssetAtPath<SkillData>(SkillPath);if(s==null){s=ScriptableObject.CreateInstance<SkillData>();s.damage=24;s.cooldown=22;s.hitCount=1;s.vfxDuration=11.15f;AssetDatabase.CreateAsset(s,SkillPath);}s.skillId="skill_kraken";s.displayName="크라켄";s.description="옥타 전용 · 심해의 촉수가 10초간 독립 공격합니다. 소환 중에도 기존 전투 행동을 사용할 수 있습니다.";s.elementType=ElementType.Water;s.effectKind=SkillEffectKind.Water;s.rarity=ContentRarity.Legendary;s.persistentAttack=data;
 var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon5.asset");s.exclusiveDragonId=d.StableId;Icon();s.icon=AssetDatabase.LoadAssetAtPath<Sprite>(Folder+"/Icon.png");d.signatureSkill=s;
 var profile=AssetDatabase.LoadAssetAtPath<KrakenProfile>(Folder+"/Profile.asset");if(profile==null){profile=ScriptableObject.CreateInstance<KrakenProfile>();AssetDatabase.CreateAsset(profile,Folder+"/Profile.asset");}profile.skill=s;profile.style=AssetDatabase.LoadAssetAtPath<WaterVfxStyle>(WaterStyleSetup.StylePath);
 var db=AssetDatabase.LoadAssetAtPath<ContentDatabase>("Assets/Resources/ContentDatabase.asset");if(!db.skills.Contains(s)){db.skills=db.skills.Concat(new[]{s}).ToArray();EditorUtility.SetDirty(db);}EditorUtility.SetDirty(profile);EditorUtility.SetDirty(d);EditorUtility.SetDirty(s);AssetDatabase.SaveAssets();Debug.Log("KRAKEN_INSTALLED");
 }
 static void Icon(){const int n=96;var t=new Texture2D(n,n,TextureFormat.RGBA32,false);for(int y=0;y<n;y++)for(int x=0;x<n;x++){float u=(x-48)/48f,v=(y-48)/48f;Color c=new Color(.015f,.035f,.10f);float ring=u*u+(v+.55f)*(v+.55f)*10;if(Mathf.Abs(ring-.7f)<.15f)c=new Color(.05f,.65f,.8f);for(int i=0;i<4;i++){float h=(v+.58f)/1.4f,curve=(-.65f+i*.43f)+Mathf.Sin(h*4+i)*.23f;float w=.10f*(1-h*.6f);if(h>=0&&h<=1&&Mathf.Abs(u-curve)<w){c=new Color(.05f,.42f,.56f);if(u>curve+w*.3f)c=new Color(.35f,.85f,.9f);if(y%13<4&&u<curve)c=new Color(.84f,.5f,.74f);}}if(u*u+v*v>.98f)c=Color.clear;t.SetPixel(x,y,c);}t.Apply();File.WriteAllBytes(Folder+"/Icon.png",t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);AssetDatabase.Refresh();var im=(TextureImporter)AssetImporter.GetAtPath(Folder+"/Icon.png");im.textureType=TextureImporterType.Sprite;im.spriteImportMode=SpriteImportMode.Single;im.filterMode=FilterMode.Point;im.mipmapEnabled=false;im.alphaIsTransparency=true;im.textureCompression=TextureImporterCompression.Uncompressed;im.SaveAndReimport();}
}}
