using System;using System.IO;using System.Reflection;using UnityEngine;using UnityEngine.UI;using UnityEditor;using UnityEditor.SceneManagement;
namespace DragonTower.Editor {public static class MirLegendaryValidation {
 static int wait;public static void WindOnly(){Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.MirLegendary.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetBool("MirLegendWind",true);SessionState.SetBool("MirLegendCheck",true);EditorApplication.isPlaying=true;}public static void Run(){MirLegendarySetup.Install();Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.MirLegendary.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetBool("MirLegendCheck",true);EditorApplication.isPlaying=true;}
 [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("MirLegendCheck",false)){wait=0;EditorApplication.update+=After;}};}
 static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("MirLegendCheck",false);try{if(SessionState.GetBool("MirLegendWind",false)){SessionState.SetBool("MirLegendWind",false);TestWind();}else Test();Debug.Log("HWARYONG_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
 static void Check(bool b,string m){if(!b)throw new Exception("HWARYONG_FAIL "+m);Debug.Log("HWARYONG_CHECK "+m);}
 static BattleEnemyStats Enemy(int hp=99999){var e=BattleEnemyStats.Normal();e.maxHP=hp;e.interval=.2f;e.damage=10;return e;}
 static void To(BattleModel b,double t){while(b.Time<t-.000001&&b.Result==BattleResult.Fighting)b.Tick((float)Math.Min(.01,t-b.Time));}
 static void Damage(BattleModel b){typeof(BattleModel).GetMethod("DamagePlayer",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(b,new object[]{100,"test"});}
 static void TestWind(){var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon10.asset");var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var screens=c.view.frame.Find("Collection screens");if(screens!=null)screens.gameObject.SetActive(false);foreach(string path in new[]{"Assets/Data/Skill2.asset","Assets/Data/Skills/skill_falling_flower.asset","Assets/Data/Skills/skill_gale_slash.asset","Assets/Data/Skills/skill_wind_claw.asset"}){var s=AssetDatabase.LoadAssetAtPath<SkillData>(path);var stats=d.Snapshot(20);stats.skill=s.Snapshot();stats.criticalChance=0;var e=Enemy();e.interval=100;c.BeginBattle(d,stats,e,1,false,stats.maxHP,null,20,s);c.SendMessage("OnApplicationFocus",true);int hits=0;c.CurrentBattle.Cue+=(cue,n)=>{if(c.CurrentBattle.ResolvingSkillHit)hits++;};Check(c.RequestSkill(),"Wind still casts "+s.StableId);for(int f=0;f<90;f++){c.CurrentBattle.Tick(1f/30);c.view.StepAnimation(c.CurrentBattle,1f/30);}Check(hits==s.hitCount&&!c.view.GetComponent<MirLegendaryVfx>().Configured,"Wind unchanged "+s.StableId);c.EndBattle();}} static void Test(){var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon10.asset");var otherDragon=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon2.asset");var s=AssetDatabase.LoadAssetAtPath<SkillData>(MirLegendarySetup.SkillPath);var stats=d.Snapshot(20);stats.skill=s.Snapshot();stats.maxHP=10000;stats.criticalChance=0;
 Check(s.icon!=null&&d.signatureSkill==s&&d.CanOfferSkill(s)&&!otherDragon.CanOfferSkill(s)&&!d.elementSkillPool.Contains(s),"exclusive signature outside shared pool");var other=otherDragon.Snapshot(20);other.skill=s.Snapshot();Check(!new BattleModel(other,Enemy()).Skill(),"other dragon rejected");
 var b=new BattleModel(stats,Enemy(),10000);int hits=0,total=0;b.Cue+=(cue,n)=>{if(b.ResolvingSkillHit){Check(Math.Abs(b.Time-s.hitTimeOffsets[hits])<.012,"damage timing "+hits);Check(n==(hits==0?170:340),"damage ratio "+hits);hits++;total+=n;}};Check(b.Skill()&&b.ProtectedSkillActive&&!b.Attack()&&!b.Dodge(),"protected cinematic begins");Damage(b);To(b,4.69);Check(b.PlayerHP==10000&&hits==2&&total==510&&b.ProtectedSkillActive,"two hits full cast immunity");To(b,4.71);Check(!b.ProtectedSkillActive,"immunity ends");int hp=b.PlayerHP;Damage(b);Check(b.PlayerHP==hp-100,"normal damage restored");
 var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var v=c.view;var screens=v.frame.Find("Collection screens");if(screens!=null)screens.gameObject.SetActive(false);var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var rect=(RectTransform)canvas.transform;rect.position=Vector3.zero;rect.localScale=Vector3.one;rect.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/Hwaryong");
 for(int form=0;form<3;form++){c.BeginBattle(d,stats,Enemy(),1,false,10000,null,form==0?1:form*10,s);c.SendMessage("OnApplicationFocus",true);b=c.CurrentBattle;var fx=v.GetComponent<MirLegendaryVfx>();Check(fx.Configured,"configured");int count=0;b.Cue+=(cue,n)=>{if(b.ResolvingSkillHit){count++;Check(fx.HitsShown==count,"same frame VFX impact");}};var root=v.playerArt.transform.localPosition;Check(c.RequestSkill(),"cast");int objects=v.frame.GetComponentsInChildren<Transform>(true).Length;for(int f=0;f<165;f++){b.Tick(1f/30);v.StepAnimation(b,1f/30);v.Show(b);if(form==2)Capture(v,cam,rt,f);if(f==30)Check(!fx.ActorVisible,"actor hidden during manifestation");}Check(count==2&&fx.Clean&&fx.ActorVisible&&fx.Dropped==0,"two hits restoration no overflow");Check(Vector3.Distance(root,v.playerArt.transform.localPosition)<2,"player position restored");Check(objects==v.frame.GetComponentsInChildren<Transform>(true).Length,"no spawned object growth");Check(Time.timeScale==1,"global time scale untouched");Debug.Log("HWARYONG_FORM_OK "+form+" peak="+fx.Peak);c.EndBattle();}
 foreach(float phase in new[]{.3f,.6f,1.02f,1.8f,2.9f,3.7f,4.3f}){c.BeginBattle(d,stats,Enemy(),1,false,10000,null,20,s);c.RequestSkill();b=c.CurrentBattle;To(b,phase);v.StepAnimation(b,phase);var fx=v.GetComponent<MirLegendaryVfx>();c.EndBattle();Check(fx.Clean&&fx.ActorVisible&&!b.ProtectedSkillActive,"exit cleanup "+phase);}
 foreach(var terminal in new[]{BattleResult.Victory,BattleResult.Defeat}){c.BeginBattle(d,stats,Enemy(),1,false,10000,null,20,s);c.RequestSkill();b=c.CurrentBattle;To(b,.7);v.StepAnimation(b,.7f);typeof(BattleModel).GetProperty("Result").SetValue(b,terminal);v.StepAnimation(b,.01f);var fx=v.GetComponent<MirLegendaryVfx>();Check(fx.Clean&&fx.ActorVisible&&!b.ProtectedSkillActive,"terminal cleanup "+terminal);c.EndBattle();}
 foreach(int hpLimit in new[]{1,300}){c.BeginBattle(d,stats,Enemy(hpLimit),1,false,10000,null,20,s);c.RequestSkill();b=c.CurrentBattle;for(int f=0;f<150;f++){b.Tick(1f/30);v.StepAnimation(b,1f/30);}var fx=v.GetComponent<MirLegendaryVfx>();Check(b.Result==BattleResult.Victory&&fx.Clean&&fx.ActorVisible&&!b.ProtectedSkillActive,"lethal hit cleanup "+hpLimit);c.EndBattle();}
 c.BeginBattle(d,stats,Enemy(),1,false,10000,null,20,s);for(int cast=0;cast<3;cast++){b=c.CurrentBattle;b.SkillReady=0;Check(c.RequestSkill(),"repeat cast "+cast);for(int f=0;f<150;f++){b.Tick(1f/30);v.StepAnimation(b,1f/30);}Check(v.GetComponent<MirLegendaryVfx>().Clean,"repeat cleanup");}c.EndBattle();
 c.BeginBattle(d,stats,Enemy(),1,false,10000,null,20,s);c.RequestSkill();b=c.CurrentBattle;To(b,.7);v.StepAnimation(b,.7f);var fx2=v.GetComponent<MirLegendaryVfx>();fx2.enabled=false;Check(fx2.Clean&&fx2.ActorVisible&&!b.ProtectedSkillActive,"disable cleanup");fx2.enabled=true;c.EndBattle();cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);
 }
 static void Capture(BattleView v,Camera cam,RenderTexture rt,int f){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var t=new Texture2D(480,850,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,480,850),0,0);t.Apply();File.WriteAllBytes("Validation/Hwaryong/"+f.ToString("000")+".png",t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);RenderTexture.active=old;}
 }}
