using System;using System.IO;using System.Linq;using System.Reflection;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using UnityEditor;using UnityEditor.SceneManagement;
namespace DragonTower.Editor {
 [InitializeOnLoad] public static class ResultPresentationValidation {
 const string Flag="ResultPresentationValidation",Out="C:/Users/PC/Documents/Codex/Results-20261009/";static CollectionFlow flow;static BattleController controller;static int stage,scenario;static double started;static string settled;static string hud;
 static ResultPresentationValidation(){if(SessionState.GetBool(Flag,false))EditorApplication.update+=Tick;}
 public static void Run(){Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.Test.ResultPresentation");Directory.CreateDirectory(Out);SessionState.SetBool(Flag,true);EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");EditorApplication.EnterPlaymode();}
 static object Call(string n,params object[] a)=>typeof(CollectionFlow).GetMethod(n,BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public).Invoke(flow,a);
 static void Check(bool b,string s){if(!b)throw new Exception(s);}
 static void Capture(string n)=>typeof(AugmentPresentationValidation).GetMethod("Capture",BindingFlags.NonPublic|BindingFlags.Static).Invoke(null,new object[]{Out+n+".png"});
 static string Hud(){var v=controller.view;return string.Join("|",new[]{v.skillButton,v.itemButton1,v.itemButton2,v.itemButton3,v.RecoveryButton}.Select(b=>{var r=(RectTransform)b.transform;var im=b.targetGraphic;return r.anchoredPosition+"/"+r.sizeDelta+"/"+im.color+"/"+(im as Image)?.sprite?.name;}));}
 static void StartBattle(){var d=flow.Session.Selected;var r=new TowerRun(d.maxHP,0,1,d.elementType,d.alternateSkillElement,d.StableId,d);r.AttachInstance(flow.Session.Profile.selectedInstanceId);var s=r.Capture();s.Floor=scenario==1?10:1;s.Room=scenario==1?TowerRoomKind.Boss:scenario==2?TowerRoomKind.Gold:TowerRoomKind.Monster;s.RoomChosen=true;s.Phase=FloorPhase.CombatPending;s.AdditionalBattle=scenario==2;s.EncounterDecided=true;s.BattleExperiencePercent=100;r=TowerRun.Restore(s,ContentDatabase.Load());typeof(CollectionFlow).GetField("towerRun",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(flow,r);flow.Session.SaveRun(r);Call("StartCurrentBattle");hud=Hud();started=EditorApplication.timeSinceStartup;stage=1;}
 static void Tick(){try{if(!EditorApplication.isPlaying)return;if(flow==null){flow=UnityEngine.Object.FindFirstObjectByType<CollectionFlow>();if(flow?.Session==null){flow=null;return;}controller=UnityEngine.Object.FindFirstObjectByType<BattleController>();if(flow.Session.Selected==null)flow.Session.Hatch(0);StartBattle();return;}
 var b=controller.CurrentBattle;var v=controller.view;double t=EditorApplication.timeSinceStartup-started;
 if(stage==2){v.StepAnimation(b,.05f);v.Show(b);}
 if(stage==1&&t>.3){Check(!v.resultPanel.activeSelf,"overlay hidden in combat");Capture("hud-"+scenario);if(scenario<3){b.Dragon.attackDamage=1000000;b.Attack();}else{b.Enemy.damage=1000000;for(int i=0;i<500&&b.Result==BattleResult.Fighting;i++)b.Tick(.1f);}Check(b.Result==(scenario<3?BattleResult.Victory:BattleResult.Defeat),"actual battle completion");flow.BattleSettled();settled=JsonUtility.ToJson(flow.CurrentRun.Capture());stage=2;started=EditorApplication.timeSinceStartup;return;}
 if(stage==2&&t>1.5){if((!v.resultPanel.activeSelf||v.resultPanel.GetComponent<BattleResultPresentation>()?.Ready!=true)&&t<30)return;Check(v.resultPanel.activeSelf,"result shown after death");var p=v.resultPanel.GetComponent<BattleResultPresentation>();Check(p!=null&&p.Ready&&v.restartButton.interactable,"result action ready");Check(!controller.CanControl&&!controller.RequestAttack()&&!controller.RequestDodge(1),"combat blocked");Check(Hud()==hud,"HUD layout sprite color unchanged");flow.BattleSettled();Check(JsonUtility.ToJson(flow.CurrentRun.Capture())==settled,"settlement idempotent");Capture(scenario==3?"defeat":"victory-"+scenario);
 if(scenario==0||scenario==3){for(int f=0;f<30;f++){typeof(BattleResultPresentation).GetField("age",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(p,f/20f);typeof(BattleResultPresentation).GetMethod("Animate",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(p,null);Capture((scenario==0?"win-":"loss-")+f.ToString("D3"));}}
 p.Present(b,flow.CurrentRun,flow.CurrentRun.Progress.score);Check(!p.Ready&&!v.restartButton.interactable,"reveal gates action");p.OnPointerClick(new PointerEventData(EventSystem.current));Check(p.Ready&&controller.CurrentBattle==b,"tap completes only presentation");
 if(scenario==3){var preview=TowerRun.Restore(flow.CurrentRun.Capture(),ContentDatabase.Load());preview.Progress.customDragonName="가나다라마바사아자차카타";preview.Progress.score=int.MaxValue;p.Present(b,preview,0);p.OnPointerClick(new PointerEventData(EventSystem.current));Capture("long-name-large-score");}
 foreach(var text in v.resultPanel.GetComponentsInChildren<Text>()){float h=text.cachedTextGeneratorForLayout.GetPreferredHeight(text.text,text.GetGenerationSettings(text.rectTransform.rect.size))/text.pixelsPerUnit;Check(h<=text.rectTransform.rect.height+2,"text overflow "+text.text);}
 if(scenario<3){Check(flow.CurrentRun.BattleExperienceClaimed&&flow.CurrentRun.LastExperienceGain>0,"EXP settled");int floor=flow.CurrentRun.Floor;v.restartButton.onClick.Invoke();Check(!v.resultPanel.activeSelf,"result closed");Check(flow.CurrentRun.Floor==floor&&flow.CurrentRun.ExperiencePresentationPending,"reward flow before next floor");flow.ShowLobby();Check(flow.Session.HasSavedRun,"live run resumable");flow.ResumeRun();Check(flow.CurrentRun.ExperiencePresentationPending,"resume pending reward");flow.CurrentRun.AcknowledgeExperience();flow.CurrentRun.ConsumeDrop();flow.CurrentRun.CompleteBattleRewards();flow.CurrentRun.CompletePostBattleShop();Call("AdvanceFloor");Check(flow.CurrentRun.Floor==floor+1,"next floor after rewards");scenario++;StartBattle();return;}
 Check(!flow.Session.HasSavedRun&&!flow.CurrentRun.Active,"dead run cannot resume");v.restartButton.onClick.Invoke();Check(flow.ScreenName=="도전 종료","existing result destination");flow.ShowLobby();Check(!flow.Session.HasSavedRun,"death lobby no resume");Debug.Log("RESULT_PRESENTATION_OK normal boss additional death rewards idempotence save resume HUD controls portrait");SessionState.SetBool(Flag,false);EditorApplication.Exit(0);
 }
 }catch(Exception e){Debug.LogException(e);SessionState.SetBool(Flag,false);EditorApplication.Exit(1);}}
 }
}
