using System;using System.IO;using System.Linq;using System.Reflection;using UnityEngine;using UnityEngine.UI;using UnityEditor;using UnityEditor.SceneManagement;
namespace DragonTower.Editor {
[InitializeOnLoad] public static class RewardRoomValidation {
 const string Flag="RewardRoomValidation";public const string Out="C:/Users/PC/Documents/Codex/RewardRooms-20261009/";static CollectionFlow flow;static double started;static int stage;static TowerRun run;static string[] ids;static ContentDatabase db;
 static RewardRoomValidation(){if(SessionState.GetBool(Flag,false))EditorApplication.update+=Tick;}
 public static void Run(){Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.Test.RewardRooms");Directory.CreateDirectory(Out);SessionState.SetBool(Flag,true);EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");EditorApplication.EnterPlaymode();}
 static object Call(string n,params object[] a)=>typeof(CollectionFlow).GetMethod(n,BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public).Invoke(flow,a);
 static void Capture(string n)=>typeof(AugmentPresentationValidation).GetMethod("Capture",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{Out+n+".png"});
 static void Check(bool ok,string text){if(!ok)throw new Exception(text);}
 static TowerRun Create(int floor,params TowerRoomKind[] choices){var d=flow.Session.Selected;var r=new TowerRun(d.maxHP,0,1,d.elementType,d.alternateSkillElement,d.StableId,d);r.AttachInstance(flow.Session.Profile.selectedInstanceId);var saved=r.Capture();saved.Floor=floor;saved.choices=choices;return TowerRun.Restore(saved,db);}
 static void VerifyCardText(){
 run=Create(1,TowerRoomKind.Item,TowerRoomKind.Augment);run.BeginFloorRoom(0,18421);SetRun();Call("ShowItemChoices");
 foreach(var item in db.items.Where(x=>x!=null)){var card=(Button)Call("ItemChoice",item,320f);var text=card.transform.Find("Reward summary").GetComponent<Text>();var settings=text.GetGenerationSettings(text.rectTransform.rect.size);float h=text.cachedTextGeneratorForLayout.GetPreferredHeight(text.text,settings)/text.pixelsPerUnit;Check(h<=text.rectTransform.rect.height+1,"item description overflow: "+item.displayName+" height "+h);UnityEngine.Object.DestroyImmediate(card.gameObject);}
 Debug.Log("REWARD_ITEM_TEXT_OK "+db.items.Length+" descriptions");
 }
 static void VerifySavedChest(){
 var r=Create(6,TowerRoomKind.Item,TowerRoomKind.Gold);r.BeginFloorRoom(0,78431);var selected=db.PickItems(3,r.RewardSeed^r.Floor).Select(x=>x.StableId).ToArray();r.OpenChest(selected);r.OpenChest(new[]{"must-not-replace"});Check(r.ChestRewardIds.SequenceEqual(selected),"chest cannot reroll");var saved=r.Capture();var copy=TowerRun.Restore(JsonUtility.FromJson<TowerRunSave>(JsonUtility.ToJson(saved)),db);Check(copy.ChestOpened&&copy.ChestRewardIds.SequenceEqual(selected),"saved chest IDs");var config=FloorProgressionConfig.Load();Check(copy.CompleteRoomEvent(config,0,50),"reward claim once");int experience=copy.Experience;Check(!copy.CompleteRoomEvent(config,99,99)&&copy.Experience==experience,"no duplicate EXP");var resume=TowerRun.Restore(copy.Capture(),db);Check(resume.EncounterDecided&&resume.AdditionalBattle==copy.AdditionalBattle&&resume.BattleExperiencePercent==copy.BattleExperiencePercent,"encounter and multiplier not rerolled");copy=TowerRun.Restore(saved,db);copy.CompleteRoomEvent(config,100,50);copy.MoveToNextFloor(0,1);Check(!copy.ChestOpened&&copy.ChestRewardIds==null,"new floor resets chest");saved.ChestOpened=false;saved.ChestRewardIds=null;Check(!TowerRun.Restore(saved,db).ChestOpened,"old save compatible");Debug.Log("REWARD_ROOM_SAVE_OK");
 }
 static void Tick(){try{if(!EditorApplication.isPlaying)return;
 if(flow==null){flow=UnityEngine.Object.FindFirstObjectByType<CollectionFlow>();if(flow?.Session==null){flow=null;return;}if(flow.Session.Selected==null)flow.Session.Hatch(0);db=ContentDatabase.Load();VerifySavedChest();VerifyCardText();run=Create(9,TowerRoomKind.Item,TowerRoomKind.Augment);SetRun();Call("ShowTowerChoices");Capture("stairs-two-doors");flow.RoomButton.onClick.Invoke();int seed=run.RewardSeed;flow.SecondRoomButton.onClick.Invoke();Check(run.Room==TowerRoomKind.Item&&run.Floor==9&&run.RewardSeed==seed,"duplicate door input blocked");started=EditorApplication.timeSinceStartup;return;}
 double t=EditorApplication.timeSinceStartup-started;
 if(stage==0&&t>2){Check(flow.ScreenName=="아이템방","door transition destination");flow.RoomButton.onClick.Invoke();Call("ShowLobby");flow.ResumeRun();Check(flow.ScreenName=="아이템 선택"&&flow.CurrentRun.ChestOpened,"actual lobby resume after opening");Capture("resumed-rewards");var claimed=flow.CurrentRun;var selectedButton=flow.ChoiceButtons[0];selectedButton.onClick.Invoke();Check(claimed.RewardClaimed,"item click completes reward");int total=claimed.ItemSlots.Count+claimed.ItemCountAt(3);Check(total==1,"exactly one item granted");selectedButton.onClick.Invoke();Check(claimed.ItemSlots.Count+claimed.ItemCountAt(3)==total,"repeat click no duplicate item");Call("ShowLobby");flow.ResumeRun();Check(flow.CurrentRun.ItemSlots.Count+flow.CurrentRun.ItemCountAt(3)==total,"claimed item persisted on resume");run=Create(10,TowerRoomKind.Boss);SetRun();Call("ShowTowerChoices");Capture("stairs-boss-door");flow.RoomButton.onClick.Invoke();Call("ShowLobby");flow.ResumeRun();Check(flow.ScreenName=="보스 전투"&&flow.CurrentRun.Floor==10,"boss selection resume");
 run=Create(4,TowerRoomKind.Gold,TowerRoomKind.Monster);SetRun();Call("ShowTowerChoices");Capture("stairs-gold-monster");flow.RoomButton.onClick.Invoke();Call("ShowLobby");flow.ResumeRun();Check(flow.ScreenName=="골드방"&&flow.CurrentRun.Floor==4,"room selection interrupted resume");
 Debug.Log("REWARD_PHASE_C_OK door double input blocked unchanged floor chest actual lobby resume boss resume room selection resume item selection duplicate prevention");run=Create(5,TowerRoomKind.Augment,TowerRoomKind.Item);run.BeginFloorRoom(0,58421);SetRun();Call("ShowAugmentChoices",false);started=EditorApplication.timeSinceStartup;stage=1;return;}
 if(stage==1&&t>1.5){Check(flow.RewardsReady,"augment reveal completes");flow.ChoiceButtons[0].onClick.Invoke();var confirm=GameObject.Find("이 선택으로 성장");Check(confirm!=null,"detail confirmation");confirm.GetComponent<Button>().onClick.Invoke();Check(run.RewardClaimed,"augment selection commits");run=Create(5,TowerRoomKind.Augment,TowerRoomKind.Item);run.BeginFloorRoom(0,58422);SetRun();Call("ShowAugmentChoices",false);started=EditorApplication.timeSinceStartup;stage=2;return;}
 if(stage==2&&t>1.5){Check(flow.RewardsReady,"skip unlocked after reveal");flow.SecondRoomButton.onClick.Invoke();Check(run.RewardClaimed&&run.Augments.Count==0,"augment skip without grant");Debug.Log("REWARD_SELECTION_OK item grant resume duplicate click augment detail confirm skip");SessionState.SetBool(Flag,false);EditorApplication.Exit(0);stage=3;}
 }catch(Exception e){Debug.LogException(e);SessionState.SetBool(Flag,false);EditorApplication.Exit(1);}}
 static void SetRun()=>typeof(CollectionFlow).GetField("towerRun",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(flow,run);
}}
