using System;using System.IO;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.UI;
namespace DragonTower.Editor {
 public static class SolarPierceValidation {
  static int wait;
  public static void Run(){SolarPierceSetup.Install();Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.Solar.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetBool("SolarCheck",true);EditorApplication.isPlaying=true;}
  [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("SolarCheck",false)){wait=0;EditorApplication.update+=After;}};}
  static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("SolarCheck",false);try{Test();Debug.Log("SOLAR_VALIDATION_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
  static void Check(bool b,string m){if(!b)throw new Exception("SOLAR_FAIL "+m);Debug.Log("SOLAR_CHECK "+m);}
  static BattleStats Stats(DragonData d,SkillData s){var st=d.Snapshot(20);st.skill=s.Snapshot();st.criticalChance=0;st.passiveMechanic=DragonPassiveMechanic.None;return st;}
  static BattleEnemyStats Enemy(int hp=99999){var e=BattleEnemyStats.Normal();e.maxHP=hp;e.interval=100;return e;}
  static void Test(){var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon8.asset");var ember=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon0.asset");var s=AssetDatabase.LoadAssetAtPath<SkillData>(SolarPierceSetup.SkillPath);Check(d.signatureSkill==s&&d.CanOfferSkill(s)&&!ember.CanOfferSkill(s),"Sol exclusive signature");Check(d.elementSkillPool==null||!d.elementSkillPool.Contains(s),"excluded from shared Fire pool");Check(!new BattleModel(Stats(ember,s),Enemy()).Skill(),"Ember cannot cast");
   var stats=Stats(d,s);int heal=(int)Math.Ceiling(stats.maxHP*20/100f);var m=new BattleModel(stats,Enemy(),10);int healEvents=0;m.Healed+=x=>healEvents++;m.Skill();m.Tick(1.8f);Check(m.PlayerHP==10,"no early heal");m.Tick(.3f);Check(m.PlayerHP==10+heal&&healEvents==1,"one maximum-HP 20 percent heal after final impact");m.Tick(2);Check(healEvents==1,"no duplicate recovery");
   m=new BattleModel(stats,Enemy(),stats.maxHP-1);m.Skill();m.Tick(3);Check(m.PlayerHP==stats.maxHP,"max HP cap");m=new BattleModel(stats,Enemy(1),10);m.Skill();m.Tick(4);Check(m.PlayerHP==10&&!m.CompletionHealPending,"early target death cancels recovery");
   int total=s.damage*(s.hitCount-1)+(int)(s.damage*s.finalHitDamageMultiplier);m=new BattleModel(stats,Enemy(total),10);m.Skill();m.Tick(4);Check(m.Result==BattleResult.Victory&&m.PlayerHP==10+heal,"lethal final hit completes recovery once");
   m=new BattleModel(stats,Enemy(),10);m.Skill();m.Tick(1.9f);m.CancelCompletionHeal();m.Tick(4);Check(m.PlayerHP==10,"scene cancellation prevents queued healing");
   var deadly=Enemy();deadly.damage=1000;deadly.interval=1.95f;m=new BattleModel(stats,deadly,10);m.Skill();m.Tick(4);Check(m.Result==BattleResult.Defeat&&m.PlayerHP==0,"death before return prevents resurrection");
   var dbl=Stats(d,s);dbl.augments=new[]{new BattleAugment{mechanic=AugmentMechanic.DoubleCasting}};m=new BattleModel(dbl,Enemy(),10);int healed=0;m.Healed+=x=>healed++;m.Skill();m.Tick(6);Check(healed==1&&m.PlayerHP==10+heal,"DoubleCasting completion heals once per use");
   var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var v=c.view;var screens=v.frame.Find("Collection screens");if(screens!=null)screens.gameObject.SetActive(false);var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var rect=(RectTransform)canvas.transform;rect.position=Vector3.zero;rect.localScale=Vector3.one;rect.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/Solar");
   for(int stage=0;stage<3;stage++){c.BeginBattle(d,stats,Enemy(),1,false,10,null,stage==0?1:stage*10,s);c.SendMessage("OnApplicationFocus",true);var b=c.CurrentBattle;var fx=v.GetComponent<SolarPierceVfx>();int count=0,damage=0,heals=0;int objects=v.frame.GetComponentsInChildren<Transform>(true).Length;b.Cue+=(cue,value)=>{if((cue==CombatCue.Skill||cue==CombatCue.SkillHit)&&b.ResolvingSkillHit){Check(Math.Abs(b.Time-s.initialHitDelay-count*s.hitInterval)<.034,"contact timing "+count);count++;damage+=value;Check(fx.HitsShown==count,"same-frame impact");}if(cue==CombatCue.SkillHeal)heals++;};Check(c.RequestSkill()&&!c.RequestSkill(),"cooldown gate");for(int f=0;f<115;f++){b.Tick(1f/30);v.StepAnimation(b,1f/30);v.Show(b);if(stage==2||f==43||f==58)Capture(v,cam,rt,"sol-"+stage+"-"+f.ToString("000"));}Check(count==6&&damage==total,"six hits exact damage");Check(heals==1&&b.PlayerHP==10+heal,"visual recovery matches HP event");Check(fx.Clean&&fx.DroppedLayers==0,"pool budget and cleanup");Check(objects==v.frame.GetComponentsInChildren<Transform>(true).Length,"no per-cast objects");Check(v.skillButton.transform.Find("Equipped skill name").GetComponent<Text>().text==s.displayName,"HUD reads skill data");Debug.Log("SOLAR_FORM_OK "+stage+" damage="+damage+" heal="+heal+" peak="+fx.PeakImages);c.EndBattle();}
   for(int i=0;i<3;i++){c.BeginBattle(d,stats,Enemy(),1,false,10,null,20,s);c.RequestSkill();c.CurrentBattle.Tick(.8f);v.StepAnimation(c.CurrentBattle,.8f);c.EndBattle();Check(v.GetComponent<SolarPierceVfx>().Clean,"mid-cast exit cleanup "+i);}cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);
  }
  static void Capture(BattleView v,Camera cam,RenderTexture rt,string name){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(480,850,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,480,850),0,0);tex.Apply();File.WriteAllBytes("Validation/Solar/"+name+".png",tex.EncodeToPNG());UnityEngine.Object.DestroyImmediate(tex);RenderTexture.active=old;}
 }
}

