using System;using System.IO;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.UI;
namespace DragonTower.Editor {
 public static class TimeClockworkValidation {
  static int wait;static void Check(bool b,string label){if(!b)throw new Exception("TIME_CLOCKWORK_FAIL "+label);Debug.Log("TIME_CHECK "+label);}
  public static void Run(){TimeClockworkSetup.Install();Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.TimeClockwork.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetBool("TimeClockworkCheck",true);EditorApplication.isPlaying=true;}
  [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("TimeClockworkCheck",false)){wait=0;EditorApplication.update+=After;}};}
  static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("TimeClockworkCheck",false);try{Rules();Regression();Visual();Debug.Log("TIME_CLOCKWORK_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
  static SkillData Data=>AssetDatabase.LoadAssetAtPath<SkillData>(TimeClockworkSetup.SkillPath);
  static BattleStats Stats(){var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon15.asset");var s=d.Snapshot(20);s.skill=Data.Snapshot();s.passiveMechanic=DragonPassiveMechanic.None;s.criticalChance=100;s.criticalDamage=1.5f;s.attackDamage=20;s.augments=Array.Empty<BattleAugment>();s.items=Array.Empty<BattleItem>();return s;}
  static BattleEnemyStats Enemy(){var e=BattleEnemyStats.Normal();e.maxHP=20000;e.damage=0;return e;}
  static void Rules(){var s=Stats();var b=new BattleModel(s,Enemy(),s.maxHP);int releases=0,total=0;double start=-1,finish=-1;b.Cue+=(cue,d)=>{if(cue==CombatCue.TimeStopped)start=b.Time;if(cue==CombatCue.TimeReleased){finish=b.Time;releases++;total=d;}};
   Check(b.Skill(),"cast");b.Tick(s.skill.timeDomainDelay);Check(b.EnemyTimeStopped,"starts after domain opens");double remaining=b.NextEnemyStrike-b.Time;for(int i=0;i<10;i++){Check(b.Attack(),"basic accepted during stop");b.Tick(.31f);}Check(b.StoredBasicDamage==300&&b.StoredBasicHits==10,"critical final basic damage stored exactly");Check(b.EnemyHP==20000,"stored basics do not reduce HP");Check(Math.Abs(b.NextEnemyStrike-b.Time-remaining)<1e-5,"enemy attack countdown frozen");b.SkillReady=0;Check(!b.Skill(),"recast blocked despite ready cooldown");Check(b.Dodge(),"dodge available");b.Tick((float)b.TimeDomainRemaining-.001f);Check(b.EnemyTimeStopped&&releases==0,"before exact boundary");b.Tick(.0011f);Check(releases==1&&total==540&&b.EnemyHP==19460,"skill 240 plus stored 300 released once without recalculation");Check(Math.Abs(finish-start-5)<.00001,"exact five seconds");Check(!b.EnemyTimeStopped&&b.StoredBasicDamage==0,"state cleared");b.Tick(.2f);Check(releases==1,"no duplicate release");int hp=b.EnemyHP;b.Attack();Check(b.EnemyHP==hp-30,"normal attack HP resumes");
   s=Stats();s.augments=new[]{new BattleAugment{mechanic=AugmentMechanic.Spread,primaryValue=50}};b=new BattleModel(s,Enemy(),s.maxHP);b.Skill();b.Tick(.24f);b.Attack();Check(b.StoredBasicDamage==30&&b.EnemyHP==19985,"extra damage immediate, excluded from storage");var burn=typeof(BattleModel).GetMethod("ApplyBurn",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance);burn.Invoke(b,new object[]{2f,7});b.Tick(1);Check(b.StoredBasicDamage==30&&b.EnemyHP==19978,"status damage not stored");b.CancelTimeDomain();b.Tick(6);Check(b.LastTimeRelease==0&&b.StoredBasicDamage==0&&!b.EnemyTimeStopped,"cancel does not release");
   s=Stats();var immune=Enemy();immune.timeStopImmune=true;b=new BattleModel(s,immune,s.maxHP);b.Skill();b.Tick(.25f);Check(!b.EnemyTimeStopped&&b.LastTimeRelease==240,"optional immunity retains signature damage");var resistant=Enemy();resistant.timeStopDurationMultiplier=.5f;b=new BattleModel(s,resistant,s.maxHP);b.Skill();b.Tick(.24f);Check(Math.Abs(b.TimeDomainRemaining-2.5)<.00001,"optional duration multiplier without boss rebalance");b.Tick(3);Check(!b.TimeDomainBusy,"large delta resolves boundary");
   s=Stats();b=new BattleModel(s,Enemy(),s.maxHP);b.Skill();b.Tick(.24f);typeof(BattleModel).GetField("playerParalyzeUntil",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).SetValue(b,100d);typeof(BattleModel).GetField("random",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).SetValue(b,(Func<double>)(()=>0));b.Attack();Check(b.StoredBasicDamage==0&&b.StoredBasicHits==0,"missed basic not stored");var hit=typeof(BattleModel).GetMethod("Hit",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance);hit.Invoke(b,new object[]{40,ElementType.Light,true,false,false});Check(b.StoredBasicDamage==0&&b.EnemyHP<20000,"other skill hit not stored");b.CancelTimeDomain();
   var dante=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon7.asset");Check(!Data.CanEquip(dante.speciesId),"signature exclusive");s=Stats();var lethal=Enemy();lethal.damage=999;lethal.interval=.1f;b=new BattleModel(s,lethal,1);b.Skill();b.Tick(.15f);Check(b.Result==BattleResult.Defeat&&!b.TimeDomainBusy&&b.StoredBasicDamage==0,"caster death cleanup");
   s=Stats();s.augments=new[]{new BattleAugment{mechanic=AugmentMechanic.Spread,primaryValue=100}};lethal=Enemy();lethal.maxHP=1;b=new BattleModel(s,lethal,s.maxHP);b.Skill();b.Tick(.24f);b.Attack();b.Tick(.01f);Check(b.Result==BattleResult.Victory&&!b.TimeDomainBusy&&b.StoredBasicDamage==0,"target death cleanup");
  }
  static void Regression(){var enemy=Enemy();enemy.interval=100;foreach(string path in LightBatchSetup.Paths){var s=Stats();s.skill=AssetDatabase.LoadAssetAtPath<SkillData>(path).Snapshot();s.criticalChance=0;var b=new BattleModel(s,enemy,s.maxHP);int hits=0;b.Cue+=(cue,d)=>{if(cue==CombatCue.Skill||cue==CombatCue.SkillHit)hits++;};b.Skill();b.Tick(2);Check(hits==s.skill.hitCount&&b.EnemyHP==enemy.maxHP-s.skill.damage*s.skill.hitCount,"shared Light damage regression "+path);}
   var bolt=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon4.asset");var stats=bolt.Snapshot(20);stats.skill=bolt.signatureSkill.Snapshot();stats.passiveMechanic=DragonPassiveMechanic.None;stats.criticalChance=0;var empowered=new BattleModel(stats,enemy,stats.maxHP);int extras=0;empowered.Cue+=(cue,d)=>{if(cue==CombatCue.EmpoweredAttackHit)extras++;};empowered.Skill();empowered.Tick(.25f);for(int i=0;i<10;i++){empowered.Attack();empowered.Tick(.31f);}Check(extras==10&&empowered.StoredBasicDamage==0,"Bolt additional hits unchanged");
  }
  static void Visual(){var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var v=c.view;var screens=v.frame.Find("Collection screens");if(screens!=null)screens.gameObject.SetActive(false);var dragon=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon15.asset");var stats=Stats();stats.criticalChance=0;var enemy=Enemy();enemy.damage=8;c.BeginBattle(dragon,stats,enemy,1,false,stats.maxHP,null,20,Data);c.SendMessage("OnApplicationFocus",true);var b=c.CurrentBattle;var fx=v.GetComponent<TimeClockworkVfx>();
   var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var rect=(RectTransform)canvas.transform;rect.position=Vector3.zero;rect.localScale=Vector3.one;rect.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/TimeClockwork");
   Check(c.RequestSkill(),"visual cast");Vector2 frozen=Vector2.zero;Vector3 frozenScale=Vector3.zero;bool captured=false;int releaseCount=0;b.Cue+=(cue,d)=>{if(cue==CombatCue.TimeReleased)releaseCount++;};
   for(int f=0;f<255;f++){b.Tick(1f/30);if(f>9&&f%10==0&&f<155)c.RequestAttack();if(f==80)c.RequestDodge(1);v.StepAnimation(b,1f/30);v.Show(b);if(b.EnemyTimeStopped){if(!captured){frozen=v.enemyArt.rectTransform.anchoredPosition;frozenScale=v.enemyArt.rectTransform.localScale;captured=true;}Check(v.enemyArt.rectTransform.anchoredPosition==frozen&&v.enemyArt.rectTransform.localScale==frozenScale,"enemy pose frozen");Check(b.EnemyHP==20000,"visual phase HP preserved");}Capture(v,cam,rt,f);}
   Check(releaseCount==1&&b.LastTimeRelease>Data.damage,"one accumulated impact");Check(fx.Dropped==0,"no mesh overflow");Check(Time.timeScale==1,"global time untouched");Debug.Log("TIME_VISUAL peak="+fx.Peak+" release="+b.LastTimeRelease+" imprints="+fx.Imprints);b.Tick(30);c.RequestSkill();v.StepAnimation(b,.3f);c.EndBattle();Check(fx.Clean&&!b.TimeDomainBusy,"battle exit restores visuals and state");cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);
  }
  static void Capture(BattleView v,Camera cam,RenderTexture rt,int f){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var t=new Texture2D(480,850,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,480,850),0,0);t.Apply();File.WriteAllBytes("Validation/TimeClockwork/"+f.ToString("000")+".png",t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);RenderTexture.active=old;}
  public static void BuildWeb(){TimeClockworkSetup.Install();var report=BuildPipeline.BuildPlayer(new[]{"Assets/Scenes/Battle.unity"},"../TimeClockwork-WebGL",BuildTarget.WebGL,BuildOptions.None);if(report.summary.result!=UnityEditor.Build.Reporting.BuildResult.Succeeded)throw new Exception("Time WebGL failed");Debug.Log("TIME_WEBGL_OK");}
 }
}
