using System;using System.IO;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.UI;
namespace DragonTower.Editor {
 public static class VolcanicMeteorValidation {
  static int wait;
  public static void Run(){VolcanicMeteorSetup.Install();Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.Volcanic.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetBool("VolcanicCheck",true);EditorApplication.isPlaying=true;}
  [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("VolcanicCheck",false)){wait=0;EditorApplication.update+=After;}};}
  static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("VolcanicCheck",false);try{Test();Debug.Log("VOLCANIC_VALIDATION_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
  static void Check(bool b,string m){if(!b)throw new Exception("VOLCANIC_FAIL "+m);Debug.Log("VOLCANIC_CHECK "+m);}
  static BattleStats Stats(DragonData d,SkillData s){var st=d.Snapshot(20);st.skill=s.Snapshot();st.criticalChance=0;st.passiveMechanic=DragonPassiveMechanic.None;return st;}
  static BattleEnemyStats Enemy(int hp=99999){var e=BattleEnemyStats.Normal();e.maxHP=hp;e.interval=100;return e;}
  static void Test(){var d=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon0.asset");var sol=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon8.asset");var s=AssetDatabase.LoadAssetAtPath<SkillData>(VolcanicMeteorSetup.SkillPath);Check(d.signatureSkill==s&&d.CanOfferSkill(s)&&!sol.CanOfferSkill(s),"Ember exclusive signature");Check(d.elementSkillPool==null||!d.elementSkillPool.Contains(s),"excluded from shared Fire pool");Check(!new BattleModel(Stats(sol,s),Enemy()).Skill(),"Sol cannot cast");var stats=Stats(d,s);stats.criticalChance=.1f;var m=new BattleModel(stats,Enemy(),stats.maxHP,()=>.55);double start=-1;int n=0;m.Cue+=(cue,damage)=>{if(m.ResolvingSkillHit){n++;if(n==6){start=m.Time;Check(m.EnemyBurning&&Math.Abs(m.EnemyBurnRemaining-5)<.00001,"Burn exactly five seconds at final contact");Check(Math.Abs(m.TargetCriticalRemaining-5)<.00001&&Math.Abs(m.EffectiveCriticalChancePercent-60)<.001,"10 percent plus 50 points equals 60");}}};m.Skill();m.Tick(1.7f);Check(!m.EnemyBurning&&m.TargetCriticalRemaining==0,"no early burst window");m.Tick(.4f);Check(n==6&&start>0,"all scheduled contacts");int before=m.EnemyHP;m.Attack();Check(before-m.EnemyHP==(int)Math.Round(stats.attackDamage*stats.criticalDamage,MidpointRounding.AwayFromZero),"normal attacks use temporary crit chance");m.Tick((float)(start+4.99-m.Time));Check(m.TargetCriticalRemaining>0&&m.EnemyBurning,"active at expiry minus 10 ms");m.Tick(.02f);Check(m.TargetCriticalRemaining==0&&!m.EnemyBurning&&Math.Abs(m.EffectiveCriticalChancePercent-10)<.001,"both expire together without persistent crit");
   var capped=Stats(d,s);capped.criticalChance=.8f;var cap=new BattleModel(capped,Enemy(),capped.maxHP,()=>.99);cap.Skill();cap.Tick(2.2f);Check(cap.EffectiveCriticalChancePercent==100,"existing 100 percent cap");
   var stacked=Stats(d,s);stacked.criticalChance=.1f;stacked.augments=new[]{new BattleAugment{mechanic=AugmentMechanic.Inferno,primaryValue=50}};var st=new BattleModel(stacked,Enemy());st.Skill();st.Tick(2.2f);Check(st.EffectiveCriticalChancePercent==100,"existing Inferno additive source preserved");st.CancelTargetModifier();Check(st.TargetCriticalRemaining==0&&st.EffectiveCriticalChancePercent==60,"cancelling signature preserves other crit source");
   var killed=new BattleModel(Stats(d,s),Enemy(1));killed.Skill();killed.Tick(4);Check(killed.Result==BattleResult.Victory&&killed.TargetCriticalRemaining==0,"early target death cannot grant next-target bonus");var next=new BattleModel(Stats(d,s),Enemy());Check(next.TargetCriticalBonus==0,"new target isolated");
   var cancelled=new BattleModel(Stats(d,s),Enemy());cancelled.Skill();cancelled.Tick(.8f);int hp=cancelled.EnemyHP;cancelled.CancelTargetModifier();cancelled.Tick(5);Check(cancelled.EnemyHP==hp&&!cancelled.EnemyBurning,"cancel stops pending impacts and statuses");
   var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var v=c.view;var screens=v.frame.Find("Collection screens");if(screens!=null)screens.gameObject.SetActive(false);var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var rect=(RectTransform)canvas.transform;rect.position=Vector3.zero;rect.localScale=Vector3.one;rect.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/Volcanic");
   stats=Stats(d,s);for(int stage=0;stage<3;stage++){c.BeginBattle(d,stats,Enemy(),1,false,stats.maxHP,null,stage==0?1:stage*10,s);c.SendMessage("OnApplicationFocus",true);var b=c.CurrentBattle;var fx=v.GetComponent<VolcanicMeteorVfx>();int count=0,damage=0;int objects=v.frame.GetComponentsInChildren<Transform>(true).Length;b.Cue+=(cue,value)=>{if(b.ResolvingSkillHit){Check(Math.Abs(b.Time-s.hitTimeOffsets[count])<.034,"contact timing "+count);count++;damage+=value;Check(fx.HitsShown==count,"same-frame visual contact");}};Check(c.RequestSkill()&&!c.RequestSkill(),"cooldown gate");for(int f=0;f<250;f++){b.Tick(1f/30);v.StepAnimation(b,1f/30);v.Show(b);if(stage==2||f==58||f==69)Capture(v,cam,rt,"ember-"+stage+"-"+f.ToString("000"));}Check(count==6&&damage==273,"six contacts exact base damage");Check(fx.Clean&&fx.DroppedLayers==0,"complete expiry and pool headroom");Check(objects==v.frame.GetComponentsInChildren<Transform>(true).Length,"no per-cast object growth");Check(v.skillButton.transform.Find("Equipped skill name").GetComponent<Text>().text==s.displayName,"HUD reads skill name");Debug.Log("VOLCANIC_FORM_OK "+stage+" damage="+damage+" peak="+fx.PeakImages+" origin="+fx.LastOrigin);c.EndBattle();}
   for(int i=0;i<3;i++){c.BeginBattle(d,stats,Enemy(),1,false,stats.maxHP,null,20,s);c.RequestSkill();c.CurrentBattle.Tick(i==2?2.2f:.8f);v.StepAnimation(c.CurrentBattle,i==2?2.2f:.8f);c.EndBattle();Check(v.GetComponent<VolcanicMeteorVfx>().Clean,"scene exit cleanup "+i);}cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);
  }
  static void Capture(BattleView v,Camera cam,RenderTexture rt,string name){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(480,850,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,480,850),0,0);tex.Apply();File.WriteAllBytes("Validation/Volcanic/"+name+".png",tex.EncodeToPNG());UnityEngine.Object.DestroyImmediate(tex);RenderTexture.active=old;}
 }
}
