using System;using System.IO;using System.Linq;using UnityEditor;using UnityEngine;
namespace DragonTower.Editor {
 public static class VolcanicMeteorSetup {
  public const string Folder="Assets/Resources/VFX/VolcanicMeteor",SkillPath="Assets/Data/Skills/skill_volcanic_meteor.asset";
  public static void Install(){GenerateArt();var s=AssetDatabase.LoadAssetAtPath<SkillData>(SkillPath);if(s==null){s=ScriptableObject.CreateInstance<SkillData>();AssetDatabase.CreateAsset(s,SkillPath);}var ember=AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon0.asset");s.skillId="skill_volcanic_meteor";s.displayName="유성 화산";s.description="엠버 전용 · 유성 폭격과 화산 분화. 최종 적중 후 5초 확정 화상, 현재 적에게 치명타 확률 +50%p.";s.exclusiveDragonId=ember.StableId;s.elementType=ElementType.Fire;s.effectKind=SkillEffectKind.Fire;s.rarity=ContentRarity.Legendary;s.volcanicPresentation=true;s.damage=21;s.cooldown=17;s.hitCount=6;s.initialHitDelay=.43f;s.hitInterval=.3f;s.hitTimeOffsets=new[]{.43f,.66f,.98f,1.18f,1.47f,2.05f};s.finalHitDamageMultiplier=8;s.statusOnFinalHit=true;s.statusOnHit=false;s.statusEffect=CombatStatusEffect.Burn;s.statusChancePercent=100;s.statusDuration=5;s.statusPower=9;s.targetCriticalBonus=50;s.targetCriticalDuration=5;s.vfxDuration=3.55f;s.icon=AssetDatabase.LoadAllAssetsAtPath(Folder+"/VolcanicAtlas.png").OfType<Sprite>().First(x=>x.name=="Volcanic5_0");ember.signatureSkill=s;EditorUtility.SetDirty(s);EditorUtility.SetDirty(ember);var db=AssetDatabase.LoadAssetAtPath<ContentDatabase>("Assets/Resources/ContentDatabase.asset");if(!db.skills.Contains(s)){db.skills=db.skills.Concat(new[]{s}).ToArray();EditorUtility.SetDirty(db);}AssetDatabase.SaveAssets();Debug.Log("VOLCANIC_INSTALLED "+ember.StableId);}
  public static void GenerateArt(){Directory.CreateDirectory(Folder);AssetDatabase.Refresh();const int n=128,w=1024,h=768;var tex=new Texture2D(w,h,TextureFormat.RGBA32,false);var pixels=new Color[w*h];for(int row=0;row<6;row++)for(int f=0;f<8;f++)for(int y=0;y<n;y++)for(int x=0;x<n;x++)pixels[(row*n+y)*w+f*n+x]=Pixel(row,f,x,y);tex.SetPixels(pixels);tex.Apply();File.WriteAllBytes(Folder+"/VolcanicAtlas.png",tex.EncodeToPNG());UnityEngine.Object.DestroyImmediate(tex);AssetDatabase.Refresh();var im=(TextureImporter)AssetImporter.GetAtPath(Folder+"/VolcanicAtlas.png");im.textureType=TextureImporterType.Sprite;im.spriteImportMode=SpriteImportMode.Multiple;im.filterMode=FilterMode.Point;im.mipmapEnabled=false;im.alphaIsTransparency=true;im.textureCompression=TextureImporterCompression.Uncompressed;im.npotScale=TextureImporterNPOTScale.None;im.spritePixelsPerUnit=100;im.maxTextureSize=1024;var slices=new SpriteMetaData[48];for(int row=0;row<6;row++)for(int f=0;f<8;f++)slices[row*8+f]=new SpriteMetaData{name="Volcanic"+row+"_"+f,rect=new Rect(f*n,row*n,n,n),pivot=Vector2.one*.5f,alignment=0};
#pragma warning disable 618
 im.spritesheet=slices;
#pragma warning restore 618
 im.SaveAndReimport();}
  static Color Lava(float v){return v<.18f?new Color(1,1,.88f):v<.38f?new Color(1,.85f,.25f):v<.63f?new Color(1,.37f,.025f):new Color(.68f,.055f,.025f);}
  static Color Pixel(int row,int f,int x,int y){float px=(x-63.5f)/60,py=(y-63.5f)/60,r=Mathf.Sqrt(px*px+py*py),a=Mathf.Atan2(py,px),t=f*Mathf.PI/4;
   if(row==4){if(r>.7f+.12f*Mathf.Sin(a*5))return Color.clear;float seam=Mathf.Abs(px*.7f+py*.5f-.1f);if(seam<.10f)return Lava(seam*8);return px+py>.1f?new Color(.29f,.13f,.085f):new Color(.09f,.055f,.065f);}if(row<2){float edge=.82f+.065f*Mathf.Sin(a*7)+.035f*Mathf.Cos(a*11);if(r>edge)return Color.clear;float z=Mathf.Sqrt(Mathf.Max(0,1-r*r/(edge*edge)));float longitude=Mathf.Atan2(px,z)+t*.14f;float c1=Mathf.Abs(Mathf.Sin(longitude*8+py*4+Mathf.Sin(py*9)*.8f)),c2=Mathf.Abs(Mathf.Sin(py*10-longitude*3+Mathf.Sin(longitude*7)*.7f));float crack=Mathf.Min(c1,c2);float veins=.10f+.035f*Mathf.Sin(t+py*6);if(row==1){if(crack>veins)return Color.clear;var c=Lava(crack/veins);c.a=.7f+.3f*z;return c;}if(crack<veins)return Lava(crack/veins);float light=Mathf.Clamp01(z*.6f-px*.22f+py*.35f);float facet=Mathf.Floor((light+.08f*Mathf.Sin(px*31+py*17))*5)/5;return Color.Lerp(new Color(.055f,.035f,.043f),new Color(.32f,.18f,.13f),Mathf.Clamp01(facet));}
   if(row==2){float min=3;for(int i=0;i<7;i++){float angle=i*.898f,along=px*Mathf.Cos(angle)+py*Mathf.Sin(angle),across=-px*Mathf.Sin(angle)+py*Mathf.Cos(angle);if(along>0&&along<.94f)min=Mathf.Min(min,Mathf.Abs(across-(Mathf.Sin(along*15+i)+Mathf.Sin(along*27-i))*.025f));}float width=.016f+f*.004f;if(min>width||r>1)return Color.clear;var c=Lava(min/width);c.a=Mathf.Clamp01((1-r)*5);return c;}
   if(row==3){float u=(py+1)*.5f;float bend=Mathf.Sin(u*9-t)*.12f;float width=(1-u)*(.65f+.13f*Mathf.Sin(u*16-t*2));float q=Mathf.Abs(px-bend)/Mathf.Max(.001f,width);if(q>1||u<0||u>1)return Color.clear;var c=Lava(q*.9f+u*.17f);c.a=Mathf.Clamp01((1-u)*5);return c;}
   if(row==5){if(r>1)return Color.clear;if(r>.92f)return new Color(1,.32f,.035f);float rock=Vector2.Distance(new Vector2(px,py),new Vector2(.1f,.22f));if(rock<.4f){float crack=Mathf.Min(Mathf.Abs(px-.1f+py*.4f),Mathf.Abs(py-.15f-px*.3f));return crack<.055f?Lava(crack*8):new Color(.15f,.08f,.075f);}if(py>.2f&&Mathf.Abs(px-py*.55f)<.16f)return Lava(Mathf.Abs(px-py*.55f)*4);if(py<-.25f&&py>-.75f&&Mathf.Abs(px)<.7f+py*.45f)return Lava(Mathf.Abs(py+.38f)*3);return new Color(.06f,.025f,.03f);}
   return Color.clear;
  }
 }
}
