using System;using System.IO;using System.Collections.Generic;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.UI;
namespace DragonTower.Editor {
 public static class WaterBatchValidation {
  static int wait;public static void Aqua()=>Run(0);public static void Surge()=>Run(1);public static void Snipe()=>Run(2);public static void Splash()=>Run(3);
  public static void Final()=>Run(3,true);
  static void Run(int n,bool all=false){WaterBatchSetup.Install(n);SessionState.SetBool("WaterAll",all);Environment.SetEnvironmentVariable("DRAGON_TOWER_TEST_SAVE","DragonTower.WaterBatch.Validation");EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");SessionState.SetInt("WaterThrough",n);SessionState.SetBool("WaterBatchCheck",true);EditorApplication.isPlaying=true;}
  [InitializeOnLoadMethod]static void Listen(){EditorApplication.playModeStateChanged+=s=>{if(s==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("WaterBatchCheck",false)){wait=0;EditorApplication.update+=After;}};}
  static void After(){if(++wait<12)return;EditorApplication.update-=After;SessionState.SetBool("WaterBatchCheck",false);try{Test();Debug.Log("WATER_BATCH_OK");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
  static void Check(bool b,string label){if(!b)throw new Exception("WATER_BATCH_FAIL "+label);Debug.Log("WATER_CHECK "+label);}
  static void Test(){var c=UnityEngine.Object.FindFirstObjectByType<BattleController>();c.enabled=false;var v=c.view;var screens=v.frame.Find("Collection screens");if(screens!=null)screens.gameObject.SetActive(false);
   var cam=UnityEngine.Object.FindFirstObjectByType<Camera>();var rt=new RenderTexture(480,850,24);rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=425;cam.transform.position=new Vector3(0,0,-10);cam.transform.rotation=Quaternion.identity;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.cullingMask=-1;var canvas=v.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=cam;var rect=(RectTransform)canvas.transform;rect.position=Vector3.zero;rect.localScale=Vector3.one;rect.sizeDelta=new Vector2(480,850);ShaderUtil.allowAsyncCompilation=false;Directory.CreateDirectory("Validation/WaterBatch");
   int s=SessionState.GetInt("WaterThrough",0);
   for(int k=SessionState.GetBool("WaterAll",false)?0:s;k<=SessionState.GetInt("WaterThrough",0);k++)for(int d=0;d<2;d++){s=k;var dragon=AssetDatabase.LoadAssetAtPath<DragonData>(d==0?"Assets/Data/Dragon13.asset":"Assets/Data/Dragon5.asset");var data=AssetDatabase.LoadAssetAtPath<SkillData>(WaterBatchSetup.Paths[s]);var stats=dragon.Snapshot(20);stats.skill=data.Snapshot();stats.criticalChance=0;stats.passiveMechanic=DragonPassiveMechanic.None;var enemy=BattleEnemyStats.Normal();enemy.maxHP=99999;enemy.interval=100;c.BeginBattle(dragon,stats,enemy,1,false,stats.maxHP,null,20,data);c.SendMessage("OnApplicationFocus",true);var b=c.CurrentBattle;var fx=v.GetComponent<WaterSkillVfx>();Check(fx.Configured,"presentation configured");var times=new List<double>();int damageSum=0;var mirror=new BattleModel(stats,enemy,stats.maxHP);int objects=v.frame.GetComponentsInChildren<Transform>(true).Length;var randomField=typeof(BattleModel).GetField("random",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);randomField.SetValue(b,(Func<double>)(()=>0.1));randomField.SetValue(mirror,(Func<double>)(()=>0.1));
    b.Cue+=(cue,damage)=>{if((cue==CombatCue.Skill||cue==CombatCue.SkillHit)&&b.ResolvingSkillHit){times.Add(b.Time);damageSum+=damage;Check(fx.HitsShown==times.Count,"impact and real cue same frame");}};
    var rng=UnityEngine.Random.state;Check(c.RequestSkill(),"cast accepted");UnityEngine.Random.state=rng;mirror.Skill();Check(!c.RequestSkill(),"cooldown gate");v.Show(b);Capture(v,cam,rt,d,s,0);
    for(int f=1;f<120;f++){rng=UnityEngine.Random.state;b.Tick(1f/30);UnityEngine.Random.state=rng;mirror.Tick(1f/30);v.StepAnimation(b,1f/30);v.Show(b);CheckEqual(b,mirror);Capture(v,cam,rt,d,s,f);}
    Check(fx.DroppedLayers==0,"no pool overflow");if(data.icon!=null)Check(Array.Exists(v.skillButton.GetComponentsInChildren<Image>(),im=>im.sprite==data.icon&&im.enabled),"HUD icon data");Check(times.Count==data.hitCount,"hit count preserved");for(int i=0;i<times.Count;i++)Check(Math.Abs(times[i]-data.initialHitDelay-i*data.hitInterval)<.034,"hit time preserved");Check(Math.Abs(b.SkillReady-mirror.SkillReady)<.0001&&Time.timeScale==1,"cooldown and clock preserved");Check(objects==v.frame.GetComponentsInChildren<Transform>(true).Length,"pool stable");Check(v.skillButton.transform.Find("Equipped skill name").GetComponent<Text>().text==data.displayName,"HUD name unchanged");Debug.Log("WATER_SKILL_OK "+d+"/"+s+" hits="+times.Count+" damage="+damageSum+" peak="+fx.PeakImages+" origin="+fx.LastOrigin);
    if(SessionState.GetBool("WaterAll",false)){for(int warm=0;warm<2;warm++)Cycle(fx,b,data);var watch=new System.Diagnostics.Stopwatch();long before=GC.GetAllocatedBytesForCurrentThread();watch.Start();for(int run=0;run<4;run++)Cycle(fx,b,data);watch.Stop();long allocated=GC.GetAllocatedBytesForCurrentThread()-before;Debug.Log("WATER_PERF "+d+"/"+s+" ms="+watch.Elapsed.TotalMilliseconds/480+" bytes="+allocated);Check(allocated==0,"warmed VFX no managed allocation");}
    b.Tick(15);v.StepAnimation(b,15);Check(fx.ActiveImages==0,"expiry clean");times.Clear();Check(c.RequestSkill(),"repeat cast");c.EndBattle();Check(fx.ActiveImages==0,"exit clean");
    var weak=enemy;weak.maxHP=1;c.BeginBattle(dragon,stats,weak,1,false,stats.maxHP,null,20,data);c.RequestSkill();c.CurrentBattle.Tick(data.initialHitDelay+.034f);v.StepAnimation(c.CurrentBattle,.034f);Check(fx.ActiveImages==0,"death clean");
   }cam.targetTexture=null;rt.Release();UnityEngine.Object.DestroyImmediate(rt);
  }
  static void Cycle(WaterSkillVfx fx,BattleModel b,SkillData data){fx.Cast();fx.Hit(true);int next=1;for(int f=1;f<=120;f++){float t=f/60f;if(next<data.hitCount&&t>=next*data.hitInterval){fx.Hit(false);next++;}fx.Step(b,1f/60);}fx.Clear();}
  public static void BuildWeb(){WaterBatchSetup.Install(3);const string path="Assets/Scenes/Prototypes/WaterBatchPreview.unity";EditorSceneManager.OpenScene("Assets/Scenes/Battle.unity");var preview=new GameObject("Water shared skills review").AddComponent<WaterBatchPreview>();preview.dragons=new[]{AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon13.asset"),AssetDatabase.LoadAssetAtPath<DragonData>("Assets/Data/Dragon5.asset")};preview.library=AssetDatabase.LoadAssetAtPath<WaterSkillLibrary>("Assets/Resources/WaterSkills/Library.asset");EditorSceneManager.SaveScene(EditorSceneManager.GetActiveScene(),path);var report=BuildPipeline.BuildPlayer(new[]{path},"../WaterBatch-WebGL",BuildTarget.WebGL,BuildOptions.None);if(report.summary.result!=UnityEditor.Build.Reporting.BuildResult.Succeeded)throw new Exception("Water batch WebGL failed");Debug.Log("WATER_BATCH_WEBGL_OK");}
  static void CheckEqual(BattleModel a,BattleModel b){if(a.EnemyHP!=b.EnemyHP||a.PlayerHP!=b.PlayerHP||a.EnemyBurning!=b.EnemyBurning||a.EnemySlowed!=b.EnemySlowed||a.EnemySlowPower!=b.EnemySlowPower||a.EnemyParalyzed!=b.EnemyParalyzed||a.EnemyStunned!=b.EnemyStunned||a.AttackReady!=b.AttackReady||a.DodgeReady!=b.DodgeReady||a.SkillReady!=b.SkillReady)throw new Exception("WATER_BATCH_FAIL presentation changed combat outcome");}
  static void Capture(BattleView v,Camera cam,RenderTexture rt,int d,int s,int f){Canvas.ForceUpdateCanvases();v.frame.localScale=Vector3.one;v.frame.anchoredPosition=Vector2.zero;cam.Render();var old=RenderTexture.active;RenderTexture.active=rt;var t=new Texture2D(480,850,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,480,850),0,0);t.Apply();File.WriteAllBytes("Validation/WaterBatch/"+(d==0?"sharkid":"octa")+"-"+s+"-"+f.ToString("000")+".png",t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);RenderTexture.active=old;}
 }
}



