from pathlib import Path
p=Path('Assets/Scripts/BattleAnimation.cs');s=p.read_text(encoding='utf-8-sig')
s=s.replace('bool zephyrWind;','DantianVfx dantianVfx;DantianFeedback dantianFeedback;\n        bool zephyrWind;')
s=s.replace('clawFeedback.Initialize();','clawFeedback.Initialize();dantianVfx=gameObject.AddComponent<DantianVfx>();dantianVfx.Initialize(view);dantianFeedback=gameObject.AddComponent<DantianFeedback>();dantianFeedback.Initialize();')
s=s.replace('skill.StableId=="skill_wind_claw"))','skill.StableId=="skill_wind_claw"||skill.StableId=="skill_dantian"))')
s=s.replace('clawFeedback.Bind(player,enemy,playerGraphic,enemyGraphic);','clawFeedback.Bind(player,enemy,playerGraphic,enemyGraphic);dantianVfx.Configure(skill,playerGraphic);dantianFeedback.Bind(player,enemy,playerGraphic,enemyGraphic);')
s=s.replace('case CombatCue.SkillCast:\n','case CombatCue.SkillCast:\n                    if(dantianVfx.Configured){attackAge=dodgeAge=playerHitAge=10;skillAge=0;dantianVfx.Cast(playerHome,enemyHome);break;}\n')
s=s.replace('case CombatCue.Skill:\n','case CombatCue.Skill:\n                    if(dantianVfx.Configured){if(dantianVfx.Active){enemyHitAge=10;dantianVfx.Hit();dantianFeedback.Hit();Damage(enemyHome,damage.ToString(),WindVFXStyle.Pale,0,0,false,0,true);}break;}\n')
s=s.replace('case CombatCue.SkillHit:\n','case CombatCue.SkillHit:\n                    if(dantianVfx.Configured){Damage(enemyHome,damage.ToString(),WindVFXStyle.Mint,0);break;}\n')
s=s.replace('bool heavy=false,int clawHit=0)','bool heavy=false,int clawHit=0,bool legendary=false)')
s=s.replace('var n=numbers[numberIndex++%numbers.Length];n.active=true;', 'var n=numbers[numberIndex++%numbers.Length];n.text.transform.SetParent(legendary?dantianVfx.Overlay:layer,false);n.active=true;')
s=s.replace('n.age=-delay;n.color=color;', 'if(legendary){n.start=at+new Vector2(-88,70);n.text.fontSize=36;n.drift=new Vector2(-8,55);}n.age=-delay;n.color=color;')
s=s.replace('if(battle.Result!=BattleResult.Fighting)clawVfx.Clear();else clawVfx.Step(delta);','if(battle.Result!=BattleResult.Fighting)clawVfx.Clear();else clawVfx.Step(delta);\n            dantianVfx.Step(battle);')
s=s.replace('!slashVfx.Active&&!clawVfx.Active&&enemyHitAge','!slashVfx.Active&&!clawVfx.Active&&!dantianVfx.Active&&enemyHitAge')
s=s.replace('clawFeedback.Step(delta,fighting,!defensiveAction);','clawFeedback.Step(delta,fighting,!defensiveAction);dantianFeedback.Step(delta,fighting,!defensiveAction);')
p.write_text(s,encoding='utf-8')
p=Path('Assets/Scripts/DantianVfx.cs');s=p.read_text();s=s.replace('public int Capacity=>Count;','public int Capacity=>Count;\n        public RectTransform Overlay=>root;');p.write_text(s)
p=Path('Assets/Scripts/BattleController.cs');s=p.read_text(encoding='utf-8-sig');s=s.replace('public void EndBattle() { view.CancelGesture();battle=null; }','public void EndBattle() { CancelSignature();view.CancelGesture();battle=null; }\n        void CancelSignature(){battle?.CancelProtectedSkill();view.GetComponent<DantianVfx>()?.Cancel();view.GetComponent<DantianFeedback>()?.Clear();}\n        void OnDisable(){if(view!=null)CancelSignature();}')
s=s.replace('enemy.floor=floor;','CancelSignature();\n            enemy.floor=floor;')
s=s.replace('battle.Cue+=HandleCue;','var signature=view.GetComponent<DantianVfx>();if(signature!=null)signature.Cancelled=()=>{battle?.CancelProtectedSkill();view.GetComponent<DantianFeedback>()?.Clear();};\n            battle.Cue+=HandleCue;')
p.write_text(s,encoding='utf-8')
